local v=require("char_constant")

assert(v.CHAR_CONSTANT == 'x', 'CHAR_CONSTANT')
assert(string.byte(v.CHAR_CONSTANT) == 120, 'CHAR_CONSTANT value')
assert(v.STRING_CONSTANT == 'xyzzy', 'STRING_CONSTANT')
assert(v.ESC_CONST == '\01', 'ESC_CONST')
assert(string.byte(v.ESC_CONST) == 1, 'ESC_CONST value')
assert(v.NULL_CONST == '\0', 'NULL_CONST')
assert(string.byte(v.NULL_CONST) == 0, 'NULL_CONST value')
-- Latin small letter a with acute from ISO 8859-1/Latin-1
assert(string.byte(v.SPECIALCHAR) == 225, 'SPECIALCHAR')
assert(v.SPECIALCHAR2 == '\n', 'SPECIALCHAR2')
assert(string.byte(v.SPECIALCHAR2) == 10, 'SPECIALCHAR2 value')
assert(v.SPECIALCHARA == 'A', 'SPECIALCHARA')
assert(string.byte(v.SPECIALCHARA) == 65, 'SPECIALCHARA value')
assert(v.SPECIALCHARB == 'B', 'SPECIALCHARB')
assert(string.byte(v.SPECIALCHARB) == 66, 'SPECIALCHARB value')
assert(v.SPECIALCHARC == 'C', 'SPECIALCHARC')
assert(string.byte(v.SPECIALCHARC) == 67, 'SPECIALCHARC value')
assert(v.SPECIALCHARD == 68, 'SPECIALCHARD')
assert(string.char(v.SPECIALCHARD) == 'D', 'SPECIALCHARD char')
assert(v.SPECIALCHARE == 69, 'SPECIALCHARE')
assert(string.char(v.SPECIALCHARE) == 'E', 'SPECIALCHARE char')
-- Latin capital letter AE from ISO 8859-1/Latin-1
assert(string.byte(v.SPECIALCHARAE1) == 198, 'SPECIALCHARAE1 value')
assert(string.byte(v.SPECIALCHARAE2) == 198, 'SPECIALCHARAE2 value')
assert(string.byte(v.SPECIALCHARAE3) == 198, 'SPECIALCHARAE3 value')
assert(v.SPECIALCHARPAREN == ';', 'SPECIALCHARPAREN')
assert(string.byte(v.SPECIALCHARPAREN) == 59, 'SPECIALCHARPAREN value')
assert(v.X_ESC_CONST == '\01', 'X_ESC_CONST')
assert(string.byte(v.X_ESC_CONST) == 1, 'X_ESC_CONST value')
assert(v.X_NULL_CONST == '\0', 'X_NULL_CONST')
assert(string.byte(v.X_NULL_CONST) == 0, 'X_NULL_CONST value')
assert(string.byte(v.X_SPECIALCHAR) == 225, 'X_SPECIALCHAR')
assert(v.X_SPECIALCHAR2 == '\n', 'X_SPECIALCHAR2')
assert(string.byte(v.X_SPECIALCHAR2) == 10, 'X_SPECIALCHAR2 value')
assert(v.X_SPECIALCHARA == 'A', 'X_SPECIALCHARA')
assert(string.byte(v.X_SPECIALCHARA) == 65, 'X_SPECIALCHARA value')
assert(v.X_SPECIALCHARB == 'B', 'X_SPECIALCHARB')
assert(string.byte(v.X_SPECIALCHARB) == 66, 'X_SPECIALCHARB value')
assert(v.X_SPECIALCHARC == 'C', 'X_SPECIALCHARC')
assert(string.byte(v.X_SPECIALCHARC) == 67, 'X_SPECIALCHARC value')
assert(v.X_SPECIALCHARD == 68, 'X_SPECIALCHARD')
assert(string.char(v.X_SPECIALCHARD) == 'D', 'X_SPECIALCHARD char')
assert(v.X_SPECIALCHARE == 69, 'X_SPECIALCHARE')
assert(string.char(v.X_SPECIALCHARE) == 'E', 'X_SPECIALCHARE char')
-- Latin capital letter AE from ISO 8859-1/Latin-1
assert(string.byte(v.X_SPECIALCHARAE1) == 198, 'X_SPECIALCHARAE1 value')
assert(string.byte(v.X_SPECIALCHARAE2) == 198, 'X_SPECIALCHARAE2 value')
assert(string.byte(v.X_SPECIALCHARAE3) == 198, 'X_SPECIALCHARAE3 value')
assert(v.X_SPECIALCHARPAREN == ';', 'X_SPECIALCHARPAREN')
assert(string.byte(v.X_SPECIALCHARPAREN) == 59, 'X_SPECIALCHARPAREN value')
assert(v.ia == 97, 'ia') -- 'a' value
assert(v.ib == 98, 'ib') -- 'b' value
assert(v.iparen == 59, 'iparen') -- ';' value
