local v=require("class_scope_namespace")

local a = v.A()
assert(a ~= nil)
local b = v.B()
assert(b ~= nil)
local c = v.C()
assert(c ~= nil)
local d = v.D()
assert(d ~= nil)
local e = v.E()
assert(e ~= nil)
local f = v.F()
assert(f ~= nil)
local g = v.G()
assert(g ~= nil)
local h = v.H.HH()
assert(h ~= nil)
local i = v.I_.II()
assert(i ~= nil)
local j = v.J()
assert(j ~= nil)
local k = v.K()
assert(k ~= nil)
local l = v.L()
assert(l ~= nil)
local m = v.M()
assert(m ~= nil)

a:aa(a, a, a)
b:bb(b, b)
c:cc(c, c)
d:dd(d, d, d)
e:ee(e, e, e)
f:ff(f, f, f, f)
g:gg(g, g)
h:hh(h)
i:ii(i, i)
j:jj(j, j, j)
k:kk(k, k, k)
l:ll(l, l, l)
m:mm(m, m, m)

v.aaa(a, a, a)
v.bbb(b, b)
v.ccc(c, c)
v.ddd(d, d, d)
v.eee(e, e, e)
v.fff(f, f, f, f)
v.ggg(g, g)
v.hhh(h)
v.iii(i, i)
v.jjj(j, j, j)
v.kkk(k, k, k)
v.lll(l, l, l)
v.mmm(m, m, m)
