local v=require("cpp17_nspace_nested_namespaces")

v.A1.A1Struct():A1Method()
v.A1.B1.B1Struct():B1Method()
v.A1.B1.C1.C1Struct():C1Method()
v.createA1Struct():A1Method()
v.createB1Struct():B1Method()
v.createC1Struct():C1Method()
v.A2.B2.B2Struct():B2Method()
v.A2.B2.C2.C2Struct():C2Method()
v.createB2Struct():B2Method()
v.createC2Struct():C2Method()
v.A3.B3.B3Struct():B3Method()
v.A3.B3.C3.C3Struct():C3Method()
v.createB3Struct():B3Method()
v.createC3Struct():C3Method()
