require("default_arg_values")

local d = default_arg_values.Display()
assert(d:draw1() == 0)
assert(d:draw1(12) == 12)
assert(d:draw2() == 0)
local p = default_arg_values.createPtr(123)
assert(d:draw2(p) == 123)
assert(d:draw3() == 0)
assert(d:draw4() == 1)
assert(d:draw4(false) == -1)
assert(not d:bool0())
assert(d:bool1())
assert(not d:mybool0())
assert(d:mybool1())
