local v=require("rename_camel")

local g = v.GeometryFactory()
g:create_point_from_internal_coord(1)
g:big_method(2)

local b = v.ByteOrderValues()
b:read_hex()
assert(v.ByteOrderValues.ENDIANBIG == 4321)

v.CamelCase(15)
v.CamelCase1(17)
v.CamelCase2(16)
v.CamelCase3(56)
v.under_case(23)
v.under_case1(12)
v.under_case2(85)
v.under_case3(64)
v.lowerCamelCase(32)
v.lowerCamelCase1(10)
v.lowerCamelCase2(17)
v.lowerCamelCase3(54)
v.Import(17)
v.foo(31)
v.hello()

assert(v.HELLO == 0)
assert(v.HI_THERE == 1)
assert(v.BYE == 0)
assert(v.SEE_YOU  == 1)
