local v=require("special_variable_macros")

local name = v.Name()
assert(v.testFred(name) == "none")
assert(v.accessed_examplekw == 0, "Precondition failed")
assert(v.testJack(name) == "$specialname")
assert(v.accessed_examplekw == 1, "Postcondition failed")
assert(v.testJill(name) == "jilly")
assert(v.testMary(name) == "SWIGTYPE_p_NameWrap")
assert(v.testJames(name) == "SWIGTYPE_Name")
assert(v.testJim(name) == "multiname num")
assert(v.testJohn(v.PairIntBool(10, false)) == 123)
assert(v.makeStringInt("stringint", 999) == "stringint")
assert(v.provideStringInt(999) == "1000")
assert(v.shortFunction(1, 1) == (200*2 + 200*3))
