local v=require("template_using_directive_and_declaration_forward")

v.useit1(v.Thing1Int())
v.useit1a(v.Thing1Int())
v.useit1b(v.Thing1Int())
v.useit1c(v.Thing1Int())

v.useit2(v.Thing2Int())
v.useit2a(v.Thing2Int())
v.useit2b(v.Thing2Int())
v.useit2c(v.Thing2Int())
v.useit2d(v.Thing2Int())

v.useit3(v.Thing3Int())
v.useit3a(v.Thing3Int())
v.useit3b(v.Thing3Int())
v.useit3c(v.Thing3Int())
v.useit3d(v.Thing3Int())

v.useit4(v.Thing4Int())
v.useit4a(v.Thing4Int())
v.useit4b(v.Thing4Int())
v.useit4c(v.Thing4Int())
v.useit4d(v.Thing4Int())

v.useit5(v.Thing5Int())
v.useit5a(v.Thing5Int())
v.useit5b(v.Thing5Int())
v.useit5c(v.Thing5Int())
v.useit5d(v.Thing5Int())

v.useit7(v.Thing7Int())
v.useit7a(v.Thing7Int())
v.useit7b(v.Thing7Int())
v.useit7c(v.Thing7Int())
v.useit7d(v.Thing7Int())
