local v=require("template_class_reuse_name")

v.Bool1():tt()
v.Bool1False():ff()
v.Bool2():tt()
v.Bool2False():ff()
v.Bool3():tt()
v.Bool3False():ff()
v.Bool4():tt()
v.Bool4False():ff()
v.BoolForward1():tt()
v.BoolForward1False():ff()
v.BoolForward2():tt()
v.BoolForward2False():ff()
v.BoolForward3():tt()
v.BoolForward3False():ff()
v.BoolForward4():tt()
v.BoolForward4False():ff()
v.IntBool1():tt()
v.IntBool1False():ff()
v.IntBool2():tt()
v.IntBool2False():ff()
v.IntBool3():tt()
v.IntBool3False():ff()
v.IntBool4():tt()
v.IntBool4False():ff()
v.Duplicate2_0():n()
v.Duplicate3():n()
