/* -----------------------------------------------------------------------------
 * javascript.swg
 *
 * Javascript typemaps
 * ----------------------------------------------------------------------------- */

%include <typemaps/swigmacros.swg>

%include <javascripttypemaps.swg>

%include <javascriptruntime.swg>

%include <javascript/javascriptkw.swg>

%include <javascriptcode.swg>

%include <javascriptinit.swg>
