/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: ./../allprotected_not.i

package allprotected_not

import "unsafe"
import _ "runtime/cgo"

var _cgo_runtime_cgocall func(unsafe.Pointer, uintptr)



type _ unsafe.Pointer



type _swig_fnptr *byte
type _swig_memberptr *byte

type SwigcptrAllProtectedNot uintptr

func (p SwigcptrAllProtectedNot) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrAllProtectedNot) SwigIsAllProtectedNot() {
}

var _wrap_delete_AllProtectedNot unsafe.Pointer

func _swig_wrap_delete_AllProtectedNot(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_AllProtectedNot, _swig_p)
	return
}

func DeleteAllProtectedNot(arg1 AllProtectedNot) {
	_swig_wrap_delete_AllProtectedNot(arg1.Swigcptr())
}

var _wrap_AllProtectedNot_PublicMethod unsafe.Pointer

func _swig_wrap_AllProtectedNot_PublicMethod(base SwigcptrAllProtectedNot) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_AllProtectedNot_PublicMethod, _swig_p)
	return
}

func (arg1 SwigcptrAllProtectedNot) PublicMethod() {
	_swig_wrap_AllProtectedNot_PublicMethod(arg1)
}

var _wrap_new_AllProtectedNot unsafe.Pointer

func _swig_wrap_new_AllProtectedNot() (base SwigcptrAllProtectedNot) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_AllProtectedNot, _swig_p)
	return
}

func NewAllProtectedNot() (_swig_ret AllProtectedNot) {
	return _swig_wrap_new_AllProtectedNot()
}

type AllProtectedNot interface {
	Swigcptr() uintptr
	SwigIsAllProtectedNot()
	PublicMethod()
}


type SwigcptrVoid uintptr
type Void interface {
	Swigcptr() uintptr;
}
func (p SwigcptrVoid) Swigcptr() uintptr {
	return uintptr(p)
}

