/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: ./../cpp_static.i

package cpp_static

import "unsafe"
import _ "runtime/cgo"

var _cgo_runtime_cgocall func(unsafe.Pointer, uintptr)



type _ unsafe.Pointer



type _swig_fnptr *byte
type _swig_memberptr *byte

type SwigcptrStaticMemberTest uintptr

func (p SwigcptrStaticMemberTest) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrStaticMemberTest) SwigIsStaticMemberTest() {
}

var _wrap_StaticMemberTest_static_int_set unsafe.Pointer

func _swig_wrap_StaticMemberTest_static_int_set(base int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_StaticMemberTest_static_int_set, _swig_p)
	return
}

func SetStaticMemberTestStatic_int(arg1 int) {
	_swig_wrap_StaticMemberTest_static_int_set(arg1)
}

var _wrap_StaticMemberTest_static_int_get unsafe.Pointer

func GetStaticMemberTestStatic_int() (_swig_ret int) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_StaticMemberTest_static_int_get, _swig_p)
	return
}
var _wrap_new_StaticMemberTest unsafe.Pointer

func _swig_wrap_new_StaticMemberTest() (base SwigcptrStaticMemberTest) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_StaticMemberTest, _swig_p)
	return
}

func NewStaticMemberTest() (_swig_ret StaticMemberTest) {
	return _swig_wrap_new_StaticMemberTest()
}

var _wrap_delete_StaticMemberTest unsafe.Pointer

func _swig_wrap_delete_StaticMemberTest(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_StaticMemberTest, _swig_p)
	return
}

func DeleteStaticMemberTest(arg1 StaticMemberTest) {
	_swig_wrap_delete_StaticMemberTest(arg1.Swigcptr())
}

type StaticMemberTest interface {
	Swigcptr() uintptr
	SwigIsStaticMemberTest()
}

type SwigcptrStaticFunctionTest uintptr

func (p SwigcptrStaticFunctionTest) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrStaticFunctionTest) SwigIsStaticFunctionTest() {
}

var _wrap_StaticFunctionTest_static_func unsafe.Pointer

func _swig_wrap_StaticFunctionTest_static_func() {
	var _swig_p uintptr
	_cgo_runtime_cgocall(_wrap_StaticFunctionTest_static_func, _swig_p)
	return
}

func StaticFunctionTestStatic_func() {
	_swig_wrap_StaticFunctionTest_static_func()
}

var _wrap_StaticFunctionTest_static_func_2 unsafe.Pointer

func _swig_wrap_StaticFunctionTest_static_func_2(base int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_StaticFunctionTest_static_func_2, _swig_p)
	return
}

func StaticFunctionTestStatic_func_2(arg1 int) {
	_swig_wrap_StaticFunctionTest_static_func_2(arg1)
}

var _wrap_StaticFunctionTest_static_func_3 unsafe.Pointer

func _swig_wrap_StaticFunctionTest_static_func_3(base int, _ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_StaticFunctionTest_static_func_3, _swig_p)
	return
}

func StaticFunctionTestStatic_func_3(arg1 int, arg2 int) {
	_swig_wrap_StaticFunctionTest_static_func_3(arg1, arg2)
}

var _wrap_new_StaticFunctionTest unsafe.Pointer

func _swig_wrap_new_StaticFunctionTest() (base SwigcptrStaticFunctionTest) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_StaticFunctionTest, _swig_p)
	return
}

func NewStaticFunctionTest() (_swig_ret StaticFunctionTest) {
	return _swig_wrap_new_StaticFunctionTest()
}

var _wrap_delete_StaticFunctionTest unsafe.Pointer

func _swig_wrap_delete_StaticFunctionTest(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_StaticFunctionTest, _swig_p)
	return
}

func DeleteStaticFunctionTest(arg1 StaticFunctionTest) {
	_swig_wrap_delete_StaticFunctionTest(arg1.Swigcptr())
}

type StaticFunctionTest interface {
	Swigcptr() uintptr
	SwigIsStaticFunctionTest()
}


type SwigcptrVoid uintptr
type Void interface {
	Swigcptr() uintptr;
}
func (p SwigcptrVoid) Swigcptr() uintptr {
	return uintptr(p)
}

