/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: ./../curiously_recurring_template_pattern.i

package curiously_recurring_template_pattern

import "unsafe"
import _ "runtime/cgo"

var _cgo_runtime_cgocall func(unsafe.Pointer, uintptr)



type _ unsafe.Pointer



type _swig_fnptr *byte
type _swig_memberptr *byte

type SwigcptrBasederived uintptr

func (p SwigcptrBasederived) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrBasederived) SwigIsBasederived() {
}

var _wrap_new_basederived unsafe.Pointer

func _swig_wrap_new_basederived() (base SwigcptrBasederived) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_basederived, _swig_p)
	return
}

func NewBasederived() (_swig_ret Basederived) {
	return _swig_wrap_new_basederived()
}

var _wrap_basederived_getBase1Param unsafe.Pointer

func _swig_wrap_basederived_getBase1Param(base SwigcptrBasederived) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_basederived_getBase1Param, _swig_p)
	return
}

func (arg1 SwigcptrBasederived) GetBase1Param() (_swig_ret int) {
	return _swig_wrap_basederived_getBase1Param(arg1)
}

var _wrap_basederived_setBase1Param unsafe.Pointer

func _swig_wrap_basederived_setBase1Param(base SwigcptrBasederived, _ int) (_ SwigcptrDerived) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_basederived_setBase1Param, _swig_p)
	return
}

func (arg1 SwigcptrBasederived) SetBase1Param(arg2 int) (_swig_ret Derived) {
	return _swig_wrap_basederived_setBase1Param(arg1, arg2)
}

var _wrap_basederived_getBase2Param unsafe.Pointer

func _swig_wrap_basederived_getBase2Param(base SwigcptrBasederived) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_basederived_getBase2Param, _swig_p)
	return
}

func (arg1 SwigcptrBasederived) GetBase2Param() (_swig_ret int) {
	return _swig_wrap_basederived_getBase2Param(arg1)
}

var _wrap_basederived_setBase2Param unsafe.Pointer

func _swig_wrap_basederived_setBase2Param(base SwigcptrBasederived, _ int) (_ SwigcptrDerived) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_basederived_setBase2Param, _swig_p)
	return
}

func (arg1 SwigcptrBasederived) SetBase2Param(arg2 int) (_swig_ret Derived) {
	return _swig_wrap_basederived_setBase2Param(arg1, arg2)
}

var _wrap_delete_basederived unsafe.Pointer

func _swig_wrap_delete_basederived(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_basederived, _swig_p)
	return
}

func DeleteBasederived(arg1 Basederived) {
	_swig_wrap_delete_basederived(arg1.Swigcptr())
}

type Basederived interface {
	Swigcptr() uintptr
	SwigIsBasederived()
	GetBase1Param() (_swig_ret int)
	SetBase1Param(arg2 int) (_swig_ret Derived)
	GetBase2Param() (_swig_ret int)
	SetBase2Param(arg2 int) (_swig_ret Derived)
}

type SwigcptrDerived uintptr

func (p SwigcptrDerived) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrDerived) SwigIsDerived() {
}

var _wrap_new_Derived unsafe.Pointer

func _swig_wrap_new_Derived() (base SwigcptrDerived) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_Derived, _swig_p)
	return
}

func NewDerived() (_swig_ret Derived) {
	return _swig_wrap_new_Derived()
}

var _wrap_Derived_getDerived1Param unsafe.Pointer

func _swig_wrap_Derived_getDerived1Param(base SwigcptrDerived) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Derived_getDerived1Param, _swig_p)
	return
}

func (arg1 SwigcptrDerived) GetDerived1Param() (_swig_ret int) {
	return _swig_wrap_Derived_getDerived1Param(arg1)
}

var _wrap_Derived_setDerived1Param unsafe.Pointer

func _swig_wrap_Derived_setDerived1Param(base SwigcptrDerived, _ int) (_ SwigcptrDerived) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Derived_setDerived1Param, _swig_p)
	return
}

func (arg1 SwigcptrDerived) SetDerived1Param(arg2 int) (_swig_ret Derived) {
	return _swig_wrap_Derived_setDerived1Param(arg1, arg2)
}

var _wrap_Derived_getDerived2Param unsafe.Pointer

func _swig_wrap_Derived_getDerived2Param(base SwigcptrDerived) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Derived_getDerived2Param, _swig_p)
	return
}

func (arg1 SwigcptrDerived) GetDerived2Param() (_swig_ret int) {
	return _swig_wrap_Derived_getDerived2Param(arg1)
}

var _wrap_Derived_setDerived2Param unsafe.Pointer

func _swig_wrap_Derived_setDerived2Param(base SwigcptrDerived, _ int) (_ SwigcptrDerived) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Derived_setDerived2Param, _swig_p)
	return
}

func (arg1 SwigcptrDerived) SetDerived2Param(arg2 int) (_swig_ret Derived) {
	return _swig_wrap_Derived_setDerived2Param(arg1, arg2)
}

var _wrap_delete_Derived unsafe.Pointer

func _swig_wrap_delete_Derived(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_Derived, _swig_p)
	return
}

func DeleteDerived(arg1 Derived) {
	_swig_wrap_delete_Derived(arg1.Swigcptr())
}

var _wrap_Derived_getBase1Param unsafe.Pointer

func _swig_wrap_Derived_getBase1Param(base SwigcptrDerived) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Derived_getBase1Param, _swig_p)
	return
}

func (_swig_base SwigcptrDerived) GetBase1Param() (_swig_ret int) {
	return _swig_wrap_Derived_getBase1Param(_swig_base)
}

var _wrap_Derived_setBase1Param unsafe.Pointer

func _swig_wrap_Derived_setBase1Param(base SwigcptrDerived, _ int) (_ SwigcptrDerived) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Derived_setBase1Param, _swig_p)
	return
}

func (_swig_base SwigcptrDerived) SetBase1Param(arg1 int) (_swig_ret Derived) {
	return _swig_wrap_Derived_setBase1Param(_swig_base, arg1)
}

var _wrap_Derived_getBase2Param unsafe.Pointer

func _swig_wrap_Derived_getBase2Param(base SwigcptrDerived) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Derived_getBase2Param, _swig_p)
	return
}

func (_swig_base SwigcptrDerived) GetBase2Param() (_swig_ret int) {
	return _swig_wrap_Derived_getBase2Param(_swig_base)
}

var _wrap_Derived_setBase2Param unsafe.Pointer

func _swig_wrap_Derived_setBase2Param(base SwigcptrDerived, _ int) (_ SwigcptrDerived) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Derived_setBase2Param, _swig_p)
	return
}

func (_swig_base SwigcptrDerived) SetBase2Param(arg1 int) (_swig_ret Derived) {
	return _swig_wrap_Derived_setBase2Param(_swig_base, arg1)
}

func (p SwigcptrDerived) SwigIsBasederived() {
}

func (p SwigcptrDerived) SwigGetBasederived() Basederived {
	return SwigcptrBasederived(p.Swigcptr())
}

type Derived interface {
	Swigcptr() uintptr
	SwigIsDerived()
	GetDerived1Param() (_swig_ret int)
	SetDerived1Param(arg2 int) (_swig_ret Derived)
	GetDerived2Param() (_swig_ret int)
	SetDerived2Param(arg2 int) (_swig_ret Derived)
	GetBase1Param() (_swig_ret int)
	SetBase1Param(arg1 int) (_swig_ret Derived)
	GetBase2Param() (_swig_ret int)
	SetBase2Param(arg1 int) (_swig_ret Derived)
	SwigIsBasederived()
	SwigGetBasederived() Basederived
}


type SwigcptrVoid uintptr
type Void interface {
	Swigcptr() uintptr;
}
func (p SwigcptrVoid) Swigcptr() uintptr {
	return uintptr(p)
}

