/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: ./../director_abstract.i

package director_abstract

import "unsafe"
import _ "runtime/cgo"

var _cgo_runtime_cgocall func(unsafe.Pointer, uintptr)



type _ unsafe.Pointer



type _swig_fnptr *byte
type _swig_memberptr *byte

type _swig_DirectorFoo struct {
	SwigcptrFoo
	v interface{}
}

func (p *_swig_DirectorFoo) Swigcptr() uintptr {
	return p.SwigcptrFoo.Swigcptr()
}

func (p *_swig_DirectorFoo) SwigIsFoo() {
}

func (p *_swig_DirectorFoo) DirectorInterface() interface{} {
	return p.v
}

var _wrap__swig_NewDirectorFooFoo unsafe.Pointer

func _swig_NewDirectorFooFoo(_swig_director *_swig_DirectorFoo) (_swig_ret SwigcptrFoo) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_director))
	_cgo_runtime_cgocall(_wrap__swig_NewDirectorFooFoo, _swig_p)
	return
}

func NewDirectorFoo(v interface{}) Foo {
	p := &_swig_DirectorFoo{0, v}
	p.SwigcptrFoo = _swig_NewDirectorFooFoo(p)
	return p
}

var _wrap_DeleteDirectorFoo unsafe.Pointer

func _swig_wrap_DeleteDirectorFoo(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_DeleteDirectorFoo, _swig_p)
	return
}

func DeleteDirectorFoo(arg1 Foo) {
	_swig_wrap_DeleteDirectorFoo(arg1.Swigcptr())
}

func Swiggo_DeleteDirector_Foo(p *_swig_DirectorFoo) {
	p.SwigcptrFoo = 0
}

type _swig_DirectorInterfaceFooPing interface {
	Ping() string
}

func (swig_p *_swig_DirectorFoo) Ping() string {
	if swig_g, swig_ok := swig_p.v.(_swig_DirectorInterfaceFooPing); swig_ok {
		return swig_g.Ping()
	}
	panic("call to pure virtual method")
}

func Swig_DirectorFoo_callback_ping(p *_swig_DirectorFoo) (swig_result string) {
	var swig_r string
	swig_r = p.Ping()
	return swig_r
}

type _swig_DirectorInterfaceFooPong interface {
	Pong() string
}

var _wrap__swig_DirectorFoo_upcall_Pong unsafe.Pointer

func _swig_wrap__swig_DirectorFoo_upcall_Pong(_swig_ptr SwigcptrFoo) (_swig_ret string) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ptr))
	_cgo_runtime_cgocall(_wrap__swig_DirectorFoo_upcall_Pong, _swig_p)
	return
}

func (swig_p *_swig_DirectorFoo) Pong() string {
	if swig_g, swig_ok := swig_p.v.(_swig_DirectorInterfaceFooPong); swig_ok {
		return swig_g.Pong()
	}
	var swig_r string
	swig_r = _swig_wrap__swig_DirectorFoo_upcall_Pong(swig_p.SwigcptrFoo)
	return swig_r
}

func DirectorFooPong(p Foo) string {
	var swig_r string
	swig_r = _swig_wrap__swig_DirectorFoo_upcall_Pong(p.(*_swig_DirectorFoo).SwigcptrFoo)
	return swig_r
}

func Swig_DirectorFoo_callback_pong(p *_swig_DirectorFoo) (swig_result string) {
	var swig_r string
	swig_r = p.Pong()
	return swig_r
}

type SwigcptrFoo uintptr

func (p SwigcptrFoo) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrFoo) SwigIsFoo() {
}

func (p SwigcptrFoo) DirectorInterface() interface{} {
	return nil
}

var _wrap_delete_Foo unsafe.Pointer

func _swig_wrap_delete_Foo(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_Foo, _swig_p)
	return
}

func DeleteFoo(arg1 Foo) {
	_swig_wrap_delete_Foo(arg1.Swigcptr())
}

var _wrap_Foo_ping unsafe.Pointer

func _swig_wrap_Foo_ping(base SwigcptrFoo) (_ string) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Foo_ping, _swig_p)
	return
}

func (arg1 SwigcptrFoo) Ping() (_swig_ret string) {
	return _swig_wrap_Foo_ping(arg1)
}

var _wrap_Foo_pong unsafe.Pointer

func _swig_wrap_Foo_pong(base SwigcptrFoo) (_ string) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Foo_pong, _swig_p)
	return
}

func (arg1 SwigcptrFoo) Pong() (_swig_ret string) {
	return _swig_wrap_Foo_pong(arg1)
}

var _wrap_new_Foo unsafe.Pointer

func _swig_wrap_new_Foo() (base SwigcptrFoo) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_Foo, _swig_p)
	return
}

func NewFoo() (_swig_ret Foo) {
	return _swig_wrap_new_Foo()
}

type Foo interface {
	Swigcptr() uintptr
	SwigIsFoo()
	DirectorInterface() interface{}
	Ping() (_swig_ret string)
	Pong() (_swig_ret string)
}

type _swig_DirectorExample0 struct {
	SwigcptrExample0
	v interface{}
}

func (p *_swig_DirectorExample0) Swigcptr() uintptr {
	return p.SwigcptrExample0.Swigcptr()
}

func (p *_swig_DirectorExample0) SwigIsExample0() {
}

func (p *_swig_DirectorExample0) DirectorInterface() interface{} {
	return p.v
}

var _wrap__swig_NewDirectorExample0Example0__SWIG_0 unsafe.Pointer

func _swig_NewDirectorExample0Example0__SWIG_0(_swig_director *_swig_DirectorExample0, _ int, _ int) (_swig_ret SwigcptrExample0) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_director))
	_cgo_runtime_cgocall(_wrap__swig_NewDirectorExample0Example0__SWIG_0, _swig_p)
	return
}

func NewDirectorExample0__SWIG_0(v interface{}, arg1 int, arg2 int) Example0 {
	p := &_swig_DirectorExample0{0, v}
	p.SwigcptrExample0 = _swig_NewDirectorExample0Example0__SWIG_0(p, arg1, arg2)
	return p
}

var _wrap__swig_NewDirectorExample0Example0__SWIG_1 unsafe.Pointer

func _swig_NewDirectorExample0Example0__SWIG_1(_swig_director *_swig_DirectorExample0) (_swig_ret SwigcptrExample0) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_director))
	_cgo_runtime_cgocall(_wrap__swig_NewDirectorExample0Example0__SWIG_1, _swig_p)
	return
}

func NewDirectorExample0__SWIG_1(v interface{}) Example0 {
	p := &_swig_DirectorExample0{0, v}
	p.SwigcptrExample0 = _swig_NewDirectorExample0Example0__SWIG_1(p)
	return p
}

func NewDirectorExample0(abi interface{}, a ...interface{}) Example0 {
	argc := len(a)
	if argc == 0 {
		return NewDirectorExample0__SWIG_1(abi)
	}
	if argc == 2 {
		return NewDirectorExample0__SWIG_0(abi, a[0].(int), a[1].(int))
	}
	panic("No match for overloaded function call")
}

var _wrap_DeleteDirectorExample0 unsafe.Pointer

func _swig_wrap_DeleteDirectorExample0(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_DeleteDirectorExample0, _swig_p)
	return
}

func DeleteDirectorExample0(arg1 Example0) {
	_swig_wrap_DeleteDirectorExample0(arg1.Swigcptr())
}

func Swiggo_DeleteDirector_Example0(p *_swig_DirectorExample0) {
	p.SwigcptrExample0 = 0
}

type _swig_DirectorInterfaceExample0Color interface {
	Color(byte, byte, byte) int
}

var _wrap__swig_DirectorExample0_upcall_Color unsafe.Pointer

func _swig_wrap__swig_DirectorExample0_upcall_Color(_swig_ptr SwigcptrExample0, _ byte, _ byte, _ byte) (_swig_ret int) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ptr))
	_cgo_runtime_cgocall(_wrap__swig_DirectorExample0_upcall_Color, _swig_p)
	return
}

func (swig_p *_swig_DirectorExample0) Color(r byte, g byte, b byte) int {
	if swig_g, swig_ok := swig_p.v.(_swig_DirectorInterfaceExample0Color); swig_ok {
		return swig_g.Color(r, g, b)
	}
	var swig_r int
	swig_r = _swig_wrap__swig_DirectorExample0_upcall_Color(swig_p.SwigcptrExample0, r, g, b)
	return swig_r
}

func DirectorExample0Color(p Example0, arg2 byte, arg3 byte, arg4 byte) int {
	var swig_r int
	swig_r = _swig_wrap__swig_DirectorExample0_upcall_Color(p.(*_swig_DirectorExample0).SwigcptrExample0, arg2, arg3, arg4)
	return swig_r
}

func Swig_DirectorExample0_callback_Color(p *_swig_DirectorExample0, arg2 byte, arg3 byte, arg4 byte) (swig_result int) {
	var swig_r int
	swig_r = p.Color(arg2, arg3, arg4)
	return swig_r
}

type SwigcptrExample0 uintptr

func (p SwigcptrExample0) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrExample0) SwigIsExample0() {
}

func (p SwigcptrExample0) DirectorInterface() interface{} {
	return nil
}

var _wrap_new_Example0__SWIG_0 unsafe.Pointer

func _swig_wrap_new_Example0__SWIG_0(base int, _ int) (_ SwigcptrExample0) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_Example0__SWIG_0, _swig_p)
	return
}

func NewExample0__SWIG_0(arg1 int, arg2 int) (_swig_ret Example0) {
	return _swig_wrap_new_Example0__SWIG_0(arg1, arg2)
}

var _wrap_new_Example0__SWIG_1 unsafe.Pointer

func _swig_wrap_new_Example0__SWIG_1() (base SwigcptrExample0) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_Example0__SWIG_1, _swig_p)
	return
}

func NewExample0__SWIG_1() (_swig_ret Example0) {
	return _swig_wrap_new_Example0__SWIG_1()
}

func NewExample0(a ...interface{}) Example0 {
	argc := len(a)
	if argc == 0 {
		return NewExample0__SWIG_1()
	}
	if argc == 2 {
		return NewExample0__SWIG_0(a[0].(int), a[1].(int))
	}
	panic("No match for overloaded function call")
}

var _wrap_delete_Example0 unsafe.Pointer

func _swig_wrap_delete_Example0(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_Example0, _swig_p)
	return
}

func DeleteExample0(arg1 Example0) {
	_swig_wrap_delete_Example0(arg1.Swigcptr())
}

var _wrap_Example0_GetXSize unsafe.Pointer

func _swig_wrap_Example0_GetXSize(base SwigcptrExample0) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Example0_GetXSize, _swig_p)
	return
}

func (arg1 SwigcptrExample0) GetXSize() (_swig_ret int) {
	return _swig_wrap_Example0_GetXSize(arg1)
}

var _wrap_Example0_Color unsafe.Pointer

func _swig_wrap_Example0_Color(base SwigcptrExample0, _ byte, _ byte, _ byte) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Example0_Color, _swig_p)
	return
}

func (arg1 SwigcptrExample0) Color(arg2 byte, arg3 byte, arg4 byte) (_swig_ret int) {
	return _swig_wrap_Example0_Color(arg1, arg2, arg3, arg4)
}

var _wrap_Example0_get_color unsafe.Pointer

func _swig_wrap_Example0_get_color(base uintptr, _ byte, _ byte, _ byte) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Example0_get_color, _swig_p)
	return
}

func Example0Get_color(arg1 Example0, arg2 byte, arg3 byte, arg4 byte) (_swig_ret int) {
	return _swig_wrap_Example0_get_color(arg1.Swigcptr(), arg2, arg3, arg4)
}

type Example0 interface {
	Swigcptr() uintptr
	SwigIsExample0()
	DirectorInterface() interface{}
	GetXSize() (_swig_ret int)
	Color(arg2 byte, arg3 byte, arg4 byte) (_swig_ret int)
}

type _swig_DirectorExample1 struct {
	SwigcptrExample1
	v interface{}
}

func (p *_swig_DirectorExample1) Swigcptr() uintptr {
	return p.SwigcptrExample1.Swigcptr()
}

func (p *_swig_DirectorExample1) SwigIsExample1() {
}

func (p *_swig_DirectorExample1) DirectorInterface() interface{} {
	return p.v
}

var _wrap__swig_NewDirectorExample1Example1__SWIG_0 unsafe.Pointer

func _swig_NewDirectorExample1Example1__SWIG_0(_swig_director *_swig_DirectorExample1, _ int, _ int) (_swig_ret SwigcptrExample1) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_director))
	_cgo_runtime_cgocall(_wrap__swig_NewDirectorExample1Example1__SWIG_0, _swig_p)
	return
}

func NewDirectorExample1__SWIG_0(v interface{}, arg1 int, arg2 int) Example1 {
	p := &_swig_DirectorExample1{0, v}
	p.SwigcptrExample1 = _swig_NewDirectorExample1Example1__SWIG_0(p, arg1, arg2)
	return p
}

var _wrap__swig_NewDirectorExample1Example1__SWIG_1 unsafe.Pointer

func _swig_NewDirectorExample1Example1__SWIG_1(_swig_director *_swig_DirectorExample1) (_swig_ret SwigcptrExample1) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_director))
	_cgo_runtime_cgocall(_wrap__swig_NewDirectorExample1Example1__SWIG_1, _swig_p)
	return
}

func NewDirectorExample1__SWIG_1(v interface{}) Example1 {
	p := &_swig_DirectorExample1{0, v}
	p.SwigcptrExample1 = _swig_NewDirectorExample1Example1__SWIG_1(p)
	return p
}

func NewDirectorExample1(abi interface{}, a ...interface{}) Example1 {
	argc := len(a)
	if argc == 0 {
		return NewDirectorExample1__SWIG_1(abi)
	}
	if argc == 2 {
		return NewDirectorExample1__SWIG_0(abi, a[0].(int), a[1].(int))
	}
	panic("No match for overloaded function call")
}

var _wrap_DeleteDirectorExample1 unsafe.Pointer

func _swig_wrap_DeleteDirectorExample1(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_DeleteDirectorExample1, _swig_p)
	return
}

func DeleteDirectorExample1(arg1 Example1) {
	_swig_wrap_DeleteDirectorExample1(arg1.Swigcptr())
}

func Swiggo_DeleteDirector_Example1(p *_swig_DirectorExample1) {
	p.SwigcptrExample1 = 0
}

type _swig_DirectorInterfaceExample1Color interface {
	Color(byte, byte, byte) int
}

func (swig_p *_swig_DirectorExample1) Color(r byte, g byte, b byte) int {
	if swig_g, swig_ok := swig_p.v.(_swig_DirectorInterfaceExample1Color); swig_ok {
		return swig_g.Color(r, g, b)
	}
	panic("call to pure virtual method")
}

func Swig_DirectorExample1_callback_Color(p *_swig_DirectorExample1, r byte, g byte, b byte) (swig_result int) {
	var swig_r int
	swig_r = p.Color(r, g, b)
	return swig_r
}

type SwigcptrExample1 uintptr

func (p SwigcptrExample1) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrExample1) SwigIsExample1() {
}

func (p SwigcptrExample1) DirectorInterface() interface{} {
	return nil
}

var _wrap_new_Example1__SWIG_0 unsafe.Pointer

func _swig_wrap_new_Example1__SWIG_0(base int, _ int) (_ SwigcptrExample1) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_Example1__SWIG_0, _swig_p)
	return
}

func NewExample1__SWIG_0(arg1 int, arg2 int) (_swig_ret Example1) {
	return _swig_wrap_new_Example1__SWIG_0(arg1, arg2)
}

var _wrap_new_Example1__SWIG_1 unsafe.Pointer

func _swig_wrap_new_Example1__SWIG_1() (base SwigcptrExample1) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_Example1__SWIG_1, _swig_p)
	return
}

func NewExample1__SWIG_1() (_swig_ret Example1) {
	return _swig_wrap_new_Example1__SWIG_1()
}

func NewExample1(a ...interface{}) Example1 {
	argc := len(a)
	if argc == 0 {
		return NewExample1__SWIG_1()
	}
	if argc == 2 {
		return NewExample1__SWIG_0(a[0].(int), a[1].(int))
	}
	panic("No match for overloaded function call")
}

var _wrap_delete_Example1 unsafe.Pointer

func _swig_wrap_delete_Example1(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_Example1, _swig_p)
	return
}

func DeleteExample1(arg1 Example1) {
	_swig_wrap_delete_Example1(arg1.Swigcptr())
}

var _wrap_Example1_GetXSize unsafe.Pointer

func _swig_wrap_Example1_GetXSize(base SwigcptrExample1) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Example1_GetXSize, _swig_p)
	return
}

func (arg1 SwigcptrExample1) GetXSize() (_swig_ret int) {
	return _swig_wrap_Example1_GetXSize(arg1)
}

var _wrap_Example1_Color unsafe.Pointer

func _swig_wrap_Example1_Color(base SwigcptrExample1, _ byte, _ byte, _ byte) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Example1_Color, _swig_p)
	return
}

func (arg1 SwigcptrExample1) Color(arg2 byte, arg3 byte, arg4 byte) (_swig_ret int) {
	return _swig_wrap_Example1_Color(arg1, arg2, arg3, arg4)
}

var _wrap_Example1_get_color unsafe.Pointer

func _swig_wrap_Example1_get_color(base uintptr, _ byte, _ byte, _ byte) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Example1_get_color, _swig_p)
	return
}

func Example1Get_color(arg1 Example1, arg2 byte, arg3 byte, arg4 byte) (_swig_ret int) {
	return _swig_wrap_Example1_get_color(arg1.Swigcptr(), arg2, arg3, arg4)
}

type Example1 interface {
	Swigcptr() uintptr
	SwigIsExample1()
	DirectorInterface() interface{}
	GetXSize() (_swig_ret int)
	Color(arg2 byte, arg3 byte, arg4 byte) (_swig_ret int)
}

type _swig_DirectorExample2 struct {
	SwigcptrExample2
	v interface{}
}

func (p *_swig_DirectorExample2) Swigcptr() uintptr {
	return p.SwigcptrExample2.Swigcptr()
}

func (p *_swig_DirectorExample2) SwigIsExample2() {
}

func (p *_swig_DirectorExample2) DirectorInterface() interface{} {
	return p.v
}

var _wrap__swig_NewDirectorExample2Example2__SWIG_0 unsafe.Pointer

func _swig_NewDirectorExample2Example2__SWIG_0(_swig_director *_swig_DirectorExample2, _ int) (_swig_ret SwigcptrExample2) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_director))
	_cgo_runtime_cgocall(_wrap__swig_NewDirectorExample2Example2__SWIG_0, _swig_p)
	return
}

func NewDirectorExample2__SWIG_0(v interface{}, arg1 int) Example2 {
	p := &_swig_DirectorExample2{0, v}
	p.SwigcptrExample2 = _swig_NewDirectorExample2Example2__SWIG_0(p, arg1)
	return p
}

var _wrap__swig_NewDirectorExample2Example2__SWIG_1 unsafe.Pointer

func _swig_NewDirectorExample2Example2__SWIG_1(_swig_director *_swig_DirectorExample2, _ int, _ int) (_swig_ret SwigcptrExample2) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_director))
	_cgo_runtime_cgocall(_wrap__swig_NewDirectorExample2Example2__SWIG_1, _swig_p)
	return
}

func NewDirectorExample2__SWIG_1(v interface{}, arg1 int, arg2 int) Example2 {
	p := &_swig_DirectorExample2{0, v}
	p.SwigcptrExample2 = _swig_NewDirectorExample2Example2__SWIG_1(p, arg1, arg2)
	return p
}

func NewDirectorExample2(abi interface{}, a ...interface{}) Example2 {
	argc := len(a)
	if argc == 1 {
		return NewDirectorExample2__SWIG_0(abi, a[0].(int))
	}
	if argc == 2 {
		return NewDirectorExample2__SWIG_1(abi, a[0].(int), a[1].(int))
	}
	panic("No match for overloaded function call")
}

var _wrap_DeleteDirectorExample2 unsafe.Pointer

func _swig_wrap_DeleteDirectorExample2(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_DeleteDirectorExample2, _swig_p)
	return
}

func DeleteDirectorExample2(arg1 Example2) {
	_swig_wrap_DeleteDirectorExample2(arg1.Swigcptr())
}

func Swiggo_DeleteDirector_Example2(p *_swig_DirectorExample2) {
	p.SwigcptrExample2 = 0
}

type _swig_DirectorInterfaceExample2Color interface {
	Color(byte, byte, byte) int
}

func (swig_p *_swig_DirectorExample2) Color(r byte, g byte, b byte) int {
	if swig_g, swig_ok := swig_p.v.(_swig_DirectorInterfaceExample2Color); swig_ok {
		return swig_g.Color(r, g, b)
	}
	panic("call to pure virtual method")
}

func Swig_DirectorExample2_callback_Color(p *_swig_DirectorExample2, r byte, g byte, b byte) (swig_result int) {
	var swig_r int
	swig_r = p.Color(r, g, b)
	return swig_r
}

type SwigcptrExample2 uintptr

func (p SwigcptrExample2) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrExample2) SwigIsExample2() {
}

func (p SwigcptrExample2) DirectorInterface() interface{} {
	return nil
}

var _wrap_new_Example2__SWIG_0 unsafe.Pointer

func _swig_wrap_new_Example2__SWIG_0(base int) (_ SwigcptrExample2) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_Example2__SWIG_0, _swig_p)
	return
}

func NewExample2__SWIG_0(arg1 int) (_swig_ret Example2) {
	return _swig_wrap_new_Example2__SWIG_0(arg1)
}

var _wrap_new_Example2__SWIG_1 unsafe.Pointer

func _swig_wrap_new_Example2__SWIG_1(base int, _ int) (_ SwigcptrExample2) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_Example2__SWIG_1, _swig_p)
	return
}

func NewExample2__SWIG_1(arg1 int, arg2 int) (_swig_ret Example2) {
	return _swig_wrap_new_Example2__SWIG_1(arg1, arg2)
}

func NewExample2(a ...interface{}) Example2 {
	argc := len(a)
	if argc == 1 {
		return NewExample2__SWIG_0(a[0].(int))
	}
	if argc == 2 {
		return NewExample2__SWIG_1(a[0].(int), a[1].(int))
	}
	panic("No match for overloaded function call")
}

var _wrap_delete_Example2 unsafe.Pointer

func _swig_wrap_delete_Example2(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_Example2, _swig_p)
	return
}

func DeleteExample2(arg1 Example2) {
	_swig_wrap_delete_Example2(arg1.Swigcptr())
}

var _wrap_Example2_GetXSize unsafe.Pointer

func _swig_wrap_Example2_GetXSize(base SwigcptrExample2) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Example2_GetXSize, _swig_p)
	return
}

func (arg1 SwigcptrExample2) GetXSize() (_swig_ret int) {
	return _swig_wrap_Example2_GetXSize(arg1)
}

var _wrap_Example2_Color unsafe.Pointer

func _swig_wrap_Example2_Color(base SwigcptrExample2, _ byte, _ byte, _ byte) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Example2_Color, _swig_p)
	return
}

func (arg1 SwigcptrExample2) Color(arg2 byte, arg3 byte, arg4 byte) (_swig_ret int) {
	return _swig_wrap_Example2_Color(arg1, arg2, arg3, arg4)
}

var _wrap_Example2_get_color unsafe.Pointer

func _swig_wrap_Example2_get_color(base uintptr, _ byte, _ byte, _ byte) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Example2_get_color, _swig_p)
	return
}

func Example2Get_color(arg1 Example2, arg2 byte, arg3 byte, arg4 byte) (_swig_ret int) {
	return _swig_wrap_Example2_get_color(arg1.Swigcptr(), arg2, arg3, arg4)
}

type Example2 interface {
	Swigcptr() uintptr
	SwigIsExample2()
	DirectorInterface() interface{}
	GetXSize() (_swig_ret int)
	Color(arg2 byte, arg3 byte, arg4 byte) (_swig_ret int)
}

type _swig_DirectorExample4 struct {
	SwigcptrExample4
	v interface{}
}

func (p *_swig_DirectorExample4) Swigcptr() uintptr {
	return p.SwigcptrExample4.Swigcptr()
}

func (p *_swig_DirectorExample4) SwigIsExample4() {
}

func (p *_swig_DirectorExample4) DirectorInterface() interface{} {
	return p.v
}

var _wrap__swig_NewDirectorExample4Example4__SWIG_0 unsafe.Pointer

func _swig_NewDirectorExample4Example4__SWIG_0(_swig_director *_swig_DirectorExample4) (_swig_ret SwigcptrExample4) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_director))
	_cgo_runtime_cgocall(_wrap__swig_NewDirectorExample4Example4__SWIG_0, _swig_p)
	return
}

func NewDirectorExample4__SWIG_0(v interface{}) Example4 {
	p := &_swig_DirectorExample4{0, v}
	p.SwigcptrExample4 = _swig_NewDirectorExample4Example4__SWIG_0(p)
	return p
}

var _wrap__swig_NewDirectorExample4Example4__SWIG_1 unsafe.Pointer

func _swig_NewDirectorExample4Example4__SWIG_1(_swig_director *_swig_DirectorExample4, _ int, _ int) (_swig_ret SwigcptrExample4) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_director))
	_cgo_runtime_cgocall(_wrap__swig_NewDirectorExample4Example4__SWIG_1, _swig_p)
	return
}

func NewDirectorExample4__SWIG_1(v interface{}, arg1 int, arg2 int) Example4 {
	p := &_swig_DirectorExample4{0, v}
	p.SwigcptrExample4 = _swig_NewDirectorExample4Example4__SWIG_1(p, arg1, arg2)
	return p
}

func NewDirectorExample4(abi interface{}, a ...interface{}) Example4 {
	argc := len(a)
	if argc == 0 {
		return NewDirectorExample4__SWIG_0(abi)
	}
	if argc == 2 {
		return NewDirectorExample4__SWIG_1(abi, a[0].(int), a[1].(int))
	}
	panic("No match for overloaded function call")
}

var _wrap_DeleteDirectorExample4 unsafe.Pointer

func _swig_wrap_DeleteDirectorExample4(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_DeleteDirectorExample4, _swig_p)
	return
}

func DeleteDirectorExample4(arg1 Example4) {
	_swig_wrap_DeleteDirectorExample4(arg1.Swigcptr())
}

func Swiggo_DeleteDirector_Example4(p *_swig_DirectorExample4) {
	p.SwigcptrExample4 = 0
}

type _swig_DirectorInterfaceExample4Color interface {
	Color(byte, byte, byte) int
}

func (swig_p *_swig_DirectorExample4) Color(r byte, g byte, b byte) int {
	if swig_g, swig_ok := swig_p.v.(_swig_DirectorInterfaceExample4Color); swig_ok {
		return swig_g.Color(r, g, b)
	}
	panic("call to pure virtual method")
}

func Swig_DirectorExample4_callback_Color(p *_swig_DirectorExample4, r byte, g byte, b byte) (swig_result int) {
	var swig_r int
	swig_r = p.Color(r, g, b)
	return swig_r
}

type SwigcptrExample4 uintptr

func (p SwigcptrExample4) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrExample4) SwigIsExample4() {
}

func (p SwigcptrExample4) DirectorInterface() interface{} {
	return nil
}

var _wrap_new_Example4__SWIG_0 unsafe.Pointer

func _swig_wrap_new_Example4__SWIG_0() (base SwigcptrExample4) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_Example4__SWIG_0, _swig_p)
	return
}

func NewExample4__SWIG_0() (_swig_ret Example4) {
	return _swig_wrap_new_Example4__SWIG_0()
}

var _wrap_new_Example4__SWIG_1 unsafe.Pointer

func _swig_wrap_new_Example4__SWIG_1(base int, _ int) (_ SwigcptrExample4) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_Example4__SWIG_1, _swig_p)
	return
}

func NewExample4__SWIG_1(arg1 int, arg2 int) (_swig_ret Example4) {
	return _swig_wrap_new_Example4__SWIG_1(arg1, arg2)
}

func NewExample4(a ...interface{}) Example4 {
	argc := len(a)
	if argc == 0 {
		return NewExample4__SWIG_0()
	}
	if argc == 2 {
		return NewExample4__SWIG_1(a[0].(int), a[1].(int))
	}
	panic("No match for overloaded function call")
}

var _wrap_delete_Example4 unsafe.Pointer

func _swig_wrap_delete_Example4(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_Example4, _swig_p)
	return
}

func DeleteExample4(arg1 Example4) {
	_swig_wrap_delete_Example4(arg1.Swigcptr())
}

var _wrap_Example4_GetXSize unsafe.Pointer

func _swig_wrap_Example4_GetXSize(base SwigcptrExample4) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Example4_GetXSize, _swig_p)
	return
}

func (arg1 SwigcptrExample4) GetXSize() (_swig_ret int) {
	return _swig_wrap_Example4_GetXSize(arg1)
}

var _wrap_Example4_Color unsafe.Pointer

func _swig_wrap_Example4_Color(base SwigcptrExample4, _ byte, _ byte, _ byte) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Example4_Color, _swig_p)
	return
}

func (arg1 SwigcptrExample4) Color(arg2 byte, arg3 byte, arg4 byte) (_swig_ret int) {
	return _swig_wrap_Example4_Color(arg1, arg2, arg3, arg4)
}

var _wrap_Example4_get_color unsafe.Pointer

func _swig_wrap_Example4_get_color(base uintptr, _ byte, _ byte, _ byte) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Example4_get_color, _swig_p)
	return
}

func Example4Get_color(arg1 Example4, arg2 byte, arg3 byte, arg4 byte) (_swig_ret int) {
	return _swig_wrap_Example4_get_color(arg1.Swigcptr(), arg2, arg3, arg4)
}

type Example4 interface {
	Swigcptr() uintptr
	SwigIsExample4()
	DirectorInterface() interface{}
	GetXSize() (_swig_ret int)
	Color(arg2 byte, arg3 byte, arg4 byte) (_swig_ret int)
}

type _swig_DirectorExample3_i struct {
	SwigcptrExample3_i
	v interface{}
}

func (p *_swig_DirectorExample3_i) Swigcptr() uintptr {
	return p.SwigcptrExample3_i.Swigcptr()
}

func (p *_swig_DirectorExample3_i) SwigIsExample3_i() {
}

func (p *_swig_DirectorExample3_i) DirectorInterface() interface{} {
	return p.v
}

var _wrap__swig_NewDirectorExample3_iExample3_i__SWIG_0 unsafe.Pointer

func _swig_NewDirectorExample3_iExample3_i__SWIG_0(_swig_director *_swig_DirectorExample3_i) (_swig_ret SwigcptrExample3_i) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_director))
	_cgo_runtime_cgocall(_wrap__swig_NewDirectorExample3_iExample3_i__SWIG_0, _swig_p)
	return
}

func NewDirectorExample3_i__SWIG_0(v interface{}) Example3_i {
	p := &_swig_DirectorExample3_i{0, v}
	p.SwigcptrExample3_i = _swig_NewDirectorExample3_iExample3_i__SWIG_0(p)
	return p
}

var _wrap__swig_NewDirectorExample3_iExample3_i__SWIG_1 unsafe.Pointer

func _swig_NewDirectorExample3_iExample3_i__SWIG_1(_swig_director *_swig_DirectorExample3_i, _ int) (_swig_ret SwigcptrExample3_i) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_director))
	_cgo_runtime_cgocall(_wrap__swig_NewDirectorExample3_iExample3_i__SWIG_1, _swig_p)
	return
}

func NewDirectorExample3_i__SWIG_1(v interface{}, arg1 int) Example3_i {
	p := &_swig_DirectorExample3_i{0, v}
	p.SwigcptrExample3_i = _swig_NewDirectorExample3_iExample3_i__SWIG_1(p, arg1)
	return p
}

var _wrap__swig_NewDirectorExample3_iExample3_i__SWIG_2 unsafe.Pointer

func _swig_NewDirectorExample3_iExample3_i__SWIG_2(_swig_director *_swig_DirectorExample3_i, _ int, _ int) (_swig_ret SwigcptrExample3_i) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_director))
	_cgo_runtime_cgocall(_wrap__swig_NewDirectorExample3_iExample3_i__SWIG_2, _swig_p)
	return
}

func NewDirectorExample3_i__SWIG_2(v interface{}, arg1 int, arg2 int) Example3_i {
	p := &_swig_DirectorExample3_i{0, v}
	p.SwigcptrExample3_i = _swig_NewDirectorExample3_iExample3_i__SWIG_2(p, arg1, arg2)
	return p
}

func NewDirectorExample3_i(abi interface{}, a ...interface{}) Example3_i {
	argc := len(a)
	if argc == 0 {
		return NewDirectorExample3_i__SWIG_0(abi)
	}
	if argc == 1 {
		return NewDirectorExample3_i__SWIG_1(abi, a[0].(int))
	}
	if argc == 2 {
		return NewDirectorExample3_i__SWIG_2(abi, a[0].(int), a[1].(int))
	}
	panic("No match for overloaded function call")
}

var _wrap_DeleteDirectorExample3_i unsafe.Pointer

func _swig_wrap_DeleteDirectorExample3_i(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_DeleteDirectorExample3_i, _swig_p)
	return
}

func DeleteDirectorExample3_i(arg1 Example3_i) {
	_swig_wrap_DeleteDirectorExample3_i(arg1.Swigcptr())
}

func Swiggo_DeleteDirector_Example3_i(p *_swig_DirectorExample3_i) {
	p.SwigcptrExample3_i = 0
}

type _swig_DirectorInterfaceExample3_iColor interface {
	Color(byte, byte, byte) int
}

func (swig_p *_swig_DirectorExample3_i) Color(r byte, g byte, b byte) int {
	if swig_g, swig_ok := swig_p.v.(_swig_DirectorInterfaceExample3_iColor); swig_ok {
		return swig_g.Color(r, g, b)
	}
	panic("call to pure virtual method")
}

func Swig_DirectorExample3_i_callback_Color(p *_swig_DirectorExample3_i, r byte, g byte, b byte) (swig_result int) {
	var swig_r int
	swig_r = p.Color(r, g, b)
	return swig_r
}

type SwigcptrExample3_i uintptr

func (p SwigcptrExample3_i) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrExample3_i) SwigIsExample3_i() {
}

func (p SwigcptrExample3_i) DirectorInterface() interface{} {
	return nil
}

var _wrap_new_Example3_i__SWIG_0 unsafe.Pointer

func _swig_wrap_new_Example3_i__SWIG_0() (base SwigcptrExample3_i) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_Example3_i__SWIG_0, _swig_p)
	return
}

func NewExample3_i__SWIG_0() (_swig_ret Example3_i) {
	return _swig_wrap_new_Example3_i__SWIG_0()
}

var _wrap_new_Example3_i__SWIG_1 unsafe.Pointer

func _swig_wrap_new_Example3_i__SWIG_1(base int) (_ SwigcptrExample3_i) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_Example3_i__SWIG_1, _swig_p)
	return
}

func NewExample3_i__SWIG_1(arg1 int) (_swig_ret Example3_i) {
	return _swig_wrap_new_Example3_i__SWIG_1(arg1)
}

var _wrap_new_Example3_i__SWIG_2 unsafe.Pointer

func _swig_wrap_new_Example3_i__SWIG_2(base int, _ int) (_ SwigcptrExample3_i) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_Example3_i__SWIG_2, _swig_p)
	return
}

func NewExample3_i__SWIG_2(arg1 int, arg2 int) (_swig_ret Example3_i) {
	return _swig_wrap_new_Example3_i__SWIG_2(arg1, arg2)
}

func NewExample3_i(a ...interface{}) Example3_i {
	argc := len(a)
	if argc == 0 {
		return NewExample3_i__SWIG_0()
	}
	if argc == 1 {
		return NewExample3_i__SWIG_1(a[0].(int))
	}
	if argc == 2 {
		return NewExample3_i__SWIG_2(a[0].(int), a[1].(int))
	}
	panic("No match for overloaded function call")
}

var _wrap_delete_Example3_i unsafe.Pointer

func _swig_wrap_delete_Example3_i(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_Example3_i, _swig_p)
	return
}

func DeleteExample3_i(arg1 Example3_i) {
	_swig_wrap_delete_Example3_i(arg1.Swigcptr())
}

var _wrap_Example3_i_Color unsafe.Pointer

func _swig_wrap_Example3_i_Color(base SwigcptrExample3_i, _ byte, _ byte, _ byte) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Example3_i_Color, _swig_p)
	return
}

func (arg1 SwigcptrExample3_i) Color(arg2 byte, arg3 byte, arg4 byte) (_swig_ret int) {
	return _swig_wrap_Example3_i_Color(arg1, arg2, arg3, arg4)
}

var _wrap_Example3_i_get_color unsafe.Pointer

func _swig_wrap_Example3_i_get_color(base uintptr, _ byte, _ byte, _ byte) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Example3_i_get_color, _swig_p)
	return
}

func Example3_iGet_color(arg1 Example3_i, arg2 byte, arg3 byte, arg4 byte) (_swig_ret int) {
	return _swig_wrap_Example3_i_get_color(arg1.Swigcptr(), arg2, arg3, arg4)
}

type Example3_i interface {
	Swigcptr() uintptr
	SwigIsExample3_i()
	DirectorInterface() interface{}
	Color(arg2 byte, arg3 byte, arg4 byte) (_swig_ret int)
}

type _swig_DirectorA struct {
	SwigcptrA
	v interface{}
}

func (p *_swig_DirectorA) Swigcptr() uintptr {
	return p.SwigcptrA.Swigcptr()
}

func (p *_swig_DirectorA) SwigIsA() {
}

func (p *_swig_DirectorA) DirectorInterface() interface{} {
	return p.v
}

var _wrap__swig_NewDirectorAA unsafe.Pointer

func _swig_NewDirectorAA(_swig_director *_swig_DirectorA, _ A) (_swig_ret SwigcptrA) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_director))
	_cgo_runtime_cgocall(_wrap__swig_NewDirectorAA, _swig_p)
	return
}

func NewDirectorA(v interface{}, arg1 A) A {
	p := &_swig_DirectorA{0, v}
	p.SwigcptrA = _swig_NewDirectorAA(p, arg1)
	return p
}

var _wrap_DeleteDirectorA unsafe.Pointer

func _swig_wrap_DeleteDirectorA(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_DeleteDirectorA, _swig_p)
	return
}

func DeleteDirectorA(arg1 A) {
	_swig_wrap_DeleteDirectorA(arg1.Swigcptr())
}

func Swiggo_DeleteDirector_A(p *_swig_DirectorA) {
	p.SwigcptrA = 0
}

type _swig_DirectorInterfaceAF interface {
	F() int
}

func (swig_p *_swig_DirectorA) F() int {
	if swig_g, swig_ok := swig_p.v.(_swig_DirectorInterfaceAF); swig_ok {
		return swig_g.F()
	}
	panic("call to pure virtual method")
}

func Swig_DirectorA_callback_f(p *_swig_DirectorA) (swig_result int) {
	var swig_r int
	swig_r = p.F()
	return swig_r
}

type SwigcptrA uintptr

func (p SwigcptrA) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrA) SwigIsA() {
}

func (p SwigcptrA) DirectorInterface() interface{} {
	return nil
}

var _wrap_delete_A unsafe.Pointer

func _swig_wrap_delete_A(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_A, _swig_p)
	return
}

func DeleteA(arg1 A) {
	_swig_wrap_delete_A(arg1.Swigcptr())
}

var _wrap_g unsafe.Pointer

func _swig_wrap_g(base uintptr) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_g, _swig_p)
	return
}

func G(arg1 A) (_swig_ret int) {
	return _swig_wrap_g(arg1.Swigcptr())
}

var _wrap_new_A unsafe.Pointer

func _swig_wrap_new_A(base uintptr) (_ SwigcptrA) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_A, _swig_p)
	return
}

func NewA(arg1 A) (_swig_ret A) {
	return _swig_wrap_new_A(arg1.Swigcptr())
}

type A interface {
	Swigcptr() uintptr
	SwigIsA()
	DirectorInterface() interface{}
}


type SwigcptrSwigDirector_Example0 uintptr
type SwigDirector_Example0 interface {
	Swigcptr() uintptr;
}
func (p SwigcptrSwigDirector_Example0) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrSwigDirector_Foo uintptr
type SwigDirector_Foo interface {
	Swigcptr() uintptr;
}
func (p SwigcptrSwigDirector_Foo) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrVoid uintptr
type Void interface {
	Swigcptr() uintptr;
}
func (p SwigcptrVoid) Swigcptr() uintptr {
	return uintptr(p)
}

