/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: ./../director_binary_string.i

package director_binary_string

import "unsafe"
import _ "runtime/cgo"

var _cgo_runtime_cgocall func(unsafe.Pointer, uintptr)



type _ unsafe.Pointer



type _swig_fnptr *byte
type _swig_memberptr *byte

const BUFFER_SIZE_AA int = 8
const BUFFER_SIZE_BB int = 5
type _swig_DirectorCallback struct {
	SwigcptrCallback
	v interface{}
}

func (p *_swig_DirectorCallback) Swigcptr() uintptr {
	return p.SwigcptrCallback.Swigcptr()
}

func (p *_swig_DirectorCallback) SwigIsCallback() {
}

func (p *_swig_DirectorCallback) DirectorInterface() interface{} {
	return p.v
}

var _wrap__swig_NewDirectorCallbackCallback unsafe.Pointer

func _swig_NewDirectorCallbackCallback(_swig_director *_swig_DirectorCallback) (_swig_ret SwigcptrCallback) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_director))
	_cgo_runtime_cgocall(_wrap__swig_NewDirectorCallbackCallback, _swig_p)
	return
}

func NewDirectorCallback(v interface{}) Callback {
	p := &_swig_DirectorCallback{0, v}
	p.SwigcptrCallback = _swig_NewDirectorCallbackCallback(p)
	return p
}

var _wrap_DeleteDirectorCallback unsafe.Pointer

func _swig_wrap_DeleteDirectorCallback(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_DeleteDirectorCallback, _swig_p)
	return
}

func DeleteDirectorCallback(arg1 Callback) {
	_swig_wrap_DeleteDirectorCallback(arg1.Swigcptr())
}

func Swiggo_DeleteDirector_Callback(p *_swig_DirectorCallback) {
	p.SwigcptrCallback = 0
}

type _swig_DirectorInterfaceCallbackRun interface {
	Run(string, string)
}

var _wrap__swig_DirectorCallback_upcall_Run unsafe.Pointer

func _swig_wrap__swig_DirectorCallback_upcall_Run(_swig_ptr SwigcptrCallback, _ string, _ string) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ptr))
	_cgo_runtime_cgocall(_wrap__swig_DirectorCallback_upcall_Run, _swig_p)
	return
}

func (swig_p *_swig_DirectorCallback) Run(dataBufferAA string, dataBufferBB string) {
	if swig_g, swig_ok := swig_p.v.(_swig_DirectorInterfaceCallbackRun); swig_ok {
		swig_g.Run(dataBufferAA, dataBufferBB)
		return
	}
	_swig_wrap__swig_DirectorCallback_upcall_Run(swig_p.SwigcptrCallback, dataBufferAA, dataBufferBB)
}

func DirectorCallbackRun(p Callback, arg2 string, arg4 string) {
	_swig_wrap__swig_DirectorCallback_upcall_Run(p.(*_swig_DirectorCallback).SwigcptrCallback, arg2, arg4)
}

func Swig_DirectorCallback_callback_run(p *_swig_DirectorCallback, arg2 string, arg4 string) {
	p.Run(arg2, arg4)
}

type SwigcptrCallback uintptr

func (p SwigcptrCallback) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrCallback) SwigIsCallback() {
}

func (p SwigcptrCallback) DirectorInterface() interface{} {
	return nil
}

var _wrap_delete_Callback unsafe.Pointer

func _swig_wrap_delete_Callback(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_Callback, _swig_p)
	return
}

func DeleteCallback(arg1 Callback) {
	_swig_wrap_delete_Callback(arg1.Swigcptr())
}

var _wrap_Callback_run unsafe.Pointer

func _swig_wrap_Callback_run(base SwigcptrCallback, _ string, _ string) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Callback_run, _swig_p)
	return
}

func (arg1 SwigcptrCallback) Run(arg2 string, arg3 string) {
	_swig_wrap_Callback_run(arg1, arg2, arg3)
}

var _wrap_new_Callback unsafe.Pointer

func _swig_wrap_new_Callback() (base SwigcptrCallback) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_Callback, _swig_p)
	return
}

func NewCallback() (_swig_ret Callback) {
	return _swig_wrap_new_Callback()
}

type Callback interface {
	Swigcptr() uintptr
	SwigIsCallback()
	DirectorInterface() interface{}
	Run(arg2 string, arg3 string)
}

type SwigcptrCaller uintptr

func (p SwigcptrCaller) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrCaller) SwigIsCaller() {
}

var _wrap_new_Caller unsafe.Pointer

func _swig_wrap_new_Caller() (base SwigcptrCaller) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_Caller, _swig_p)
	return
}

func NewCaller() (_swig_ret Caller) {
	return _swig_wrap_new_Caller()
}

var _wrap_delete_Caller unsafe.Pointer

func _swig_wrap_delete_Caller(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_Caller, _swig_p)
	return
}

func DeleteCaller(arg1 Caller) {
	_swig_wrap_delete_Caller(arg1.Swigcptr())
}

var _wrap_Caller_delCallback unsafe.Pointer

func _swig_wrap_Caller_delCallback(base SwigcptrCaller) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Caller_delCallback, _swig_p)
	return
}

func (arg1 SwigcptrCaller) DelCallback() {
	_swig_wrap_Caller_delCallback(arg1)
}

var _wrap_Caller_setCallback unsafe.Pointer

func _swig_wrap_Caller_setCallback(base SwigcptrCaller, _ uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Caller_setCallback, _swig_p)
	return
}

func (arg1 SwigcptrCaller) SetCallback(arg2 Callback) {
	_swig_wrap_Caller_setCallback(arg1, arg2.Swigcptr())
}

var _wrap_Caller_call unsafe.Pointer

func _swig_wrap_Caller_call(base SwigcptrCaller) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Caller_call, _swig_p)
	return
}

func (arg1 SwigcptrCaller) Call() (_swig_ret int) {
	return _swig_wrap_Caller_call(arg1)
}

var _wrap_Caller_call_null unsafe.Pointer

func _swig_wrap_Caller_call_null(base SwigcptrCaller) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Caller_call_null, _swig_p)
	return
}

func (arg1 SwigcptrCaller) Call_null() {
	_swig_wrap_Caller_call_null(arg1)
}

type Caller interface {
	Swigcptr() uintptr
	SwigIsCaller()
	DelCallback()
	SetCallback(arg2 Callback)
	Call() (_swig_ret int)
	Call_null()
}


type SwigcptrSwigDirector_Callback uintptr
type SwigDirector_Callback interface {
	Swigcptr() uintptr;
}
func (p SwigcptrSwigDirector_Callback) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrVoid uintptr
type Void interface {
	Swigcptr() uintptr;
}
func (p SwigcptrVoid) Swigcptr() uintptr {
	return uintptr(p)
}

