/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: ./../director_overload2.i

package director_overload2

import "unsafe"
import _ "runtime/cgo"

var _cgo_runtime_cgocall func(unsafe.Pointer, uintptr)



type _ unsafe.Pointer



type _swig_fnptr *byte
type _swig_memberptr *byte

type _swig_DirectorOverloadBase struct {
	SwigcptrOverloadBase
	v interface{}
}

func (p *_swig_DirectorOverloadBase) Swigcptr() uintptr {
	return p.SwigcptrOverloadBase.Swigcptr()
}

func (p *_swig_DirectorOverloadBase) SwigIsOverloadBase() {
}

func (p *_swig_DirectorOverloadBase) DirectorInterface() interface{} {
	return p.v
}

var _wrap__swig_NewDirectorOverloadBaseOverloadBase unsafe.Pointer

func _swig_NewDirectorOverloadBaseOverloadBase(_swig_director *_swig_DirectorOverloadBase) (_swig_ret SwigcptrOverloadBase) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_director))
	_cgo_runtime_cgocall(_wrap__swig_NewDirectorOverloadBaseOverloadBase, _swig_p)
	return
}

func NewDirectorOverloadBase(v interface{}) OverloadBase {
	p := &_swig_DirectorOverloadBase{0, v}
	p.SwigcptrOverloadBase = _swig_NewDirectorOverloadBaseOverloadBase(p)
	return p
}

var _wrap_DeleteDirectorOverloadBase unsafe.Pointer

func _swig_wrap_DeleteDirectorOverloadBase(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_DeleteDirectorOverloadBase, _swig_p)
	return
}

func DeleteDirectorOverloadBase(arg1 OverloadBase) {
	_swig_wrap_DeleteDirectorOverloadBase(arg1.Swigcptr())
}

func Swiggo_DeleteDirector_OverloadBase(p *_swig_DirectorOverloadBase) {
	p.SwigcptrOverloadBase = 0
}

type _swig_DirectorInterfaceOverloadBaseMmm interface {
	Mmm()
}

var _wrap__swig_DirectorOverloadBase_upcall_Mmm unsafe.Pointer

func _swig_wrap__swig_DirectorOverloadBase_upcall_Mmm(_swig_ptr SwigcptrOverloadBase) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ptr))
	_cgo_runtime_cgocall(_wrap__swig_DirectorOverloadBase_upcall_Mmm, _swig_p)
	return
}

func (swig_p *_swig_DirectorOverloadBase) Mmm() {
	if swig_g, swig_ok := swig_p.v.(_swig_DirectorInterfaceOverloadBaseMmm); swig_ok {
		swig_g.Mmm()
		return
	}
	_swig_wrap__swig_DirectorOverloadBase_upcall_Mmm(swig_p.SwigcptrOverloadBase)
}

func DirectorOverloadBaseMmm(p OverloadBase) {
	_swig_wrap__swig_DirectorOverloadBase_upcall_Mmm(p.(*_swig_DirectorOverloadBase).SwigcptrOverloadBase)
}

func Swig_DirectorOverloadBase_callback_mmm(p *_swig_DirectorOverloadBase) {
	p.Mmm()
}

type _swig_DirectorInterfaceOverloadBaseNnn__SWIG_0 interface {
	Nnn__SWIG_0(int)
}

var _wrap__swig_DirectorOverloadBase_upcall_Nnn__SWIG_0 unsafe.Pointer

func _swig_wrap__swig_DirectorOverloadBase_upcall_Nnn__SWIG_0(_swig_ptr SwigcptrOverloadBase, _ int) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ptr))
	_cgo_runtime_cgocall(_wrap__swig_DirectorOverloadBase_upcall_Nnn__SWIG_0, _swig_p)
	return
}

func (swig_p *_swig_DirectorOverloadBase) Nnn__SWIG_0(vvv int) {
	if swig_g, swig_ok := swig_p.v.(_swig_DirectorInterfaceOverloadBaseNnn__SWIG_0); swig_ok {
		swig_g.Nnn__SWIG_0(vvv)
		return
	}
	_swig_wrap__swig_DirectorOverloadBase_upcall_Nnn__SWIG_0(swig_p.SwigcptrOverloadBase, vvv)
}

func DirectorOverloadBaseNnn__SWIG_0(p OverloadBase, arg2 int) {
	_swig_wrap__swig_DirectorOverloadBase_upcall_Nnn__SWIG_0(p.(*_swig_DirectorOverloadBase).SwigcptrOverloadBase, arg2)
}

func Swig_DirectorOverloadBase_callback_nnn__SWIG_0(p *_swig_DirectorOverloadBase, arg2 int) {
	p.Nnn__SWIG_0(arg2)
}

type _swig_DirectorInterfaceOverloadBaseNnn__SWIG_1 interface {
	Nnn__SWIG_1()
}

var _wrap__swig_DirectorOverloadBase_upcall_Nnn__SWIG_1 unsafe.Pointer

func _swig_wrap__swig_DirectorOverloadBase_upcall_Nnn__SWIG_1(_swig_ptr SwigcptrOverloadBase) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ptr))
	_cgo_runtime_cgocall(_wrap__swig_DirectorOverloadBase_upcall_Nnn__SWIG_1, _swig_p)
	return
}

func (swig_p *_swig_DirectorOverloadBase) Nnn__SWIG_1() {
	if swig_g, swig_ok := swig_p.v.(_swig_DirectorInterfaceOverloadBaseNnn__SWIG_1); swig_ok {
		swig_g.Nnn__SWIG_1()
		return
	}
	_swig_wrap__swig_DirectorOverloadBase_upcall_Nnn__SWIG_1(swig_p.SwigcptrOverloadBase)
}

func DirectorOverloadBaseNnn__SWIG_1(p OverloadBase) {
	_swig_wrap__swig_DirectorOverloadBase_upcall_Nnn__SWIG_1(p.(*_swig_DirectorOverloadBase).SwigcptrOverloadBase)
}

func Swig_DirectorOverloadBase_callback_nnn__SWIG_1(p *_swig_DirectorOverloadBase) {
	p.Nnn__SWIG_1()
}

func (p _swig_DirectorOverloadBase) Nnn(a ...interface{}) {
	argc := len(a)
	if argc == 0 {
		p.Nnn__SWIG_1()
		return
	}
	if argc == 1 {
		p.Nnn__SWIG_0(a[0].(int))
		return
	}
	panic("No match for overloaded function call")
}

func DirectorOverloadBaseNnn(p *_swig_DirectorOverloadBase, a ...interface{}) {
	argc := len(a)
	if argc == 0 {
		DirectorOverloadBaseNnn__SWIG_1(p)
		return
	}
	if argc == 1 {
		DirectorOverloadBaseNnn__SWIG_0(p, a[0].(int))
		return
	}
	panic("No match for overloaded function call")
}

type SwigcptrOverloadBase uintptr

func (p SwigcptrOverloadBase) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrOverloadBase) SwigIsOverloadBase() {
}

func (p SwigcptrOverloadBase) DirectorInterface() interface{} {
	return nil
}

var _wrap_delete_OverloadBase unsafe.Pointer

func _swig_wrap_delete_OverloadBase(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_OverloadBase, _swig_p)
	return
}

func DeleteOverloadBase(arg1 OverloadBase) {
	_swig_wrap_delete_OverloadBase(arg1.Swigcptr())
}

var _wrap_OverloadBase_mmm unsafe.Pointer

func _swig_wrap_OverloadBase_mmm(base SwigcptrOverloadBase) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_OverloadBase_mmm, _swig_p)
	return
}

func (arg1 SwigcptrOverloadBase) Mmm() {
	_swig_wrap_OverloadBase_mmm(arg1)
}

var _wrap_OverloadBase_nnn__SWIG_0 unsafe.Pointer

func _swig_wrap_OverloadBase_nnn__SWIG_0(base SwigcptrOverloadBase, _ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_OverloadBase_nnn__SWIG_0, _swig_p)
	return
}

func (arg1 SwigcptrOverloadBase) Nnn__SWIG_0(arg2 int) {
	_swig_wrap_OverloadBase_nnn__SWIG_0(arg1, arg2)
}

var _wrap_OverloadBase_nnn__SWIG_1 unsafe.Pointer

func _swig_wrap_OverloadBase_nnn__SWIG_1(base SwigcptrOverloadBase) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_OverloadBase_nnn__SWIG_1, _swig_p)
	return
}

func (arg1 SwigcptrOverloadBase) Nnn__SWIG_1() {
	_swig_wrap_OverloadBase_nnn__SWIG_1(arg1)
}

func (p SwigcptrOverloadBase) Nnn(a ...interface{}) {
	argc := len(a)
	if argc == 0 {
		p.Nnn__SWIG_1()
		return
	}
	if argc == 1 {
		p.Nnn__SWIG_0(a[0].(int))
		return
	}
	panic("No match for overloaded function call")
}

var _wrap_new_OverloadBase unsafe.Pointer

func _swig_wrap_new_OverloadBase() (base SwigcptrOverloadBase) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_OverloadBase, _swig_p)
	return
}

func NewOverloadBase() (_swig_ret OverloadBase) {
	return _swig_wrap_new_OverloadBase()
}

type OverloadBase interface {
	Swigcptr() uintptr
	SwigIsOverloadBase()
	DirectorInterface() interface{}
	Mmm()
	Nnn(a ...interface{})
}

type _swig_DirectorOverloadDerived1 struct {
	SwigcptrOverloadDerived1
	v interface{}
}

func (p *_swig_DirectorOverloadDerived1) Swigcptr() uintptr {
	return p.SwigcptrOverloadDerived1.Swigcptr()
}

func (p *_swig_DirectorOverloadDerived1) SwigIsOverloadDerived1() {
}

func (p *_swig_DirectorOverloadDerived1) DirectorInterface() interface{} {
	return p.v
}

var _wrap__swig_NewDirectorOverloadDerived1OverloadDerived1 unsafe.Pointer

func _swig_NewDirectorOverloadDerived1OverloadDerived1(_swig_director *_swig_DirectorOverloadDerived1) (_swig_ret SwigcptrOverloadDerived1) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_director))
	_cgo_runtime_cgocall(_wrap__swig_NewDirectorOverloadDerived1OverloadDerived1, _swig_p)
	return
}

func NewDirectorOverloadDerived1(v interface{}) OverloadDerived1 {
	p := &_swig_DirectorOverloadDerived1{0, v}
	p.SwigcptrOverloadDerived1 = _swig_NewDirectorOverloadDerived1OverloadDerived1(p)
	return p
}

var _wrap_DeleteDirectorOverloadDerived1 unsafe.Pointer

func _swig_wrap_DeleteDirectorOverloadDerived1(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_DeleteDirectorOverloadDerived1, _swig_p)
	return
}

func DeleteDirectorOverloadDerived1(arg1 OverloadDerived1) {
	_swig_wrap_DeleteDirectorOverloadDerived1(arg1.Swigcptr())
}

func Swiggo_DeleteDirector_OverloadDerived1(p *_swig_DirectorOverloadDerived1) {
	p.SwigcptrOverloadDerived1 = 0
}

type _swig_DirectorInterfaceOverloadDerived1Mmm interface {
	Mmm()
}

var _wrap__swig_DirectorOverloadDerived1_upcall_Mmm unsafe.Pointer

func _swig_wrap__swig_DirectorOverloadDerived1_upcall_Mmm(_swig_ptr SwigcptrOverloadDerived1) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ptr))
	_cgo_runtime_cgocall(_wrap__swig_DirectorOverloadDerived1_upcall_Mmm, _swig_p)
	return
}

func (swig_p *_swig_DirectorOverloadDerived1) Mmm() {
	if swig_g, swig_ok := swig_p.v.(_swig_DirectorInterfaceOverloadDerived1Mmm); swig_ok {
		swig_g.Mmm()
		return
	}
	_swig_wrap__swig_DirectorOverloadDerived1_upcall_Mmm(swig_p.SwigcptrOverloadDerived1)
}

func DirectorOverloadDerived1Mmm(p OverloadDerived1) {
	_swig_wrap__swig_DirectorOverloadDerived1_upcall_Mmm(p.(*_swig_DirectorOverloadDerived1).SwigcptrOverloadDerived1)
}

func Swig_DirectorOverloadDerived1_callback_mmm(p *_swig_DirectorOverloadDerived1) {
	p.Mmm()
}

type _swig_DirectorInterfaceOverloadDerived1Nnn interface {
	Nnn(int)
}

var _wrap__swig_DirectorOverloadDerived1_upcall_Nnn unsafe.Pointer

func _swig_wrap__swig_DirectorOverloadDerived1_upcall_Nnn(_swig_ptr SwigcptrOverloadDerived1, _ int) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ptr))
	_cgo_runtime_cgocall(_wrap__swig_DirectorOverloadDerived1_upcall_Nnn, _swig_p)
	return
}

func (swig_p *_swig_DirectorOverloadDerived1) Nnn(vvv int) {
	if swig_g, swig_ok := swig_p.v.(_swig_DirectorInterfaceOverloadDerived1Nnn); swig_ok {
		swig_g.Nnn(vvv)
		return
	}
	_swig_wrap__swig_DirectorOverloadDerived1_upcall_Nnn(swig_p.SwigcptrOverloadDerived1, vvv)
}

func DirectorOverloadDerived1Nnn(p OverloadDerived1, arg2 int) {
	_swig_wrap__swig_DirectorOverloadDerived1_upcall_Nnn(p.(*_swig_DirectorOverloadDerived1).SwigcptrOverloadDerived1, arg2)
}

func Swig_DirectorOverloadDerived1_callback_nnn(p *_swig_DirectorOverloadDerived1, arg2 int) {
	p.Nnn(arg2)
}

type _swig_DirectorInterfaceOverloadDerived1Nnn__SWIG_1 interface {
	Nnn__SWIG_1()
}

var _wrap__swig_DirectorOverloadDerived1_upcall_Nnn__SWIG_1 unsafe.Pointer

func _swig_wrap__swig_DirectorOverloadDerived1_upcall_Nnn__SWIG_1(_swig_ptr SwigcptrOverloadDerived1) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ptr))
	_cgo_runtime_cgocall(_wrap__swig_DirectorOverloadDerived1_upcall_Nnn__SWIG_1, _swig_p)
	return
}

func (swig_p *_swig_DirectorOverloadDerived1) Nnn__SWIG_1() {
	if swig_g, swig_ok := swig_p.v.(_swig_DirectorInterfaceOverloadDerived1Nnn__SWIG_1); swig_ok {
		swig_g.Nnn__SWIG_1()
		return
	}
	_swig_wrap__swig_DirectorOverloadDerived1_upcall_Nnn__SWIG_1(swig_p.SwigcptrOverloadDerived1)
}

func DirectorOverloadDerived1Nnn__SWIG_1(p OverloadDerived1) {
	_swig_wrap__swig_DirectorOverloadDerived1_upcall_Nnn__SWIG_1(p.(*_swig_DirectorOverloadDerived1).SwigcptrOverloadDerived1)
}

func Swig_DirectorOverloadDerived1_callback_nnn__SWIG_1(p *_swig_DirectorOverloadDerived1) {
	p.Nnn__SWIG_1()
}

type SwigcptrOverloadDerived1 uintptr

func (p SwigcptrOverloadDerived1) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrOverloadDerived1) SwigIsOverloadDerived1() {
}

func (p SwigcptrOverloadDerived1) DirectorInterface() interface{} {
	return nil
}

var _wrap_OverloadDerived1_nnn unsafe.Pointer

func _swig_wrap_OverloadDerived1_nnn(base SwigcptrOverloadDerived1, _ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_OverloadDerived1_nnn, _swig_p)
	return
}

func (arg1 SwigcptrOverloadDerived1) Nnn(arg2 int) {
	_swig_wrap_OverloadDerived1_nnn(arg1, arg2)
}

var _wrap_new_OverloadDerived1 unsafe.Pointer

func _swig_wrap_new_OverloadDerived1() (base SwigcptrOverloadDerived1) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_OverloadDerived1, _swig_p)
	return
}

func NewOverloadDerived1() (_swig_ret OverloadDerived1) {
	return _swig_wrap_new_OverloadDerived1()
}

var _wrap_delete_OverloadDerived1 unsafe.Pointer

func _swig_wrap_delete_OverloadDerived1(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_OverloadDerived1, _swig_p)
	return
}

func DeleteOverloadDerived1(arg1 OverloadDerived1) {
	_swig_wrap_delete_OverloadDerived1(arg1.Swigcptr())
}

var _wrap_OverloadDerived1_mmm unsafe.Pointer

func _swig_wrap_OverloadDerived1_mmm(base SwigcptrOverloadDerived1) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_OverloadDerived1_mmm, _swig_p)
	return
}

func (_swig_base SwigcptrOverloadDerived1) Mmm() {
	_swig_wrap_OverloadDerived1_mmm(_swig_base)
}

func (p SwigcptrOverloadDerived1) SwigIsOverloadBase() {
}

func (p SwigcptrOverloadDerived1) SwigGetOverloadBase() OverloadBase {
	return SwigcptrOverloadBase(p.Swigcptr())
}

type OverloadDerived1 interface {
	Swigcptr() uintptr
	SwigIsOverloadDerived1()
	DirectorInterface() interface{}
	Nnn(arg2 int)
	Mmm()
	SwigIsOverloadBase()
	SwigGetOverloadBase() OverloadBase
}

type _swig_DirectorOverloadDerived2 struct {
	SwigcptrOverloadDerived2
	v interface{}
}

func (p *_swig_DirectorOverloadDerived2) Swigcptr() uintptr {
	return p.SwigcptrOverloadDerived2.Swigcptr()
}

func (p *_swig_DirectorOverloadDerived2) SwigIsOverloadDerived2() {
}

func (p *_swig_DirectorOverloadDerived2) DirectorInterface() interface{} {
	return p.v
}

var _wrap__swig_NewDirectorOverloadDerived2OverloadDerived2 unsafe.Pointer

func _swig_NewDirectorOverloadDerived2OverloadDerived2(_swig_director *_swig_DirectorOverloadDerived2) (_swig_ret SwigcptrOverloadDerived2) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_director))
	_cgo_runtime_cgocall(_wrap__swig_NewDirectorOverloadDerived2OverloadDerived2, _swig_p)
	return
}

func NewDirectorOverloadDerived2(v interface{}) OverloadDerived2 {
	p := &_swig_DirectorOverloadDerived2{0, v}
	p.SwigcptrOverloadDerived2 = _swig_NewDirectorOverloadDerived2OverloadDerived2(p)
	return p
}

var _wrap_DeleteDirectorOverloadDerived2 unsafe.Pointer

func _swig_wrap_DeleteDirectorOverloadDerived2(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_DeleteDirectorOverloadDerived2, _swig_p)
	return
}

func DeleteDirectorOverloadDerived2(arg1 OverloadDerived2) {
	_swig_wrap_DeleteDirectorOverloadDerived2(arg1.Swigcptr())
}

func Swiggo_DeleteDirector_OverloadDerived2(p *_swig_DirectorOverloadDerived2) {
	p.SwigcptrOverloadDerived2 = 0
}

type _swig_DirectorInterfaceOverloadDerived2Mmm interface {
	Mmm()
}

var _wrap__swig_DirectorOverloadDerived2_upcall_Mmm unsafe.Pointer

func _swig_wrap__swig_DirectorOverloadDerived2_upcall_Mmm(_swig_ptr SwigcptrOverloadDerived2) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ptr))
	_cgo_runtime_cgocall(_wrap__swig_DirectorOverloadDerived2_upcall_Mmm, _swig_p)
	return
}

func (swig_p *_swig_DirectorOverloadDerived2) Mmm() {
	if swig_g, swig_ok := swig_p.v.(_swig_DirectorInterfaceOverloadDerived2Mmm); swig_ok {
		swig_g.Mmm()
		return
	}
	_swig_wrap__swig_DirectorOverloadDerived2_upcall_Mmm(swig_p.SwigcptrOverloadDerived2)
}

func DirectorOverloadDerived2Mmm(p OverloadDerived2) {
	_swig_wrap__swig_DirectorOverloadDerived2_upcall_Mmm(p.(*_swig_DirectorOverloadDerived2).SwigcptrOverloadDerived2)
}

func Swig_DirectorOverloadDerived2_callback_mmm(p *_swig_DirectorOverloadDerived2) {
	p.Mmm()
}

type _swig_DirectorInterfaceOverloadDerived2Nnn__SWIG_0 interface {
	Nnn__SWIG_0(int)
}

var _wrap__swig_DirectorOverloadDerived2_upcall_Nnn__SWIG_0 unsafe.Pointer

func _swig_wrap__swig_DirectorOverloadDerived2_upcall_Nnn__SWIG_0(_swig_ptr SwigcptrOverloadDerived2, _ int) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ptr))
	_cgo_runtime_cgocall(_wrap__swig_DirectorOverloadDerived2_upcall_Nnn__SWIG_0, _swig_p)
	return
}

func (swig_p *_swig_DirectorOverloadDerived2) Nnn__SWIG_0(vvv int) {
	if swig_g, swig_ok := swig_p.v.(_swig_DirectorInterfaceOverloadDerived2Nnn__SWIG_0); swig_ok {
		swig_g.Nnn__SWIG_0(vvv)
		return
	}
	_swig_wrap__swig_DirectorOverloadDerived2_upcall_Nnn__SWIG_0(swig_p.SwigcptrOverloadDerived2, vvv)
}

func DirectorOverloadDerived2Nnn__SWIG_0(p OverloadDerived2, arg2 int) {
	_swig_wrap__swig_DirectorOverloadDerived2_upcall_Nnn__SWIG_0(p.(*_swig_DirectorOverloadDerived2).SwigcptrOverloadDerived2, arg2)
}

func Swig_DirectorOverloadDerived2_callback_nnn__SWIG_0(p *_swig_DirectorOverloadDerived2, arg2 int) {
	p.Nnn__SWIG_0(arg2)
}

type _swig_DirectorInterfaceOverloadDerived2Nnn interface {
	Nnn()
}

var _wrap__swig_DirectorOverloadDerived2_upcall_Nnn unsafe.Pointer

func _swig_wrap__swig_DirectorOverloadDerived2_upcall_Nnn(_swig_ptr SwigcptrOverloadDerived2) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ptr))
	_cgo_runtime_cgocall(_wrap__swig_DirectorOverloadDerived2_upcall_Nnn, _swig_p)
	return
}

func (swig_p *_swig_DirectorOverloadDerived2) Nnn() {
	if swig_g, swig_ok := swig_p.v.(_swig_DirectorInterfaceOverloadDerived2Nnn); swig_ok {
		swig_g.Nnn()
		return
	}
	_swig_wrap__swig_DirectorOverloadDerived2_upcall_Nnn(swig_p.SwigcptrOverloadDerived2)
}

func DirectorOverloadDerived2Nnn(p OverloadDerived2) {
	_swig_wrap__swig_DirectorOverloadDerived2_upcall_Nnn(p.(*_swig_DirectorOverloadDerived2).SwigcptrOverloadDerived2)
}

func Swig_DirectorOverloadDerived2_callback_nnn(p *_swig_DirectorOverloadDerived2) {
	p.Nnn()
}

type SwigcptrOverloadDerived2 uintptr

func (p SwigcptrOverloadDerived2) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrOverloadDerived2) SwigIsOverloadDerived2() {
}

func (p SwigcptrOverloadDerived2) DirectorInterface() interface{} {
	return nil
}

var _wrap_OverloadDerived2_nnn unsafe.Pointer

func _swig_wrap_OverloadDerived2_nnn(base SwigcptrOverloadDerived2) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_OverloadDerived2_nnn, _swig_p)
	return
}

func (arg1 SwigcptrOverloadDerived2) Nnn() {
	_swig_wrap_OverloadDerived2_nnn(arg1)
}

var _wrap_new_OverloadDerived2 unsafe.Pointer

func _swig_wrap_new_OverloadDerived2() (base SwigcptrOverloadDerived2) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_OverloadDerived2, _swig_p)
	return
}

func NewOverloadDerived2() (_swig_ret OverloadDerived2) {
	return _swig_wrap_new_OverloadDerived2()
}

var _wrap_delete_OverloadDerived2 unsafe.Pointer

func _swig_wrap_delete_OverloadDerived2(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_OverloadDerived2, _swig_p)
	return
}

func DeleteOverloadDerived2(arg1 OverloadDerived2) {
	_swig_wrap_delete_OverloadDerived2(arg1.Swigcptr())
}

var _wrap_OverloadDerived2_mmm unsafe.Pointer

func _swig_wrap_OverloadDerived2_mmm(base SwigcptrOverloadDerived2) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_OverloadDerived2_mmm, _swig_p)
	return
}

func (_swig_base SwigcptrOverloadDerived2) Mmm() {
	_swig_wrap_OverloadDerived2_mmm(_swig_base)
}

func (p SwigcptrOverloadDerived2) SwigIsOverloadBase() {
}

func (p SwigcptrOverloadDerived2) SwigGetOverloadBase() OverloadBase {
	return SwigcptrOverloadBase(p.Swigcptr())
}

type OverloadDerived2 interface {
	Swigcptr() uintptr
	SwigIsOverloadDerived2()
	DirectorInterface() interface{}
	Nnn()
	Mmm()
	SwigIsOverloadBase()
	SwigGetOverloadBase() OverloadBase
}


type SwigcptrSwigDirector_OverloadDerived1 uintptr
type SwigDirector_OverloadDerived1 interface {
	Swigcptr() uintptr;
}
func (p SwigcptrSwigDirector_OverloadDerived1) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrSwigDirector_OverloadDerived2 uintptr
type SwigDirector_OverloadDerived2 interface {
	Swigcptr() uintptr;
}
func (p SwigcptrSwigDirector_OverloadDerived2) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrSwigDirector_OverloadBase uintptr
type SwigDirector_OverloadBase interface {
	Swigcptr() uintptr;
}
func (p SwigcptrSwigDirector_OverloadBase) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrVoid uintptr
type Void interface {
	Swigcptr() uintptr;
}
func (p SwigcptrVoid) Swigcptr() uintptr {
	return uintptr(p)
}

