/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: ./../enum_var.i

package enum_var

import "unsafe"
import _ "runtime/cgo"

var _cgo_runtime_cgocall func(unsafe.Pointer, uintptr)



type _ unsafe.Pointer



type _swig_fnptr *byte
type _swig_memberptr *byte

type Fruit int
var _wrap_APPLE unsafe.Pointer

func _swig_getAPPLE() (_swig_ret Fruit) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_APPLE, _swig_p)
	return
}
var APPLE Fruit = _swig_getAPPLE()
var _wrap_PEAR unsafe.Pointer

func _swig_getPEAR() (_swig_ret Fruit) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_PEAR, _swig_p)
	return
}
var PEAR Fruit = _swig_getPEAR()
var _wrap_test_set unsafe.Pointer

func _swig_wrap_test_set(base Fruit) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_test_set, _swig_p)
	return
}

func SetTest(arg1 Fruit) {
	_swig_wrap_test_set(arg1)
}

var _wrap_test_get unsafe.Pointer

func GetTest() (_swig_ret Fruit) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_test_get, _swig_p)
	return
}

type SwigcptrVoid uintptr
type Void interface {
	Swigcptr() uintptr;
}
func (p SwigcptrVoid) Swigcptr() uintptr {
	return uintptr(p)
}

