/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: ./../imports_b.i

package imports_b

import "unsafe"
import _ "runtime/cgo"
import "imports_a"

var _cgo_runtime_cgocall func(unsafe.Pointer, uintptr)



type _ unsafe.Pointer



type _swig_fnptr *byte
type _swig_memberptr *byte

type SwigcptrB uintptr

func (p SwigcptrB) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrB) SwigIsB() {
}

var _wrap_new_B unsafe.Pointer

func _swig_wrap_new_B() (base SwigcptrB) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_B, _swig_p)
	return
}

func NewB() (_swig_ret B) {
	return _swig_wrap_new_B()
}

var _wrap_B_bye unsafe.Pointer

func _swig_wrap_B_bye(base SwigcptrB) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_B_bye, _swig_p)
	return
}

func (arg1 SwigcptrB) Bye() {
	_swig_wrap_B_bye(arg1)
}

var _wrap_B_member_virtual_test unsafe.Pointer

func _swig_wrap_B_member_virtual_test(base SwigcptrB, _ imports_a.AMemberEnum) (_ imports_a.AMemberEnum) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_B_member_virtual_test, _swig_p)
	return
}

func (arg1 SwigcptrB) Member_virtual_test(arg2 imports_a.AMemberEnum) (_swig_ret imports_a.AMemberEnum) {
	return _swig_wrap_B_member_virtual_test(arg1, arg2)
}

var _wrap_B_global_virtual_test unsafe.Pointer

func _swig_wrap_B_global_virtual_test(base SwigcptrB, _ imports_a.GlobalEnum) (_ imports_a.GlobalEnum) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_B_global_virtual_test, _swig_p)
	return
}

func (arg1 SwigcptrB) Global_virtual_test(arg2 imports_a.GlobalEnum) (_swig_ret imports_a.GlobalEnum) {
	return _swig_wrap_B_global_virtual_test(arg1, arg2)
}

var _wrap_delete_B unsafe.Pointer

func _swig_wrap_delete_B(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_B, _swig_p)
	return
}

func DeleteB(arg1 B) {
	_swig_wrap_delete_B(arg1.Swigcptr())
}

var _wrap_B_hello unsafe.Pointer

func _swig_wrap_B_hello(base SwigcptrB) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_B_hello, _swig_p)
	return
}

func (_swig_base SwigcptrB) Hello() {
	_swig_wrap_B_hello(_swig_base)
}

func (p SwigcptrB) SwigIsA() {
}

func (p SwigcptrB) SwigGetA() imports_a.A {
	return imports_a.SwigcptrA(p.Swigcptr())
}

type B interface {
	Swigcptr() uintptr
	SwigIsB()
	Bye()
	Member_virtual_test(arg2 imports_a.AMemberEnum) (_swig_ret imports_a.AMemberEnum)
	Global_virtual_test(arg2 imports_a.GlobalEnum) (_swig_ret imports_a.GlobalEnum)
	Hello()
	SwigIsA()
	SwigGetA() imports_a.A
}

var _wrap_global_test__SWIG_1 unsafe.Pointer

func Global_test__SWIG_1(arg1 imports_a.AMemberEnum) (_swig_ret imports_a.AMemberEnum) {
	_swig_p := uintptr(unsafe.Pointer(&arg1))
	_cgo_runtime_cgocall(_wrap_global_test__SWIG_1, _swig_p)
	return
}
func Global_test(a ...interface{}) imports_a.AMemberEnum {
	argc := len(a)
	if argc == 1 {
		return Global_test__SWIG_1(a[0].(imports_a.AMemberEnum))
	}
	panic("No match for overloaded function call")
}

type SwigcptrC uintptr

func (p SwigcptrC) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrC) SwigIsC() {
}

var _wrap_C_get_a unsafe.Pointer

func _swig_wrap_C_get_a(base SwigcptrC, _ uintptr) (_ imports_a.SwigcptrA) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_C_get_a, _swig_p)
	return
}

func (arg1 SwigcptrC) Get_a(arg2 imports_a.A) (_swig_ret imports_a.A) {
	return _swig_wrap_C_get_a(arg1, arg2.Swigcptr())
}

var _wrap_C_get_a_type unsafe.Pointer

func _swig_wrap_C_get_a_type(base SwigcptrC, _ uintptr) (_ imports_a.SwigcptrA) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_C_get_a_type, _swig_p)
	return
}

func (arg1 SwigcptrC) Get_a_type(arg2 imports_a.A) (_swig_ret imports_a.A) {
	return _swig_wrap_C_get_a_type(arg1, arg2.Swigcptr())
}

var _wrap_new_C unsafe.Pointer

func _swig_wrap_new_C() (base SwigcptrC) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_C, _swig_p)
	return
}

func NewC() (_swig_ret C) {
	return _swig_wrap_new_C()
}

var _wrap_delete_C unsafe.Pointer

func _swig_wrap_delete_C(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_C, _swig_p)
	return
}

func DeleteC(arg1 C) {
	_swig_wrap_delete_C(arg1.Swigcptr())
}

var _wrap_C_hello unsafe.Pointer

func _swig_wrap_C_hello(base SwigcptrC) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_C_hello, _swig_p)
	return
}

func (_swig_base SwigcptrC) Hello() {
	_swig_wrap_C_hello(_swig_base)
}

var _wrap_C_member_virtual_test unsafe.Pointer

func _swig_wrap_C_member_virtual_test(base SwigcptrC, _ imports_a.AMemberEnum) (_ imports_a.AMemberEnum) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_C_member_virtual_test, _swig_p)
	return
}

func (_swig_base SwigcptrC) Member_virtual_test(arg1 imports_a.AMemberEnum) (_swig_ret imports_a.AMemberEnum) {
	return _swig_wrap_C_member_virtual_test(_swig_base, arg1)
}

var _wrap_C_global_virtual_test unsafe.Pointer

func _swig_wrap_C_global_virtual_test(base SwigcptrC, _ imports_a.GlobalEnum) (_ imports_a.GlobalEnum) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_C_global_virtual_test, _swig_p)
	return
}

func (_swig_base SwigcptrC) Global_virtual_test(arg1 imports_a.GlobalEnum) (_swig_ret imports_a.GlobalEnum) {
	return _swig_wrap_C_global_virtual_test(_swig_base, arg1)
}

func (p SwigcptrC) SwigIsA() {
}

func (p SwigcptrC) SwigGetA() imports_a.A {
	return imports_a.SwigcptrA(p.Swigcptr())
}

type C interface {
	Swigcptr() uintptr
	SwigIsC()
	Get_a(arg2 imports_a.A) (_swig_ret imports_a.A)
	Get_a_type(arg2 imports_a.A) (_swig_ret imports_a.A)
	Hello()
	Member_virtual_test(arg1 imports_a.AMemberEnum) (_swig_ret imports_a.AMemberEnum)
	Global_virtual_test(arg1 imports_a.GlobalEnum) (_swig_ret imports_a.GlobalEnum)
	SwigIsA()
	SwigGetA() imports_a.A
}


type SwigcptrVoid uintptr
type Void interface {
	Swigcptr() uintptr;
}
func (p SwigcptrVoid) Swigcptr() uintptr {
	return uintptr(p)
}

