/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: ./../smart_pointer_overload.i

package smart_pointer_overload

import "unsafe"
import _ "runtime/cgo"

var _cgo_runtime_cgocall func(unsafe.Pointer, uintptr)



type _ unsafe.Pointer



type _swig_fnptr *byte
type _swig_memberptr *byte

type SwigcptrFoo uintptr

func (p SwigcptrFoo) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrFoo) SwigIsFoo() {
}

var _wrap_Foo_x_set unsafe.Pointer

func _swig_wrap_Foo_x_set(base SwigcptrFoo, _ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Foo_x_set, _swig_p)
	return
}

func (arg1 SwigcptrFoo) SetX(arg2 int) {
	_swig_wrap_Foo_x_set(arg1, arg2)
}

var _wrap_Foo_x_get unsafe.Pointer

func _swig_wrap_Foo_x_get(base SwigcptrFoo) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Foo_x_get, _swig_p)
	return
}

func (arg1 SwigcptrFoo) GetX() (_swig_ret int) {
	return _swig_wrap_Foo_x_get(arg1)
}

var _wrap_Foo_test__SWIG_0 unsafe.Pointer

func _swig_wrap_Foo_test__SWIG_0(base SwigcptrFoo, _ int) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Foo_test__SWIG_0, _swig_p)
	return
}

func (arg1 SwigcptrFoo) Test__SWIG_0(arg2 int) (_swig_ret int) {
	return _swig_wrap_Foo_test__SWIG_0(arg1, arg2)
}

var _wrap_Foo_test__SWIG_1 unsafe.Pointer

func _swig_wrap_Foo_test__SWIG_1(base SwigcptrFoo, _ float64) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Foo_test__SWIG_1, _swig_p)
	return
}

func (arg1 SwigcptrFoo) Test__SWIG_1(arg2 float64) (_swig_ret int) {
	return _swig_wrap_Foo_test__SWIG_1(arg1, arg2)
}

var _wrap_Foo_test__SWIG_2 unsafe.Pointer

func _swig_wrap_Foo_test__SWIG_2(base SwigcptrFoo, _ string) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Foo_test__SWIG_2, _swig_p)
	return
}

func (arg1 SwigcptrFoo) Test__SWIG_2(arg2 string) (_swig_ret int) {
	return _swig_wrap_Foo_test__SWIG_2(arg1, arg2)
}

func (p SwigcptrFoo) Test(a ...interface{}) int {
	argc := len(a)
	if argc == 1 {
		if _, ok := a[0].(int); !ok {
			goto check_1
		}
		return p.Test__SWIG_0(a[0].(int))
	}
check_1:
	if argc == 1 {
		if _, ok := a[0].(float64); !ok {
			goto check_2
		}
		return p.Test__SWIG_1(a[0].(float64))
	}
check_2:
	if argc == 1 {
		return p.Test__SWIG_2(a[0].(string))
	}
	panic("No match for overloaded function call")
}

var _wrap_new_Foo unsafe.Pointer

func _swig_wrap_new_Foo() (base SwigcptrFoo) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_Foo, _swig_p)
	return
}

func NewFoo() (_swig_ret Foo) {
	return _swig_wrap_new_Foo()
}

var _wrap_delete_Foo unsafe.Pointer

func _swig_wrap_delete_Foo(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_Foo, _swig_p)
	return
}

func DeleteFoo(arg1 Foo) {
	_swig_wrap_delete_Foo(arg1.Swigcptr())
}

type Foo interface {
	Swigcptr() uintptr
	SwigIsFoo()
	SetX(arg2 int)
	GetX() (_swig_ret int)
	Test(a ...interface{}) int
}

type SwigcptrBar uintptr

func (p SwigcptrBar) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrBar) SwigIsBar() {
}

var _wrap_new_Bar unsafe.Pointer

func _swig_wrap_new_Bar(base uintptr) (_ SwigcptrBar) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_Bar, _swig_p)
	return
}

func NewBar(arg1 Foo) (_swig_ret Bar) {
	return _swig_wrap_new_Bar(arg1.Swigcptr())
}

var _wrap_Bar___deref__ unsafe.Pointer

func _swig_wrap_Bar___deref__(base SwigcptrBar) (_ SwigcptrFoo) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Bar___deref__, _swig_p)
	return
}

func (arg1 SwigcptrBar) X__deref__() (_swig_ret Foo) {
	return _swig_wrap_Bar___deref__(arg1)
}

var _wrap_delete_Bar unsafe.Pointer

func _swig_wrap_delete_Bar(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_Bar, _swig_p)
	return
}

func DeleteBar(arg1 Bar) {
	_swig_wrap_delete_Bar(arg1.Swigcptr())
}

var _wrap_Bar_x_set unsafe.Pointer

func _swig_wrap_Bar_x_set(base SwigcptrBar, _ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Bar_x_set, _swig_p)
	return
}

func (arg1 SwigcptrBar) SetX(arg2 int) {
	_swig_wrap_Bar_x_set(arg1, arg2)
}

var _wrap_Bar_x_get unsafe.Pointer

func _swig_wrap_Bar_x_get(base SwigcptrBar) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Bar_x_get, _swig_p)
	return
}

func (arg1 SwigcptrBar) GetX() (_swig_ret int) {
	return _swig_wrap_Bar_x_get(arg1)
}

var _wrap_Bar_test__SWIG_0 unsafe.Pointer

func _swig_wrap_Bar_test__SWIG_0(base SwigcptrBar, _ int) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Bar_test__SWIG_0, _swig_p)
	return
}

func (arg1 SwigcptrBar) Test__SWIG_0(arg2 int) (_swig_ret int) {
	return _swig_wrap_Bar_test__SWIG_0(arg1, arg2)
}

var _wrap_Bar_test__SWIG_1 unsafe.Pointer

func _swig_wrap_Bar_test__SWIG_1(base SwigcptrBar, _ float64) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Bar_test__SWIG_1, _swig_p)
	return
}

func (arg1 SwigcptrBar) Test__SWIG_1(arg2 float64) (_swig_ret int) {
	return _swig_wrap_Bar_test__SWIG_1(arg1, arg2)
}

var _wrap_Bar_test__SWIG_2 unsafe.Pointer

func _swig_wrap_Bar_test__SWIG_2(base SwigcptrBar, _ string) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Bar_test__SWIG_2, _swig_p)
	return
}

func (arg1 SwigcptrBar) Test__SWIG_2(arg2 string) (_swig_ret int) {
	return _swig_wrap_Bar_test__SWIG_2(arg1, arg2)
}

func (p SwigcptrBar) Test(a ...interface{}) int {
	argc := len(a)
	if argc == 1 {
		if _, ok := a[0].(int); !ok {
			goto check_1
		}
		return p.Test__SWIG_0(a[0].(int))
	}
check_1:
	if argc == 1 {
		if _, ok := a[0].(float64); !ok {
			goto check_2
		}
		return p.Test__SWIG_1(a[0].(float64))
	}
check_2:
	if argc == 1 {
		return p.Test__SWIG_2(a[0].(string))
	}
	panic("No match for overloaded function call")
}

type Bar interface {
	Swigcptr() uintptr
	SwigIsBar()
	X__deref__() (_swig_ret Foo)
	SetX(arg2 int)
	GetX() (_swig_ret int)
	Test(a ...interface{}) int
}


type SwigcptrVoid uintptr
type Void interface {
	Swigcptr() uintptr;
}
func (p SwigcptrVoid) Swigcptr() uintptr {
	return uintptr(p)
}

