/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: ./../smart_pointer_namespace2.i

package smart_pointer_namespace2

import "unsafe"
import _ "runtime/cgo"

var _cgo_runtime_cgocall func(unsafe.Pointer, uintptr)



type _ unsafe.Pointer



type _swig_fnptr *byte
type _swig_memberptr *byte

type SwigcptrObj1 uintptr

func (p SwigcptrObj1) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrObj1) SwigIsObj1() {
}

var _wrap_new_Obj1 unsafe.Pointer

func _swig_wrap_new_Obj1() (base SwigcptrObj1) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_Obj1, _swig_p)
	return
}

func NewObj1() (_swig_ret Obj1) {
	return _swig_wrap_new_Obj1()
}

var _wrap_Obj1_donothing unsafe.Pointer

func _swig_wrap_Obj1_donothing(base SwigcptrObj1) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Obj1_donothing, _swig_p)
	return
}

func (arg1 SwigcptrObj1) Donothing() {
	_swig_wrap_Obj1_donothing(arg1)
}

var _wrap_delete_Obj1 unsafe.Pointer

func _swig_wrap_delete_Obj1(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_Obj1, _swig_p)
	return
}

func DeleteObj1(arg1 Obj1) {
	_swig_wrap_delete_Obj1(arg1.Swigcptr())
}

type Obj1 interface {
	Swigcptr() uintptr
	SwigIsObj1()
	Donothing()
}

type SwigcptrObj1_ptr uintptr

func (p SwigcptrObj1_ptr) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrObj1_ptr) SwigIsObj1_ptr() {
}

var _wrap_new_Obj1_ptr unsafe.Pointer

func _swig_wrap_new_Obj1_ptr(base uintptr) (_ SwigcptrObj1_ptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_Obj1_ptr, _swig_p)
	return
}

func NewObj1_ptr(arg1 Obj1) (_swig_ret Obj1_ptr) {
	return _swig_wrap_new_Obj1_ptr(arg1.Swigcptr())
}

var _wrap_delete_Obj1_ptr unsafe.Pointer

func _swig_wrap_delete_Obj1_ptr(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_Obj1_ptr, _swig_p)
	return
}

func DeleteObj1_ptr(arg1 Obj1_ptr) {
	_swig_wrap_delete_Obj1_ptr(arg1.Swigcptr())
}

var _wrap_Obj1_ptr___deref__ unsafe.Pointer

func _swig_wrap_Obj1_ptr___deref__(base SwigcptrObj1_ptr) (_ SwigcptrObj1) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Obj1_ptr___deref__, _swig_p)
	return
}

func (arg1 SwigcptrObj1_ptr) X__deref__() (_swig_ret Obj1) {
	return _swig_wrap_Obj1_ptr___deref__(arg1)
}

var _wrap_Obj1_ptr_donothing unsafe.Pointer

func _swig_wrap_Obj1_ptr_donothing(base SwigcptrObj1_ptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Obj1_ptr_donothing, _swig_p)
	return
}

func (arg1 SwigcptrObj1_ptr) Donothing() {
	_swig_wrap_Obj1_ptr_donothing(arg1)
}

type Obj1_ptr interface {
	Swigcptr() uintptr
	SwigIsObj1_ptr()
	X__deref__() (_swig_ret Obj1)
	Donothing()
}

type SwigcptrObj2 uintptr

func (p SwigcptrObj2) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrObj2) SwigIsObj2() {
}

var _wrap_new_Obj2 unsafe.Pointer

func _swig_wrap_new_Obj2() (base SwigcptrObj2) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_Obj2, _swig_p)
	return
}

func NewObj2() (_swig_ret Obj2) {
	return _swig_wrap_new_Obj2()
}

var _wrap_Obj2_donothing unsafe.Pointer

func _swig_wrap_Obj2_donothing(base SwigcptrObj2) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Obj2_donothing, _swig_p)
	return
}

func (arg1 SwigcptrObj2) Donothing() {
	_swig_wrap_Obj2_donothing(arg1)
}

var _wrap_delete_Obj2 unsafe.Pointer

func _swig_wrap_delete_Obj2(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_Obj2, _swig_p)
	return
}

func DeleteObj2(arg1 Obj2) {
	_swig_wrap_delete_Obj2(arg1.Swigcptr())
}

type Obj2 interface {
	Swigcptr() uintptr
	SwigIsObj2()
	Donothing()
}

type SwigcptrObj2_ptr uintptr

func (p SwigcptrObj2_ptr) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrObj2_ptr) SwigIsObj2_ptr() {
}

var _wrap_new_Obj2_ptr unsafe.Pointer

func _swig_wrap_new_Obj2_ptr(base uintptr) (_ SwigcptrObj2_ptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_Obj2_ptr, _swig_p)
	return
}

func NewObj2_ptr(arg1 Obj2) (_swig_ret Obj2_ptr) {
	return _swig_wrap_new_Obj2_ptr(arg1.Swigcptr())
}

var _wrap_delete_Obj2_ptr unsafe.Pointer

func _swig_wrap_delete_Obj2_ptr(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_Obj2_ptr, _swig_p)
	return
}

func DeleteObj2_ptr(arg1 Obj2_ptr) {
	_swig_wrap_delete_Obj2_ptr(arg1.Swigcptr())
}

var _wrap_Obj2_ptr___deref__ unsafe.Pointer

func _swig_wrap_Obj2_ptr___deref__(base SwigcptrObj2_ptr) (_ SwigcptrObj2) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Obj2_ptr___deref__, _swig_p)
	return
}

func (arg1 SwigcptrObj2_ptr) X__deref__() (_swig_ret Obj2) {
	return _swig_wrap_Obj2_ptr___deref__(arg1)
}

var _wrap_Obj2_ptr_donothing unsafe.Pointer

func _swig_wrap_Obj2_ptr_donothing(base SwigcptrObj2_ptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Obj2_ptr_donothing, _swig_p)
	return
}

func (arg1 SwigcptrObj2_ptr) Donothing() {
	_swig_wrap_Obj2_ptr_donothing(arg1)
}

type Obj2_ptr interface {
	Swigcptr() uintptr
	SwigIsObj2_ptr()
	X__deref__() (_swig_ret Obj2)
	Donothing()
}


type SwigcptrVoid uintptr
type Void interface {
	Swigcptr() uintptr;
}
func (p SwigcptrVoid) Swigcptr() uintptr {
	return uintptr(p)
}

