/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: ./../template_specialization_enum.i

package template_specialization_enum

import "unsafe"
import _ "runtime/cgo"

var _cgo_runtime_cgocall func(unsafe.Pointer, uintptr)



type _ unsafe.Pointer



type _swig_fnptr *byte
type _swig_memberptr *byte

type Hello int
var _wrap_hi unsafe.Pointer

func _swig_gethi() (_swig_ret Hello) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_hi, _swig_p)
	return
}
var Hi Hello = _swig_gethi()
type SwigcptrBase_dd uintptr

func (p SwigcptrBase_dd) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrBase_dd) SwigIsBase_dd() {
}

var _wrap_new_Base_dd unsafe.Pointer

func _swig_wrap_new_Base_dd() (base SwigcptrBase_dd) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_Base_dd, _swig_p)
	return
}

func NewBase_dd() (_swig_ret Base_dd) {
	return _swig_wrap_new_Base_dd()
}

var _wrap_delete_Base_dd unsafe.Pointer

func _swig_wrap_delete_Base_dd(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_Base_dd, _swig_p)
	return
}

func DeleteBase_dd(arg1 Base_dd) {
	_swig_wrap_delete_Base_dd(arg1.Swigcptr())
}

type Base_dd interface {
	Swigcptr() uintptr
	SwigIsBase_dd()
}

type SwigcptrBase_ii uintptr

func (p SwigcptrBase_ii) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrBase_ii) SwigIsBase_ii() {
}

var _wrap_new_Base_ii unsafe.Pointer

func _swig_wrap_new_Base_ii() (base SwigcptrBase_ii) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_Base_ii, _swig_p)
	return
}

func NewBase_ii() (_swig_ret Base_ii) {
	return _swig_wrap_new_Base_ii()
}

var _wrap_delete_Base_ii unsafe.Pointer

func _swig_wrap_delete_Base_ii(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_Base_ii, _swig_p)
	return
}

func DeleteBase_ii(arg1 Base_ii) {
	_swig_wrap_delete_Base_ii(arg1.Swigcptr())
}

type Base_ii interface {
	Swigcptr() uintptr
	SwigIsBase_ii()
}

type SwigcptrC_i uintptr

func (p SwigcptrC_i) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrC_i) SwigIsC_i() {
}

var _wrap_C_i_fhi unsafe.Pointer

func _swig_wrap_C_i_fhi(base SwigcptrC_i) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_C_i_fhi, _swig_p)
	return
}

func (arg1 SwigcptrC_i) Fhi() (_swig_ret int) {
	return _swig_wrap_C_i_fhi(arg1)
}

var _wrap_delete_C_i unsafe.Pointer

func _swig_wrap_delete_C_i(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_C_i, _swig_p)
	return
}

func DeleteC_i(arg1 C_i) {
	_swig_wrap_delete_C_i(arg1.Swigcptr())
}

func (p SwigcptrC_i) SwigIsBase_dd() {
}

func (p SwigcptrC_i) SwigGetBase_dd() Base_dd {
	return SwigcptrBase_dd(p.Swigcptr())
}

type C_i interface {
	Swigcptr() uintptr
	SwigIsC_i()
	Fhi() (_swig_ret int)
	SwigIsBase_dd()
	SwigGetBase_dd() Base_dd
}

type SwigcptrC_d uintptr

func (p SwigcptrC_d) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrC_d) SwigIsC_d() {
}

var _wrap_C_d_fhello unsafe.Pointer

func _swig_wrap_C_d_fhello(base SwigcptrC_d) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_C_d_fhello, _swig_p)
	return
}

func (arg1 SwigcptrC_d) Fhello() (_swig_ret int) {
	return _swig_wrap_C_d_fhello(arg1)
}

var _wrap_delete_C_d unsafe.Pointer

func _swig_wrap_delete_C_d(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_C_d, _swig_p)
	return
}

func DeleteC_d(arg1 C_d) {
	_swig_wrap_delete_C_d(arg1.Swigcptr())
}

func (p SwigcptrC_d) SwigIsBase_ii() {
}

func (p SwigcptrC_d) SwigGetBase_ii() Base_ii {
	return SwigcptrBase_ii(p.Swigcptr())
}

type C_d interface {
	Swigcptr() uintptr
	SwigIsC_d()
	Fhello() (_swig_ret int)
	SwigIsBase_ii()
	SwigGetBase_ii() Base_ii
}


type SwigcptrVoid uintptr
type Void interface {
	Swigcptr() uintptr;
}
func (p SwigcptrVoid) Swigcptr() uintptr {
	return uintptr(p)
}

