/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: ./../template_namespace_forward_declaration.i

package template_namespace_forward_declaration

import "unsafe"
import _ "runtime/cgo"

var _cgo_runtime_cgocall func(unsafe.Pointer, uintptr)



type _ unsafe.Pointer



type _swig_fnptr *byte
type _swig_memberptr *byte

var _wrap_testXXX1 unsafe.Pointer

func _swig_wrap_testXXX1(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_testXXX1, _swig_p)
	return
}

func TestXXX1(arg1 XXXInt) {
	_swig_wrap_testXXX1(arg1.Swigcptr())
}

var _wrap_testXXX2 unsafe.Pointer

func _swig_wrap_testXXX2(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_testXXX2, _swig_p)
	return
}

func TestXXX2(arg1 XXXInt) {
	_swig_wrap_testXXX2(arg1.Swigcptr())
}

var _wrap_testXXX3 unsafe.Pointer

func _swig_wrap_testXXX3(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_testXXX3, _swig_p)
	return
}

func TestXXX3(arg1 XXXInt) {
	_swig_wrap_testXXX3(arg1.Swigcptr())
}

var _wrap_testYYY1 unsafe.Pointer

func _swig_wrap_testYYY1(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_testYYY1, _swig_p)
	return
}

func TestYYY1(arg1 YYYInt) {
	_swig_wrap_testYYY1(arg1.Swigcptr())
}

var _wrap_testYYY2 unsafe.Pointer

func _swig_wrap_testYYY2(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_testYYY2, _swig_p)
	return
}

func TestYYY2(arg1 YYYInt) {
	_swig_wrap_testYYY2(arg1.Swigcptr())
}

var _wrap_testYYY3 unsafe.Pointer

func _swig_wrap_testYYY3(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_testYYY3, _swig_p)
	return
}

func TestYYY3(arg1 YYYInt) {
	_swig_wrap_testYYY3(arg1.Swigcptr())
}

type SwigcptrXXXInt uintptr

func (p SwigcptrXXXInt) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrXXXInt) SwigIsXXXInt() {
}

var _wrap_XXXInt_xxx unsafe.Pointer

func _swig_wrap_XXXInt_xxx(base SwigcptrXXXInt, _ int) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_XXXInt_xxx, _swig_p)
	return
}

func (arg1 SwigcptrXXXInt) Xxx(arg2 int) (_swig_ret int) {
	return _swig_wrap_XXXInt_xxx(arg1, arg2)
}

var _wrap_new_XXXInt unsafe.Pointer

func _swig_wrap_new_XXXInt() (base SwigcptrXXXInt) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_XXXInt, _swig_p)
	return
}

func NewXXXInt() (_swig_ret XXXInt) {
	return _swig_wrap_new_XXXInt()
}

var _wrap_delete_XXXInt unsafe.Pointer

func _swig_wrap_delete_XXXInt(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_XXXInt, _swig_p)
	return
}

func DeleteXXXInt(arg1 XXXInt) {
	_swig_wrap_delete_XXXInt(arg1.Swigcptr())
}

type XXXInt interface {
	Swigcptr() uintptr
	SwigIsXXXInt()
	Xxx(arg2 int) (_swig_ret int)
}

type SwigcptrYYYInt uintptr

func (p SwigcptrYYYInt) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrYYYInt) SwigIsYYYInt() {
}

var _wrap_YYYInt_yyy unsafe.Pointer

func _swig_wrap_YYYInt_yyy(base SwigcptrYYYInt, _ int) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_YYYInt_yyy, _swig_p)
	return
}

func (arg1 SwigcptrYYYInt) Yyy(arg2 int) (_swig_ret int) {
	return _swig_wrap_YYYInt_yyy(arg1, arg2)
}

var _wrap_new_YYYInt unsafe.Pointer

func _swig_wrap_new_YYYInt() (base SwigcptrYYYInt) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_YYYInt, _swig_p)
	return
}

func NewYYYInt() (_swig_ret YYYInt) {
	return _swig_wrap_new_YYYInt()
}

var _wrap_delete_YYYInt unsafe.Pointer

func _swig_wrap_delete_YYYInt(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_YYYInt, _swig_p)
	return
}

func DeleteYYYInt(arg1 YYYInt) {
	_swig_wrap_delete_YYYInt(arg1.Swigcptr())
}

type YYYInt interface {
	Swigcptr() uintptr
	SwigIsYYYInt()
	Yyy(arg2 int) (_swig_ret int)
}


type SwigcptrVoid uintptr
type Void interface {
	Swigcptr() uintptr;
}
func (p SwigcptrVoid) Swigcptr() uintptr {
	return uintptr(p)
}

