/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: ./../template_using.i

package template_using

import "unsafe"
import _ "runtime/cgo"

var _cgo_runtime_cgocall func(unsafe.Pointer, uintptr)



type _ unsafe.Pointer



type _swig_fnptr *byte
type _swig_memberptr *byte

var _wrap_maxint unsafe.Pointer

func Maxint(arg1 int, arg2 int) (_swig_ret int) {
	_swig_p := uintptr(unsafe.Pointer(&arg1))
	_cgo_runtime_cgocall(_wrap_maxint, _swig_p)
	return
}
type SwigcptrFoofloat uintptr

func (p SwigcptrFoofloat) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrFoofloat) SwigIsFoofloat() {
}

var _wrap_new_Foofloat unsafe.Pointer

func _swig_wrap_new_Foofloat() (base SwigcptrFoofloat) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_Foofloat, _swig_p)
	return
}

func NewFoofloat() (_swig_ret Foofloat) {
	return _swig_wrap_new_Foofloat()
}

var _wrap_delete_Foofloat unsafe.Pointer

func _swig_wrap_delete_Foofloat(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_Foofloat, _swig_p)
	return
}

func DeleteFoofloat(arg1 Foofloat) {
	_swig_wrap_delete_Foofloat(arg1.Swigcptr())
}

type Foofloat interface {
	Swigcptr() uintptr
	SwigIsFoofloat()
}

var _wrap_maxfloat unsafe.Pointer

func Maxfloat(arg1 float32, arg2 float32) (_swig_ret float32) {
	_swig_p := uintptr(unsafe.Pointer(&arg1))
	_cgo_runtime_cgocall(_wrap_maxfloat, _swig_p)
	return
}

type SwigcptrVoid uintptr
type Void interface {
	Swigcptr() uintptr;
}
func (p SwigcptrVoid) Swigcptr() uintptr {
	return uintptr(p)
}

