/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: ./../unions.i

package unions

import "unsafe"
import _ "runtime/cgo"

var _cgo_runtime_cgocall func(unsafe.Pointer, uintptr)



type _ unsafe.Pointer



type _swig_fnptr *byte
type _swig_memberptr *byte

type SwigcptrSmallStruct uintptr

func (p SwigcptrSmallStruct) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrSmallStruct) SwigIsSmallStruct() {
}

var _wrap_SmallStruct_jill_set unsafe.Pointer

func _swig_wrap_SmallStruct_jill_set(base SwigcptrSmallStruct, _ int16) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_SmallStruct_jill_set, _swig_p)
	return
}

func (arg1 SwigcptrSmallStruct) SetJill(arg2 int16) {
	_swig_wrap_SmallStruct_jill_set(arg1, arg2)
}

var _wrap_SmallStruct_jill_get unsafe.Pointer

func _swig_wrap_SmallStruct_jill_get(base SwigcptrSmallStruct) (_ int16) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_SmallStruct_jill_get, _swig_p)
	return
}

func (arg1 SwigcptrSmallStruct) GetJill() (_swig_ret int16) {
	return _swig_wrap_SmallStruct_jill_get(arg1)
}

var _wrap_new_SmallStruct unsafe.Pointer

func _swig_wrap_new_SmallStruct() (base SwigcptrSmallStruct) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_SmallStruct, _swig_p)
	return
}

func NewSmallStruct() (_swig_ret SmallStruct) {
	return _swig_wrap_new_SmallStruct()
}

var _wrap_delete_SmallStruct unsafe.Pointer

func _swig_wrap_delete_SmallStruct(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_SmallStruct, _swig_p)
	return
}

func DeleteSmallStruct(arg1 SmallStruct) {
	_swig_wrap_delete_SmallStruct(arg1.Swigcptr())
}

type SmallStruct interface {
	Swigcptr() uintptr
	SwigIsSmallStruct()
	SetJill(arg2 int16)
	GetJill() (_swig_ret int16)
}

type SwigcptrBigStruct uintptr

func (p SwigcptrBigStruct) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrBigStruct) SwigIsBigStruct() {
}

var _wrap_BigStruct_jack_set unsafe.Pointer

func _swig_wrap_BigStruct_jack_set(base SwigcptrBigStruct, _ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_BigStruct_jack_set, _swig_p)
	return
}

func (arg1 SwigcptrBigStruct) SetJack(arg2 int) {
	_swig_wrap_BigStruct_jack_set(arg1, arg2)
}

var _wrap_BigStruct_jack_get unsafe.Pointer

func _swig_wrap_BigStruct_jack_get(base SwigcptrBigStruct) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_BigStruct_jack_get, _swig_p)
	return
}

func (arg1 SwigcptrBigStruct) GetJack() (_swig_ret int) {
	return _swig_wrap_BigStruct_jack_get(arg1)
}

var _wrap_BigStruct_smallstruct_set unsafe.Pointer

func _swig_wrap_BigStruct_smallstruct_set(base SwigcptrBigStruct, _ uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_BigStruct_smallstruct_set, _swig_p)
	return
}

func (arg1 SwigcptrBigStruct) SetSmallstruct(arg2 SmallStruct) {
	_swig_wrap_BigStruct_smallstruct_set(arg1, arg2.Swigcptr())
}

var _wrap_BigStruct_smallstruct_get unsafe.Pointer

func _swig_wrap_BigStruct_smallstruct_get(base SwigcptrBigStruct) (_ SwigcptrSmallStruct) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_BigStruct_smallstruct_get, _swig_p)
	return
}

func (arg1 SwigcptrBigStruct) GetSmallstruct() (_swig_ret SmallStruct) {
	return _swig_wrap_BigStruct_smallstruct_get(arg1)
}

var _wrap_new_BigStruct unsafe.Pointer

func _swig_wrap_new_BigStruct() (base SwigcptrBigStruct) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_BigStruct, _swig_p)
	return
}

func NewBigStruct() (_swig_ret BigStruct) {
	return _swig_wrap_new_BigStruct()
}

var _wrap_delete_BigStruct unsafe.Pointer

func _swig_wrap_delete_BigStruct(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_BigStruct, _swig_p)
	return
}

func DeleteBigStruct(arg1 BigStruct) {
	_swig_wrap_delete_BigStruct(arg1.Swigcptr())
}

type BigStruct interface {
	Swigcptr() uintptr
	SwigIsBigStruct()
	SetJack(arg2 int)
	GetJack() (_swig_ret int)
	SetSmallstruct(arg2 SmallStruct)
	GetSmallstruct() (_swig_ret SmallStruct)
}

type SwigcptrUnionTest uintptr

func (p SwigcptrUnionTest) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrUnionTest) SwigIsUnionTest() {
}

var _wrap_UnionTest_bs_set unsafe.Pointer

func _swig_wrap_UnionTest_bs_set(base SwigcptrUnionTest, _ uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_UnionTest_bs_set, _swig_p)
	return
}

func (arg1 SwigcptrUnionTest) SetBs(arg2 BigStruct) {
	_swig_wrap_UnionTest_bs_set(arg1, arg2.Swigcptr())
}

var _wrap_UnionTest_bs_get unsafe.Pointer

func _swig_wrap_UnionTest_bs_get(base SwigcptrUnionTest) (_ SwigcptrBigStruct) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_UnionTest_bs_get, _swig_p)
	return
}

func (arg1 SwigcptrUnionTest) GetBs() (_swig_ret BigStruct) {
	return _swig_wrap_UnionTest_bs_get(arg1)
}

var _wrap_UnionTest_ss_set unsafe.Pointer

func _swig_wrap_UnionTest_ss_set(base SwigcptrUnionTest, _ uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_UnionTest_ss_set, _swig_p)
	return
}

func (arg1 SwigcptrUnionTest) SetSs(arg2 SmallStruct) {
	_swig_wrap_UnionTest_ss_set(arg1, arg2.Swigcptr())
}

var _wrap_UnionTest_ss_get unsafe.Pointer

func _swig_wrap_UnionTest_ss_get(base SwigcptrUnionTest) (_ SwigcptrSmallStruct) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_UnionTest_ss_get, _swig_p)
	return
}

func (arg1 SwigcptrUnionTest) GetSs() (_swig_ret SmallStruct) {
	return _swig_wrap_UnionTest_ss_get(arg1)
}

var _wrap_new_UnionTest unsafe.Pointer

func _swig_wrap_new_UnionTest() (base SwigcptrUnionTest) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_UnionTest, _swig_p)
	return
}

func NewUnionTest() (_swig_ret UnionTest) {
	return _swig_wrap_new_UnionTest()
}

var _wrap_delete_UnionTest unsafe.Pointer

func _swig_wrap_delete_UnionTest(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_UnionTest, _swig_p)
	return
}

func DeleteUnionTest(arg1 UnionTest) {
	_swig_wrap_delete_UnionTest(arg1.Swigcptr())
}

type UnionTest interface {
	Swigcptr() uintptr
	SwigIsUnionTest()
	SetBs(arg2 BigStruct)
	GetBs() (_swig_ret BigStruct)
	SetSs(arg2 SmallStruct)
	GetSs() (_swig_ret SmallStruct)
}

type SwigcptrEmbeddedUnionTest uintptr

func (p SwigcptrEmbeddedUnionTest) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrEmbeddedUnionTest) SwigIsEmbeddedUnionTest() {
}

var _wrap_EmbeddedUnionTest_uni_get unsafe.Pointer

func _swig_wrap_EmbeddedUnionTest_uni_get(base SwigcptrEmbeddedUnionTest) (_ SwigcptrEmbeddedUnionTest_uni) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_EmbeddedUnionTest_uni_get, _swig_p)
	return
}

func (arg1 SwigcptrEmbeddedUnionTest) GetUni() (_swig_ret EmbeddedUnionTest_uni) {
	return _swig_wrap_EmbeddedUnionTest_uni_get(arg1)
}

var _wrap_EmbeddedUnionTest_number_set unsafe.Pointer

func _swig_wrap_EmbeddedUnionTest_number_set(base SwigcptrEmbeddedUnionTest, _ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_EmbeddedUnionTest_number_set, _swig_p)
	return
}

func (arg1 SwigcptrEmbeddedUnionTest) SetNumber(arg2 int) {
	_swig_wrap_EmbeddedUnionTest_number_set(arg1, arg2)
}

var _wrap_EmbeddedUnionTest_number_get unsafe.Pointer

func _swig_wrap_EmbeddedUnionTest_number_get(base SwigcptrEmbeddedUnionTest) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_EmbeddedUnionTest_number_get, _swig_p)
	return
}

func (arg1 SwigcptrEmbeddedUnionTest) GetNumber() (_swig_ret int) {
	return _swig_wrap_EmbeddedUnionTest_number_get(arg1)
}

var _wrap_new_EmbeddedUnionTest unsafe.Pointer

func _swig_wrap_new_EmbeddedUnionTest() (base SwigcptrEmbeddedUnionTest) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_EmbeddedUnionTest, _swig_p)
	return
}

func NewEmbeddedUnionTest() (_swig_ret EmbeddedUnionTest) {
	return _swig_wrap_new_EmbeddedUnionTest()
}

var _wrap_delete_EmbeddedUnionTest unsafe.Pointer

func _swig_wrap_delete_EmbeddedUnionTest(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_EmbeddedUnionTest, _swig_p)
	return
}

func DeleteEmbeddedUnionTest(arg1 EmbeddedUnionTest) {
	_swig_wrap_delete_EmbeddedUnionTest(arg1.Swigcptr())
}

type EmbeddedUnionTest interface {
	Swigcptr() uintptr
	SwigIsEmbeddedUnionTest()
	GetUni() (_swig_ret EmbeddedUnionTest_uni)
	SetNumber(arg2 int)
	GetNumber() (_swig_ret int)
}

type SwigcptrEmbeddedUnionTest_uni uintptr

func (p SwigcptrEmbeddedUnionTest_uni) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrEmbeddedUnionTest_uni) SwigIsEmbeddedUnionTest_uni() {
}

var _wrap_EmbeddedUnionTest_uni_big_set unsafe.Pointer

func _swig_wrap_EmbeddedUnionTest_uni_big_set(base SwigcptrEmbeddedUnionTest_uni, _ uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_EmbeddedUnionTest_uni_big_set, _swig_p)
	return
}

func (arg1 SwigcptrEmbeddedUnionTest_uni) SetBig(arg2 BigStruct) {
	_swig_wrap_EmbeddedUnionTest_uni_big_set(arg1, arg2.Swigcptr())
}

var _wrap_EmbeddedUnionTest_uni_big_get unsafe.Pointer

func _swig_wrap_EmbeddedUnionTest_uni_big_get(base SwigcptrEmbeddedUnionTest_uni) (_ SwigcptrBigStruct) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_EmbeddedUnionTest_uni_big_get, _swig_p)
	return
}

func (arg1 SwigcptrEmbeddedUnionTest_uni) GetBig() (_swig_ret BigStruct) {
	return _swig_wrap_EmbeddedUnionTest_uni_big_get(arg1)
}

var _wrap_EmbeddedUnionTest_uni_small_set unsafe.Pointer

func _swig_wrap_EmbeddedUnionTest_uni_small_set(base SwigcptrEmbeddedUnionTest_uni, _ uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_EmbeddedUnionTest_uni_small_set, _swig_p)
	return
}

func (arg1 SwigcptrEmbeddedUnionTest_uni) SetSmall(arg2 SmallStruct) {
	_swig_wrap_EmbeddedUnionTest_uni_small_set(arg1, arg2.Swigcptr())
}

var _wrap_EmbeddedUnionTest_uni_small_get unsafe.Pointer

func _swig_wrap_EmbeddedUnionTest_uni_small_get(base SwigcptrEmbeddedUnionTest_uni) (_ SwigcptrSmallStruct) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_EmbeddedUnionTest_uni_small_get, _swig_p)
	return
}

func (arg1 SwigcptrEmbeddedUnionTest_uni) GetSmall() (_swig_ret SmallStruct) {
	return _swig_wrap_EmbeddedUnionTest_uni_small_get(arg1)
}

var _wrap_new_EmbeddedUnionTest_uni unsafe.Pointer

func _swig_wrap_new_EmbeddedUnionTest_uni() (base SwigcptrEmbeddedUnionTest_uni) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_EmbeddedUnionTest_uni, _swig_p)
	return
}

func NewEmbeddedUnionTest_uni() (_swig_ret EmbeddedUnionTest_uni) {
	return _swig_wrap_new_EmbeddedUnionTest_uni()
}

var _wrap_delete_EmbeddedUnionTest_uni unsafe.Pointer

func _swig_wrap_delete_EmbeddedUnionTest_uni(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_EmbeddedUnionTest_uni, _swig_p)
	return
}

func DeleteEmbeddedUnionTest_uni(arg1 EmbeddedUnionTest_uni) {
	_swig_wrap_delete_EmbeddedUnionTest_uni(arg1.Swigcptr())
}

type EmbeddedUnionTest_uni interface {
	Swigcptr() uintptr
	SwigIsEmbeddedUnionTest_uni()
	SetBig(arg2 BigStruct)
	GetBig() (_swig_ret BigStruct)
	SetSmall(arg2 SmallStruct)
	GetSmall() (_swig_ret SmallStruct)
}


type SwigcptrVoid uintptr
type Void interface {
	Swigcptr() uintptr;
}
func (p SwigcptrVoid) Swigcptr() uintptr {
	return uintptr(p)
}

