/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: ./../using_protected.i

package using_protected

import "unsafe"
import _ "runtime/cgo"

var _cgo_runtime_cgocall func(unsafe.Pointer, uintptr)



type _ unsafe.Pointer



type _swig_fnptr *byte
type _swig_memberptr *byte

type SwigcptrFoo uintptr

func (p SwigcptrFoo) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrFoo) SwigIsFoo() {
}

var _wrap_new_Foo unsafe.Pointer

func _swig_wrap_new_Foo() (base SwigcptrFoo) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_Foo, _swig_p)
	return
}

func NewFoo() (_swig_ret Foo) {
	return _swig_wrap_new_Foo()
}

var _wrap_delete_Foo unsafe.Pointer

func _swig_wrap_delete_Foo(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_Foo, _swig_p)
	return
}

func DeleteFoo(arg1 Foo) {
	_swig_wrap_delete_Foo(arg1.Swigcptr())
}

type Foo interface {
	Swigcptr() uintptr
	SwigIsFoo()
}

type SwigcptrFooBar uintptr

func (p SwigcptrFooBar) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrFooBar) SwigIsFooBar() {
}

var _wrap_FooBar_blah unsafe.Pointer

func _swig_wrap_FooBar_blah(base SwigcptrFooBar, _ int) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_FooBar_blah, _swig_p)
	return
}

func (arg1 SwigcptrFooBar) Blah(arg2 int) (_swig_ret int) {
	return _swig_wrap_FooBar_blah(arg1, arg2)
}

var _wrap_FooBar_x_set unsafe.Pointer

func _swig_wrap_FooBar_x_set(base SwigcptrFooBar, _ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_FooBar_x_set, _swig_p)
	return
}

func (arg1 SwigcptrFooBar) SetX(arg2 int) {
	_swig_wrap_FooBar_x_set(arg1, arg2)
}

var _wrap_FooBar_x_get unsafe.Pointer

func _swig_wrap_FooBar_x_get(base SwigcptrFooBar) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_FooBar_x_get, _swig_p)
	return
}

func (arg1 SwigcptrFooBar) GetX() (_swig_ret int) {
	return _swig_wrap_FooBar_x_get(arg1)
}

var _wrap_FooBar_vmethod unsafe.Pointer

func _swig_wrap_FooBar_vmethod(base SwigcptrFooBar, _ int) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_FooBar_vmethod, _swig_p)
	return
}

func (arg1 SwigcptrFooBar) Vmethod(arg2 int) (_swig_ret int) {
	return _swig_wrap_FooBar_vmethod(arg1, arg2)
}

var _wrap_new_FooBar unsafe.Pointer

func _swig_wrap_new_FooBar() (base SwigcptrFooBar) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_FooBar, _swig_p)
	return
}

func NewFooBar() (_swig_ret FooBar) {
	return _swig_wrap_new_FooBar()
}

var _wrap_delete_FooBar unsafe.Pointer

func _swig_wrap_delete_FooBar(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_FooBar, _swig_p)
	return
}

func DeleteFooBar(arg1 FooBar) {
	_swig_wrap_delete_FooBar(arg1.Swigcptr())
}

func (p SwigcptrFooBar) SwigIsFoo() {
}

func (p SwigcptrFooBar) SwigGetFoo() Foo {
	return SwigcptrFoo(p.Swigcptr())
}

type FooBar interface {
	Swigcptr() uintptr
	SwigIsFooBar()
	Blah(arg2 int) (_swig_ret int)
	SetX(arg2 int)
	GetX() (_swig_ret int)
	Vmethod(arg2 int) (_swig_ret int)
	SwigIsFoo()
	SwigGetFoo() Foo
}

type SwigcptrFooBaz uintptr

func (p SwigcptrFooBaz) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrFooBaz) SwigIsFooBaz() {
}

var _wrap_new_FooBaz unsafe.Pointer

func _swig_wrap_new_FooBaz() (base SwigcptrFooBaz) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_FooBaz, _swig_p)
	return
}

func NewFooBaz() (_swig_ret FooBaz) {
	return _swig_wrap_new_FooBaz()
}

var _wrap_delete_FooBaz unsafe.Pointer

func _swig_wrap_delete_FooBaz(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_FooBaz, _swig_p)
	return
}

func DeleteFooBaz(arg1 FooBaz) {
	_swig_wrap_delete_FooBaz(arg1.Swigcptr())
}

func (p SwigcptrFooBaz) SwigIsFoo() {
}

func (p SwigcptrFooBaz) SwigGetFoo() Foo {
	return SwigcptrFoo(p.Swigcptr())
}

type FooBaz interface {
	Swigcptr() uintptr
	SwigIsFooBaz()
	SwigIsFoo()
	SwigGetFoo() Foo
}


type SwigcptrVoid uintptr
type Void interface {
	Swigcptr() uintptr;
}
func (p SwigcptrVoid) Swigcptr() uintptr {
	return uintptr(p)
}

