/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.3
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: ./../valuewrapper_opaque.i

package valuewrapper_opaque

import "unsafe"
import _ "runtime/cgo"

var _cgo_runtime_cgocall func(unsafe.Pointer, uintptr)



type _ unsafe.Pointer



type _swig_fnptr *byte
type _swig_memberptr *byte

type SwigcptrA uintptr

func (p SwigcptrA) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrA) SwigIsA() {
}

var _wrap_new_A unsafe.Pointer

func _swig_wrap_new_A(base int) (_ SwigcptrA) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_A, _swig_p)
	return
}

func NewA(arg1 int) (_swig_ret A) {
	return _swig_wrap_new_A(arg1)
}

var _wrap_delete_A unsafe.Pointer

func _swig_wrap_delete_A(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_A, _swig_p)
	return
}

func DeleteA(arg1 A) {
	_swig_wrap_delete_A(arg1.Swigcptr())
}

type A interface {
	Swigcptr() uintptr
	SwigIsA()
}

type SwigcptrD uintptr

func (p SwigcptrD) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrD) SwigIsD() {
}

var _wrap_new_D unsafe.Pointer

func _swig_wrap_new_D() (base SwigcptrD) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_D, _swig_p)
	return
}

func NewD() (_swig_ret D) {
	return _swig_wrap_new_D()
}

var _wrap_delete_D unsafe.Pointer

func _swig_wrap_delete_D(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_D, _swig_p)
	return
}

func DeleteD(arg1 D) {
	_swig_wrap_delete_D(arg1.Swigcptr())
}

type D interface {
	Swigcptr() uintptr
	SwigIsD()
}

type SwigcptrKlass uintptr

func (p SwigcptrKlass) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrKlass) SwigIsKlass() {
}

var _wrap_new_Klass unsafe.Pointer

func _swig_wrap_new_Klass() (base SwigcptrKlass) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_Klass, _swig_p)
	return
}

func NewKlass() (_swig_ret Klass) {
	return _swig_wrap_new_Klass()
}

var _wrap_delete_Klass unsafe.Pointer

func _swig_wrap_delete_Klass(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_Klass, _swig_p)
	return
}

func DeleteKlass(arg1 Klass) {
	_swig_wrap_delete_Klass(arg1.Swigcptr())
}

type Klass interface {
	Swigcptr() uintptr
	SwigIsKlass()
}

var _wrap_getKlass unsafe.Pointer

func _swig_wrap_getKlass(base uintptr) (_ SwigcptrTemplateClass_Sl_Klass_Sg_) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_getKlass, _swig_p)
	return
}

func GetKlass(arg1 Klass) (_swig_ret TemplateClass_Sl_Klass_Sg_) {
	return _swig_wrap_getKlass(arg1.Swigcptr())
}

var _wrap_getA__SWIG_0 unsafe.Pointer

func _swig_wrap_getA__SWIG_0(base uintptr) (_ SwigcptrTemplateClass_Sl_A_Sg_) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_getA__SWIG_0, _swig_p)
	return
}

func GetA__SWIG_0(arg1 A) (_swig_ret TemplateClass_Sl_A_Sg_) {
	return _swig_wrap_getA__SWIG_0(arg1.Swigcptr())
}

var _wrap_getA__SWIG_1 unsafe.Pointer

func _swig_wrap_getA__SWIG_1(base uintptr) (_ SwigcptrTemplateClass_Sl_B_Sg_) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_getA__SWIG_1, _swig_p)
	return
}

func GetA__SWIG_1(arg1 B) (_swig_ret TemplateClass_Sl_B_Sg_) {
	return _swig_wrap_getA__SWIG_1(arg1.Swigcptr())
}

func GetA(a ...interface{}) interface{} {
	argc := len(a)
	if argc == 1 {
		if _, ok := a[0].(A); !ok {
			goto check_1
		}
		return GetA__SWIG_0(a[0].(A))
	}
check_1:
	if argc == 1 {
		return GetA__SWIG_1(a[0].(B))
	}
	panic("No match for overloaded function call")
}

var _wrap_getC unsafe.Pointer

func _swig_wrap_getC(base uintptr) (_ SwigcptrTemplateClass_Sl_C_Sg_) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_getC, _swig_p)
	return
}

func GetC(arg1 C) (_swig_ret TemplateClass_Sl_C_Sg_) {
	return _swig_wrap_getC(arg1.Swigcptr())
}

var _wrap_getInt unsafe.Pointer

func _swig_wrap_getInt(base int) (_ SwigcptrTemplateClass_Sl_int_Sg_) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_getInt, _swig_p)
	return
}

func GetInt(arg1 int) (_swig_ret TemplateClass_Sl_int_Sg_) {
	return _swig_wrap_getInt(arg1)
}

var _wrap_sgetA unsafe.Pointer

func _swig_wrap_sgetA(base uintptr) (_ SwigcptrA) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_sgetA, _swig_p)
	return
}

func SgetA(arg1 A) (_swig_ret A) {
	return _swig_wrap_sgetA(arg1.Swigcptr())
}

var _wrap_sgetKlass unsafe.Pointer

func _swig_wrap_sgetKlass(base uintptr) (_ SwigcptrKlass) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_sgetKlass, _swig_p)
	return
}

func SgetKlass(arg1 Klass) (_swig_ret Klass) {
	return _swig_wrap_sgetKlass(arg1.Swigcptr())
}

var _wrap_getPtrA unsafe.Pointer

func _swig_wrap_getPtrA(base uintptr) (_ SwigcptrAuto_ptr_Sl_A_Sg_) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_getPtrA, _swig_p)
	return
}

func GetPtrA(arg1 Auto_ptr_Sl_A_Sg_) (_swig_ret Auto_ptr_Sl_A_Sg_) {
	return _swig_wrap_getPtrA(arg1.Swigcptr())
}

var _wrap_getB unsafe.Pointer

func _swig_wrap_getB(base uintptr) (_ SwigcptrB) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_getB, _swig_p)
	return
}

func GetB(arg1 B) (_swig_ret B) {
	return _swig_wrap_getB(arg1.Swigcptr())
}

var _wrap_getD unsafe.Pointer

func _swig_wrap_getD(base uintptr) (_ SwigcptrD) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_getD, _swig_p)
	return
}

func GetD(arg1 D) (_swig_ret D) {
	return _swig_wrap_getD(arg1.Swigcptr())
}

type SwigcptrAA uintptr

func (p SwigcptrAA) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrAA) SwigIsAA() {
}

var _wrap_new_AA unsafe.Pointer

func _swig_wrap_new_AA() (base SwigcptrAA) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_AA, _swig_p)
	return
}

func NewAA() (_swig_ret AA) {
	return _swig_wrap_new_AA()
}

var _wrap_AA_innerObj_set unsafe.Pointer

func _swig_wrap_AA_innerObj_set(base SwigcptrAA, _ uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_AA_innerObj_set, _swig_p)
	return
}

func (arg1 SwigcptrAA) SetInnerObj(arg2 BB) {
	_swig_wrap_AA_innerObj_set(arg1, arg2.Swigcptr())
}

var _wrap_AA_innerObj_get unsafe.Pointer

func _swig_wrap_AA_innerObj_get(base SwigcptrAA) (_ SwigcptrBB) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_AA_innerObj_get, _swig_p)
	return
}

func (arg1 SwigcptrAA) GetInnerObj() (_swig_ret BB) {
	return _swig_wrap_AA_innerObj_get(arg1)
}

var _wrap_delete_AA unsafe.Pointer

func _swig_wrap_delete_AA(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_AA, _swig_p)
	return
}

func DeleteAA(arg1 AA) {
	_swig_wrap_delete_AA(arg1.Swigcptr())
}

type AA interface {
	Swigcptr() uintptr
	SwigIsAA()
	SetInnerObj(arg2 BB)
	GetInnerObj() (_swig_ret BB)
}

type SwigcptrQuux uintptr

func (p SwigcptrQuux) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrQuux) SwigIsQuux() {
}

var _wrap_new_Quux unsafe.Pointer

func _swig_wrap_new_Quux() (base SwigcptrQuux) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_Quux, _swig_p)
	return
}

func NewQuux() (_swig_ret Quux) {
	return _swig_wrap_new_Quux()
}

var _wrap_Quux_method unsafe.Pointer

func _swig_wrap_Quux_method(base SwigcptrQuux) (_ SwigcptrFoobar) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Quux_method, _swig_p)
	return
}

func (arg1 SwigcptrQuux) Method() (_swig_ret Foobar) {
	return _swig_wrap_Quux_method(arg1)
}

var _wrap_delete_Quux unsafe.Pointer

func _swig_wrap_delete_Quux(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_Quux, _swig_p)
	return
}

func DeleteQuux(arg1 Quux) {
	_swig_wrap_delete_Quux(arg1.Swigcptr())
}

type Quux interface {
	Swigcptr() uintptr
	SwigIsQuux()
	Method() (_swig_ret Foobar)
}


type SwigcptrTemplateClass_Sl_A_Sg_ uintptr
type TemplateClass_Sl_A_Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrTemplateClass_Sl_A_Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrVoid uintptr
type Void interface {
	Swigcptr() uintptr;
}
func (p SwigcptrVoid) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrBB uintptr
type BB interface {
	Swigcptr() uintptr;
}
func (p SwigcptrBB) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrTemplateClass_Sl_B_Sg_ uintptr
type TemplateClass_Sl_B_Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrTemplateClass_Sl_B_Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrFoobar uintptr
type Foobar interface {
	Swigcptr() uintptr;
}
func (p SwigcptrFoobar) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrTemplateClass_Sl_C_Sg_ uintptr
type TemplateClass_Sl_C_Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrTemplateClass_Sl_C_Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrTemplateClass_Sl_Klass_Sg_ uintptr
type TemplateClass_Sl_Klass_Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrTemplateClass_Sl_Klass_Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrAuto_ptr_Sl_A_Sg_ uintptr
type Auto_ptr_Sl_A_Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrAuto_ptr_Sl_A_Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrTemplateClass_Sl_int_Sg_ uintptr
type TemplateClass_Sl_int_Sg_ interface {
	Swigcptr() uintptr;
}
func (p SwigcptrTemplateClass_Sl_int_Sg_) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrB uintptr
type B interface {
	Swigcptr() uintptr;
}
func (p SwigcptrB) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrC uintptr
type C interface {
	Swigcptr() uintptr;
}
func (p SwigcptrC) Swigcptr() uintptr {
	return uintptr(p)
}

