#!/usr/bin/python

import doxygen_translate_all_tags
import string
import sys

def check(got, expected):
  #if got is Null
  #  raise RuntimeError('Expected comment string\n')
  gotStr = string.replace(got, ' ', '')
  gotStr = string.replace(gotStr, '\n', '')
  gotStr = string.replace(gotStr, '\t', '')
  expectedStr = string.replace(expected, ' ', '')
  expectedStr = string.replace(expectedStr, '\n', '')
  expectedStr = string.replace(expectedStr, '\t', '')
  if not gotStr == expectedStr:
    raise RuntimeError("Expected: [" + str(expected) + "]\n" + "Got     : [" + str(got) + "]\n")

check(doxygen_translate_all_tags.function.__doc__, ''
'  _Hello_'
''
'  SomeLatexIndex '
''
'  someGroupSome title '
''
'  theAnchor'
''
'   -some list item '
''
'  This is attention! '
'  You were warned! '
''
'  Authors:'
'  lots of them '
''
'  Zubr '
''
'  __boldword__'
''
'  Some brief description, '
'  extended to many lines. '
''
'  Not everything works right now... '
''
'  codeword'
''
'  someCategoryheaderFile.hheaderName'
''
'  \'citationword\''
''
'  someClassheaderFile.hheaderName'
''
'  some test code '
''
'  Conditional comment: SOMECONDITION'
'  Some conditional comment '
'  End of conditional comment.'
''
'  someClass::someMethod'
''
'  someClass::someMethod2'
''
'  someClass::someMethod3'
''
'  Copyright:'
'  some copyright '
''
'  1970 - 2012 '
''
'  someDefine'
''
'  someGroupSome titles '
''
'  Deprecated:'
'  Now use another function '
''
'  This is very large '
'  and detailed description of some thing '
''
'  /somePath/someFolder'
''
'  someFile.h'
''
'  digraph example { '
'  node [shape=record, fontname=Helvetica, fontsize=10]; '
''
'  b [ label="class B" URL="\ref B"]; '
'  c [ label="class C" URL="\ref C"]; '
'  b -> c [ arrowhead="open", style="dashed" ]; '
'  } '
''
''
'  dotFile.dotThe caption'
''
'  _italicword_'
''
'  emphazedWord'
''
'  someEnum'
''
'  Example:'
'  someFile.txt'
'  Some details on using the example '
''
'  Throws:'
'  SuperError'
''
'  someOtherFunction'
''
'  file.h'
''
'  someFn '
''
'  someHeader.hHeader name'
''
'  htmlFile.htm'
''
'  This will only appear in hmtl '
''
'  If: ANOTHERCONDITION {'
'  First part of comment '
'  If: SECONDCONDITION {'
'  Nested condition text '
'  }Else if: THIRDCONDITION {'
'  The third condition text '
'  }Else:  {The last text block '
'  }'
'  }Else:  {Second part of comment '
'  If: CONDITION {'
'  Second part extended '
'  }'
'  }'
''
'  If not: SOMECONDITION {'
'  This is printed if not '
'  }'
''
'  Image: htmltestImage.bmpHello, world!asd=10qwe'
''
'  someFunction'
''
'  header.h'
''
'  header2.h'
''
'  someGroupanotherGroup'
''
'  Some text '
'  describing invariant. '
''
'  someInterfacesomeHeader.hHeader name'
''
'  This will only appear in LATeX '
''
'  <ul> '
''
'   -Some unordered list '
'   -With lots of items '
'   -lots of lots of items '
''
'  </ul> '
''
'  example '
''
'  someMember Some description follows '
''
'  Sometitle '
''
'  This will only appear in man '
''
'  someThing'
''
'  Sender,Receiver; '
'  Sender->Receiver [label="Command()", URL="\ref '
'  Receiver::Command()"]; '
'  Sender<-Receiver [label="Ack()", URL="\ref '
'  Ack()", ID="1"]; '
''
'  mscFile.mscThe caption'
''
'  someHeader.h '
''
'  someNamespace'
''
'  Notes:'
'  Here '
'  is the note! '
''
'  This is an overloaded member function, provided for convenience.'
'  It differs from the above function only in what argument(s) it accepts.'
''
'  someword'
''
'  superPackage'
''
'  somePageThe title '
''
'  Title: The paragraph title '
'  The paragraph text. '
'  Maybe even multiline '
''
'  someParagraphParagraph title '
''
'  Arguments:'
'  a (int)                              -- the first param '
''
'  Some description '
''
'  Some description '
''
'  someVar '
''
'  someProtocolheader.hHeader name'
''
'  someAnchor'
''
'  toSomething'
''
'  toSomethingElse'
''
'  someName'
''
'  someName'
''
'  Remarks:'
'  Some remark text '
''
'  Another remarks section '
''
'  Return:'
'  Whatever '
''
'  it '
''
'  may return '
''
'  someValueSome description '
''
''
'  This will only appear in RTF '
''
''
'  See also:'
'  someOtherMethod '
''
'  someSectionSome title '
''
'  function '
''
'  Same as '
'  brief description '
''
''
''
'  Since:'
'  version 0.0.0.1 '
''
'  somePattern '
''
'  someLine '
''
'  example.hSome snippet '
''
'  someStruct'
''
'  someSubpageSome description'
''
'  someSubsectionSome title '
''
'  someSubsectionSome title '
''
''
''
'  Some '
'  description of the '
'  test case '
''
'  Throws:'
'  superException'
''
'  RuntimeError'
''
'  TODO:'
'  Some very important task '
''
'  Arguments:'
'  b (float)                              -- B is mentioned again... '
''
'  someTypedef '
''
'  someUnion'
''
'  somePattern '
''
'  someVar '
''
''
'  very long '
'  text with tags <sometag> '
''
''
'  someFile.h'
''
'  Version:'
'  0.0.0.2 '
''
'  Warning:'
'  This is senseless! '
''
'  someGroupSome title '
''
''
'  This will only appear in XML '
''
''
'  Here goes test of symbols: '
'  $@\&~<>#%".::'
''
'  And here goes simple text '
)