const assert = require('assert');
require('./extend_wrap.js')().then((m) => {
  const ordinary = new m.Extended();
  assert.strictEqual(ordinary.value(), 2);
  assert.strictEqual(ordinary.scaled(), 6);
  assert.strictEqual(ordinary.scaled(4), 8);
  assert.strictEqual(ordinary.combined(1), 3);
  assert.strictEqual(ordinary.combined(1, 2), 5);
  const extended = new m.Extended(3, 4);
  assert.strictEqual(extended.value(), 7);
  assert.strictEqual(extended.scaled(2), 14);
  assert.strictEqual(m.Extended.sum(1), 5);
  assert.strictEqual(m.Extended.sum(1, 2), 3);
  assert.throws(() => new m.Extended('wrong', 2));
  assert.throws(() => ordinary.scaled('wrong'));
  assert.throws(() => ordinary.scaled(2, 3));
  assert.throws(() => ordinary.combined(1, 2, 3));
  const templated = new m.TemplatedConstructor(13);
  assert.strictEqual(templated.value(), 13);
  assert.strictEqual(templated.doubled(), 26);
  templated.delete();
  assert.strictEqual(m.null_deep_const(null), true);
  const explicitDefault = new m.ExplicitValue();
  assert.strictEqual(explicitDefault.value, 0);
  const explicit = new m.ExplicitValue(19);
  const explicitCopy = m.explicit_copy(explicit);
  explicitCopy.value = 20;
  assert.strictEqual(m.explicit_ref(explicit), 19);
  assert.strictEqual(explicitCopy.value, 20);
  explicitDefault.delete();
  explicit.delete();
  explicitCopy.delete();
  assert.strictEqual(m.Multiple.primary_static(3), 4);
  assert.strictEqual(m.Multiple.scale(3), 6);
  assert.strictEqual(m.Multiple.scale(3, 4), 12);
  const inheritedDefault = m.Multiple.make();
  const inheritedValue = m.Multiple.make(23);
  assert.strictEqual(inheritedDefault.value, 9);
  assert.strictEqual(inheritedValue.value, 23);
  inheritedDefault.delete();
  inheritedValue.delete();
  assert.throws(() => m.Multiple.scale('wrong'));
  assert.throws(() => m.Multiple.make('wrong'));
  ordinary.delete();
  extended.delete();
}).catch((error) => { console.error(error); process.exitCode = 1; });
