const assert = require('assert');
require('./stl_references_wrap.js')().then((m) => {
  assert.strictEqual(m.missing_vector(), null);
  assert.strictEqual(m.missing_map(), null);
  assert.strictEqual(m.missing_pair(), null);
  assert.throws(() => m.mutate_vector_pointer(null), TypeError);
  const store = new m.Store();
  const vector = store.vector_ref();
  const vectorPointer = store.vector_pointer();
  assert.strictEqual(vector.at(0), 3);
  m.mutate_vector(vector);
  m.mutate_vector_pointer(vectorPointer);
  vector.set(0, 13);
  assert.deepStrictEqual(store.vector_snapshot(), [13, 9, 10]);
  assert.throws(() => m.mutate_vector([1, 2]));
  assert.throws(() => m.mutate_vector_pointer([1, 2]));
  assert.throws(() => vector.at(-1));
  assert.throws(() => vector.at(3));
  assert.throws(() => vector.set(3, 0));
  vector.delete();
  vectorPointer.delete();
  assert.deepStrictEqual(store.vector_snapshot(), [13, 9, 10]);

  const map = store.map_ref();
  const mapPointer = store.map_pointer();
  m.mutate_map(map);
  m.mutate_map_pointer(mapPointer);
  map.set(4, 15);
  assert.deepStrictEqual(store.map_snapshot(), new Map([[4, 15], [6, 7], [8, 9]]));
  assert.strictEqual(map.has(6), true);
  assert.strictEqual(map.has(99), false);
  assert.throws(() => map.get(99));
  assert.throws(() => m.mutate_map(new Map()));
  assert.throws(() => m.mutate_map_pointer(new Map()));
  map.erase(6);
  assert.strictEqual(mapPointer.has(6), false);
  map.delete();
  mapPointer.delete();
  assert.deepStrictEqual(store.map_snapshot(), new Map([[4, 15], [8, 9]]));

  const pair = store.pair_ref();
  const pairPointer = store.pair_pointer();
  m.mutate_pair(pair);
  m.mutate_pair_pointer(pairPointer);
  assert.deepStrictEqual(store.pair_snapshot(), [11, 12]);
  assert.throws(() => m.mutate_pair([1, 2]));
  assert.throws(() => m.mutate_pair_pointer([1, 2]));
  pair.delete();
  pairPointer.delete();
  assert.deepStrictEqual(store.pair_snapshot(), [11, 12]);
  store.delete();

  const owned = new m.IntVector();
  assert.strictEqual(owned.empty(), true);
  owned.reserve(8);
  assert(owned.capacity() >= 8);
  owned.push_back(4);
  owned.push_back(5);
  owned.pop_back();
  assert.strictEqual(owned.size(), 1);
  assert.strictEqual(owned.at(0), 4);
  owned.clear();
  assert.strictEqual(owned.empty(), true);
  assert.throws(() => owned.pop_back());
  owned.delete();
  owned.delete();
  assert.throws(() => m.mutate_vector(owned));
}).catch((error) => { console.error(error); process.exitCode = 1; });
