%include <std_string.i>
%include <std_vector.i>
%include <std_deque.i>
%include <std_list.i>
%include <std_map.i>
%include <std_unordered_map.i>
%include <std_set.i>
%include <std_unordered_set.i>
%include <std_pair.i>
%include <std_array.i>
