/* -----------------------------------------------------------------------------
 * javascript.swg
 *
 * Javascript typemaps
 * ----------------------------------------------------------------------------- */

/* ------------------------------------------------------------
 *  Inner macros
 * ------------------------------------------------------------ */
%include <javascriptmacros.swg>

%include <javascripttypemaps.swg>

%include <javascriptruntime.swg>

%include <javascripthelpers.swg>

%include <javascriptkw.swg>

%include <javascriptcode.swg>

%include <javascriptinit.swg>
