%module cpp_python_stub_rank
%feature("python:annotations", "typing");
%feature("python:stub:overloads");
%feature("python:stub:overloads", rank="") invalid0(int);
int invalid0(int);
int invalid0(double);
%feature("python:stub:overloads", rank="+") invalid1(int);
int invalid1(int);
int invalid1(double);
%feature("python:stub:overloads", rank="1x") invalid2(int);
int invalid2(int);
int invalid2(double);
%feature("python:stub:overloads", rank=" 1") invalid3(int);
int invalid3(int);
int invalid3(double);
%feature("python:stub:overloads", rank="1 ") invalid4(int);
int invalid4(int);
int invalid4(double);
%feature("python:stub:overloads", rank="2147483648") invalid5(int);
int invalid5(int);
int invalid5(double);
%feature("python:stub:overloads", rank="-2147483649") invalid6(int);
int invalid6(int);
int invalid6(double);
%feature("python:stub:overloads", rank="9999999999999999999999999999999999999999") invalid7(int);
int invalid7(int);
int invalid7(double);
%feature("python:stub:overloads", rank="1.5") single;
int single(int);
