x = 'hello';
assert(strcmp(li_std_string_extra.test_ccvalue(x), x));
assert(strcmp(li_std_string_extra.test_cvalue(x), x));
assert(strcmp(li_std_string_extra.test_value(x), x));
assert(strcmp(li_std_string_extra.test_const_reference(x), x));
s = li_std_string_extra.string('he');
s = s + 'llo';
assert(strcmp(li_std_string_extra.test_value(s), x));
a = li_std_string_extra.A(s);
assert(strcmp(li_std_string_extra.test_value(a), x));
b = li_std_string_extra.string(' world');
assert(strcmp(li_std_string_extra.test_value(a + b), 'hello world'));
assert(strcmp(li_std_string_extra.test_value(a + ' world'), 'hello world'));
c = li_std_string_extra.string('hello') + b;
assert(c.find_last_of('l') == 9);
b = li_std_string_extra.B('hi');
b.name(li_std_string_extra.string('hello'));
assert(strcmp(li_std_string_extra.test_value(b.name()), 'hello'));
b.a(li_std_string_extra.A('hello'));
assert(strcmp(li_std_string_extra.test_value(b.a()), 'hello'));
assert(strcmp(li_std_string_extra.test_value_basic1(x), x));
assert(strcmp(li_std_string_extra.test_value_basic2(x), x));
assert(strcmp(li_std_string_extra.test_value_basic3(x), x));
assert(strcmp(li_std_string_extra.GlobalString2(), 'global string 2'));
li_std_string_extra.GlobalString2('updated');
assert(strcmp(li_std_string_extra.GlobalString2(), 'updated'));
assert(strcmp(li_std_string_extra.ConstGlobalString(), 'const global string'));
s = li_std_string_extra.Structure();
assert(strcmp(s.MemberString2(), 'member string 2'));
s.MemberString2('updated');
assert(strcmp(s.MemberString2(), 'updated'));
assert(strcmp(s.ConstMemberString(), 'const member string'));
assert(strcmp(li_std_string_extra.Structure.StaticMemberString2(), 'static member string 2'));
li_std_string_extra.Structure.StaticMemberString2('updated');
assert(strcmp(li_std_string_extra.Structure.StaticMemberString2(), 'updated'));
assert(strcmp(li_std_string_extra.test_reference_input('hello'), 'hello'));
assert(strcmp(li_std_string_extra.test_reference_inout('hello'), 'hellohello'));
assert(isempty(li_std_string_extra.stdstring_empty()));
assert(isempty(li_std_string_extra.c_empty()));
