#!/bin/sh

# POSIX to Windows path conversion in a script.
# Useful for avoiding backslash quoting difficulties in Makefiles.
# Acts as a much dumbed down cygpath tool.
# See: https://cygwin.com/cygwin-ug-net/cygpath.html

usage()
{
  cat <<EOF
Usage: $0 [-m|-u|-w|-h] [path]...

Convert Windows and Unix paths

  -m  Convert forward slashes to backslashes in the paths (relative paths only)
  -u  Convert forward slashes to backslashes in the paths (relative paths only)
  -w  Convert backslashes to forward slashes in the paths (relative paths only)
EOF
}

option="$1"
shift
case "$option" in
  -m|-u)
    echo "$@" | sed -e 's,\\,/,g'
    ;;
  -w)
    echo "$@" | sed -e 's,/,\\,g'
    ;;
  -h)
    usage
    ;;
  *)
    usage
    exit 1
    ;;
esac

exit 0
