#!/bin/sh

# This is a simple utility for Cygwin/Mingw which is useful when running the SWIG
# test-suite through Visual Studio. If the output from the test-suite is piped
# through this utility, it will filter the junk that the compiler generates.
# Typical usage: make check | vcfilter

# dos2unix needed for ^ and $ to work.
# warning C4290: C++ exception specification ignored except to indicate a function is not __declspec(nothrow)
2>&1 dos2unix | grep -v "\.cxx$" | grep -v "\.c$" | grep -v "^   Creating library" | grep -v "^Generating Code" | grep -v "warning C4290:"

