//
// octave.swg - Octave configuration module
//

// Include standard SWIG macros and fragments
%include <typemaps/swigmacros.swg>
%include <typemaps/fragments.swg>

// Include Octave runtime code
%include <octruntime.swg>

// Include Octave typemaps
%include <octtypemaps.swg>

// Include Octave overloaded operator support
%include <octopers.swg>

// Include Octave special user directives
%include <octuserdir.swg>
