/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
#include "abstract_inherit_using_proxy.h"
#include "abstract_inherit_using_wrap.h"


@implementation AbstractBase
-(void*)getCptr {
	return [self swigCPtrForAbstractBase];
}

-(void*)swigCPtrForAbstractBase {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(void)f: (int)n
{
 _wrap_AbstractBase_f([self swigCPtrForAbstractBase], n);
}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_AbstractBase((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation ConcreteDerived1
- (void*)getCptr {
	return [self swigCPtrForConcreteDerived1];
}

-(void*)swigCPtrForConcreteDerived1 {
	return swigCPtr_ConcreteDerived1;
}

-(void*)swigRelease {
	void *cptr = swigCPtr_ConcreteDerived1;
	swigCPtr_ConcreteDerived1 = NULL;
	swigCPtr = NULL;
    
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = SWIG_ObjectiveC_cast__p_ConcreteDerived1_to__p_AbstractBase(cptr);
        swigCPtr_ConcreteDerived1 = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_ConcreteDerived1();
        swigCPtr = SWIG_ObjectiveC_cast__p_ConcreteDerived1_to__p_AbstractBase(cptr);
        swigCPtr_ConcreteDerived1 = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}

-(void)f: (int)n
{
 _wrap_ConcreteDerived1_f([self swigCPtrForConcreteDerived1], n);
}


-(void)dealloc{

  if (swigCPtr_ConcreteDerived1 != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_ConcreteDerived1((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr_ConcreteDerived1 = NULL;
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation ConcreteDerived2
- (void*)getCptr {
	return [self swigCPtrForConcreteDerived2];
}

-(void*)swigCPtrForConcreteDerived2 {
	return swigCPtr_ConcreteDerived2;
}

-(void*)swigRelease {
	void *cptr = swigCPtr_ConcreteDerived2;
	swigCPtr_ConcreteDerived2 = NULL;
	swigCPtr = NULL;
    
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = SWIG_ObjectiveC_cast__p_ConcreteDerived2_to__p_AbstractBase(cptr);
        swigCPtr_ConcreteDerived2 = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_ConcreteDerived2();
        swigCPtr = SWIG_ObjectiveC_cast__p_ConcreteDerived2_to__p_AbstractBase(cptr);
        swigCPtr_ConcreteDerived2 = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}

-(void)f: (NSString *)another_representation_of_n
{
 _wrap_ConcreteDerived2_f([self swigCPtrForConcreteDerived2], another_representation_of_n);
}


-(void)dealloc{

  if (swigCPtr_ConcreteDerived2 != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_ConcreteDerived2((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr_ConcreteDerived2 = NULL;
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end

