/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
#include "abstract_virtual_proxy.h"
#include "abstract_virtual_wrap.h"


@implementation A
-(void*)getCptr {
	return [self swigCPtrForA];
}

-(void*)swigCPtrForA {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(int)foo
{
  return _wrap_A_foo([self swigCPtrForA]); 
}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_A((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation B
- (void*)getCptr {
	return [self swigCPtrForB];
}

-(void*)swigCPtrForB {
	return swigCPtr_B;
}

-(void*)swigRelease {
	void *cptr = swigCPtr_B;
	swigCPtr_B = NULL;
	swigCPtr = NULL;
    
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = SWIG_ObjectiveC_cast__p_B_to__p_A(cptr);
        swigCPtr_B = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(int)foo
{
  return _wrap_B_foo([self swigCPtrForB]); 
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_B();
        swigCPtr = SWIG_ObjectiveC_cast__p_B_to__p_A(cptr);
        swigCPtr_B = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr_B != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_B((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr_B = NULL;
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation C
- (void*)getCptr {
	return [self swigCPtrForC];
}

-(void*)swigCPtrForC {
	return swigCPtr_C;
}

-(void*)swigRelease {
	void *cptr = swigCPtr_C;
	swigCPtr_C = NULL;
	swigCPtr = NULL;
    
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = SWIG_ObjectiveC_cast__p_C_to__p_A(cptr);
        swigCPtr_C = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}


-(void)dealloc{

  if (swigCPtr_C != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_C((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr_C = NULL;
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation D
- (void*)getCptr {
	return [self swigCPtrForD];
}

-(void*)swigCPtrForD {
	return swigCPtr_D;
}

-(void*)swigRelease {
	void *cptr = swigCPtr_D;
	swigCPtr_D = NULL;
	swigCPtr_B = NULL;
    swigCPtr = NULL;
    
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr_B = SWIG_ObjectiveC_cast__p_D_to__p_B(cptr);
        swigCPtr = SWIG_ObjectiveC_cast__p_D_to__p_A(cptr);
        swigCPtr_D = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_D();
        swigCPtr_B = SWIG_ObjectiveC_cast__p_D_to__p_B(cptr);
        swigCPtr = SWIG_ObjectiveC_cast__p_D_to__p_A(cptr);
        swigCPtr_D = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}

-(C*)asC {
  void *cptr = SWIG_ObjectiveC_cast__p_D_to__p_C([self swigCPtrForD]);
  return cptr ? [[[C alloc] initWithCptr:cptr swigOwnCObject:NO] autorelease] : 0;
}


-(void)dealloc{

  if (swigCPtr_D != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_D((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr_D = NULL;
    swigCPtr_B = NULL;
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation E
- (void*)getCptr {
	return [self swigCPtrForE];
}

-(void*)swigCPtrForE {
	return swigCPtr_E;
}

-(void*)swigRelease {
	void *cptr = swigCPtr_E;
	swigCPtr_E = NULL;
	swigCPtr_C = NULL;
    swigCPtr = NULL;
    
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr_C = SWIG_ObjectiveC_cast__p_E_to__p_C(cptr);
        swigCPtr = SWIG_ObjectiveC_cast__p_E_to__p_A(cptr);
        swigCPtr_E = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_E();
        swigCPtr_C = SWIG_ObjectiveC_cast__p_E_to__p_C(cptr);
        swigCPtr = SWIG_ObjectiveC_cast__p_E_to__p_A(cptr);
        swigCPtr_E = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}

-(B*)asB {
  void *cptr = SWIG_ObjectiveC_cast__p_E_to__p_B([self swigCPtrForE]);
  return cptr ? [[[B alloc] initWithCptr:cptr swigOwnCObject:NO] autorelease] : 0;
}


-(void)dealloc{

  if (swigCPtr_E != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_E((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr_E = NULL;
    swigCPtr_C = NULL;
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end

