/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
#include "abstract_inherit_proxy.h"
#include "abstract_inherit_wrap.h"


@implementation Foo
-(void*)getCptr {
	return [self swigCPtrForFoo];
}

-(void*)swigCPtrForFoo {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(int)blah
{
  return _wrap_Foo_blah([self swigCPtrForFoo]); 
}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_Foo((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation Bar
- (void*)getCptr {
	return [self swigCPtrForBar];
}

-(void*)swigCPtrForBar {
	return swigCPtr_Bar;
}

-(void*)swigRelease {
	void *cptr = swigCPtr_Bar;
	swigCPtr_Bar = NULL;
	swigCPtr = NULL;
    
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = SWIG_ObjectiveC_cast__p_Bar_to__p_Foo(cptr);
        swigCPtr_Bar = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}


-(void)dealloc{

  if (swigCPtr_Bar != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_Bar((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr_Bar = NULL;
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation Spam
- (void*)getCptr {
	return [self swigCPtrForSpam];
}

-(void*)swigCPtrForSpam {
	return swigCPtr_Spam;
}

-(void*)swigRelease {
	void *cptr = swigCPtr_Spam;
	swigCPtr_Spam = NULL;
	swigCPtr = NULL;
    
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = SWIG_ObjectiveC_cast__p_Spam_to__p_Foo(cptr);
        swigCPtr_Spam = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}


-(void)dealloc{

  if (swigCPtr_Spam != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_Spam((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr_Spam = NULL;
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation NRFilter_i
-(void*)getCptr {
	return [self swigCPtrForNRFilter_i];
}

-(void*)swigCPtrForNRFilter_i {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_NRFilter_i((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation NRRCFilter_i
- (void*)getCptr {
	return [self swigCPtrForNRRCFilter_i];
}

-(void*)swigCPtrForNRRCFilter_i {
	return swigCPtr_NRRCFilter_i;
}

-(void*)swigRelease {
	void *cptr = swigCPtr_NRRCFilter_i;
	swigCPtr_NRRCFilter_i = NULL;
	swigCPtr = NULL;
    
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = SWIG_ObjectiveC_cast__p_NRRCFilterT_int_t_to__p_NRFilterT_int_t(cptr);
        swigCPtr_NRRCFilter_i = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}


-(void)dealloc{

  if (swigCPtr_NRRCFilter_i != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_NRRCFilter_i((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr_NRRCFilter_i = NULL;
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation NRRCFilterpro_i
-(void*)getCptr {
	return [self swigCPtrForNRRCFilterpro_i];
}

-(void*)swigCPtrForNRRCFilterpro_i {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_NRRCFilterpro_i((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation NRRCFilterpri_i
-(void*)getCptr {
	return [self swigCPtrForNRRCFilterpri_i];
}

-(void*)swigCPtrForNRRCFilterpri_i {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_NRRCFilterpri_i((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end

