/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


#define SWIG_VERSION 0x040500
#define SWIGOBJECTIVEC
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif

#if defined(__cplusplus) && __cplusplus >= 201103L
# define SWIG_NOEXCEPT noexcept
#else
# define SWIG_NOEXCEPT throw()
#endif 

#define SWIG_QUOTE_STRING(x) #x
#define SWIG_STRINGIFY(x) SWIG_QUOTE_STRING(x)

/* -----------------------------------------------------------------------------
 * swigcompat.swg
 *
 * Macros to provide support compatibility with older C and C++ standards.
 *
 * Note that SWIG expects __cplusplus to be defined to the appropriate C++ standard.
 * MSVC users are urged to check and examine the /Zc:__cplusplus compiler option.
 * See https://learn.microsoft.com/en-us/cpp/build/reference/zc-cplusplus.
 * ----------------------------------------------------------------------------- */

/* C99 and C++11 should provide snprintf, but define SWIG_NO_SNPRINTF
 * if you're missing it.
 */
#if ((defined __STDC_VERSION__ && __STDC_VERSION__ >= 199901L) || \
     (defined __cplusplus && __cplusplus >= 201103L) || \
     defined SWIG_HAVE_SNPRINTF) && \
    !defined SWIG_NO_SNPRINTF
# define SWIG_snprintf(O,S,F,A) snprintf(O,S,F,A)
# define SWIG_snprintf2(O,S,F,A,B) snprintf(O,S,F,A,B)
#else
/* Fallback versions ignore the buffer size, but most of our uses either have a
 * fixed maximum possible size or dynamically allocate a buffer that's large
 * enough.
 */
# define SWIG_snprintf(O,S,F,A) sprintf(O,F,A)
# define SWIG_snprintf2(O,S,F,A,B) sprintf(O,F,A,B)
#endif


#import <objc/NSObject.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#ifdef nil
#undef nil
#endif
#ifdef Nil
#undef Nil
#endif

#ifndef SWIG_OBJC_RUNTIME_DECLARATIONS
#define SWIG_OBJC_RUNTIME_DECLARATIONS
typedef unsigned long NSUInteger;
typedef unsigned short unichar;
struct objc_object;
typedef struct objc_object *SWIGObjectiveCId;
typedef struct objc_class *Class;
typedef struct objc_selector *SEL;
typedef struct objc_method *Method;
typedef void (*IMP)(void);

#ifdef __cplusplus
extern "C" {
#endif
Class objc_getClass(const char *name);
Class object_getClass(SWIGObjectiveCId obj);
Method class_getInstanceMethod(Class cls, SEL name);
IMP method_getImplementation(Method m);
id objc_msgSend(id self, SEL op, ...);
#ifdef __cplusplus
}
#endif

@interface NSString : NSObject
+ (id)stringWithUTF8String:(const char *)bytes;
+ (id)stringWithCharacters:(const unichar *)characters length:(NSUInteger)length;
- (const char *)UTF8String;
- (NSUInteger)length;
- (unichar)characterAtIndex:(NSUInteger)index;
- (BOOL)isEqualToString:(NSString *)aString;
@end

@interface NSArray : NSObject
- (NSUInteger)count;
- (id)objectAtIndex:(NSUInteger)index;
@end

@interface NSData : NSObject
+ (id)dataWithBytes:(const void *)bytes length:(NSUInteger)length;
- (const void *)bytes;
- (NSUInteger)length;
@end

@interface NSAutoreleasePool : NSObject
- (void)drain;
@end

@interface NSException : NSObject
+ (void)raise:(NSString *)name format:(NSString *)format, ...;
+ (id)exceptionWithName:(NSString *)name reason:(NSString *)reason userInfo:(id)userInfo;
@end

@protocol SWIGObjectiveCProxy
- (void *)getCptr;
- (id)initWithCptr:(void *)cptr swigOwnCObject:(BOOL)ownCObject;
@end

extern void NSLog(NSString *format, ...);
#endif

static id SWIG_ObjectiveC_NewProxy(const char *classname, void *cptr) {
  Class cls = classname ? objc_getClass(classname) : 0;
  if (!cptr || !cls)
    return 0;
  id proxy = [cls alloc];
  id initialized = [(id<SWIGObjectiveCProxy>)proxy initWithCptr:cptr swigOwnCObject:NO];
  return [initialized autorelease];
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) { /*throw exception*/ return nullreturn; } else


/* Support for throwing Objc exceptions */
typedef enum {
  SWIG_ObjcOutOfMemoryError = 1,
  SWIG_ObjcIOException,
  SWIG_ObjcRuntimeException,
  SWIG_ObjcIndexOutOfBoundsException,
  SWIG_ObjcArithmeticException,
  SWIG_ObjcIllegalArgumentException,
  SWIG_ObjcNullPointerException,
  SWIG_ObjcDirectorPureVirtual,
  SWIG_ObjcUnknownError
} SWIG_ObjcExceptionCodes;

typedef struct {
  SWIG_ObjcExceptionCodes code;
  const char *Objc_exception;
} SWIG_ObjcExceptions_t;

#define SWIG_exception(code, msg) SWIG_ObjcThrowException(code, msg)
#define SWIG_exception_fail(code, msg) do { SWIG_exception(code, msg); SWIG_fail; } while (0)


static void SWIGUNUSED SWIG_ObjcThrowException(int code, const char *msg) {
  static const SWIG_ObjcExceptions_t Objc_exceptions[] = {
    { SWIG_ObjcOutOfMemoryError, "OutOfMemoryError" },
    { SWIG_ObjcIOException, "IOException" },
    { SWIG_ObjcRuntimeException, "RuntimeException" },
    { SWIG_ObjcIndexOutOfBoundsException, "IndexOutOfBoundsException" },
    { SWIG_ObjcArithmeticException, "ArithmeticException" },
    { SWIG_ObjcIllegalArgumentException, "IllegalArgumentException" },
    { SWIG_ObjcNullPointerException, "NullPointerException" },
    { SWIG_ObjcDirectorPureVirtual, "RuntimeException" },
    { SWIG_ObjcUnknownError,  "UnknownError" },
    { (SWIG_ObjcExceptionCodes)0,  "UnknownError" }
  };
  const SWIG_ObjcExceptions_t *except_ptr = Objc_exceptions;
  while (except_ptr->code != code && except_ptr->code)
   except_ptr++;
  const char *type = except_ptr->Objc_exception;
  const char *reason = msg ? msg : "";
  NSException *exception = [NSException exceptionWithName:[NSString stringWithUTF8String:type]
                                                   reason:[NSString stringWithUTF8String:reason]
                                                 userInfo:0];
  @throw exception;
}


namespace Swig {
  class Director {
  public:
    virtual ~Director() {
    }
  };

  class DirectorException {
  public:
    DirectorException(const char *msg = "") : swig_msg(msg ? msg : "") {
    }
    virtual ~DirectorException() {
    }
    virtual const char *what() const {
      return swig_msg;
    }
    static void raise(const char *msg) {
      throw DirectorException(msg);
    }
  private:
    const char *swig_msg;
  };

  class DirectorPureVirtualException : public DirectorException {
  public:
    DirectorPureVirtualException(const char *msg = "") : DirectorException(msg) {
    }
    static void raise(const char *msg) {
      SWIG_ObjcThrowException(SWIG_ObjcDirectorPureVirtual, msg);
    }
  };
}



/* -----------------------------------------------------------------------------
 * swigrun.swg
 *
 * This file contains generic C API SWIG runtime support for pointer
 * type checking.
 * ----------------------------------------------------------------------------- */

/* This should only be incremented when either the layout of swig_type_info changes,
   or for whatever reason, the runtime changes incompatibly */
#define SWIG_RUNTIME_VERSION "5"

/* define SWIG_TYPE_TABLE_NAME as "SWIG_TYPE_TABLE" */
#ifdef SWIG_TYPE_TABLE
# define SWIG_TYPE_TABLE_NAME SWIG_STRINGIFY(SWIG_TYPE_TABLE)
#else
# define SWIG_TYPE_TABLE_NAME
#endif

/*
  You can use the SWIGRUNTIME and SWIGRUNTIMEINLINE macros for
  creating a static or dynamic library from the SWIG runtime code.
  In 99.9% of the cases, SWIG just needs to declare them as 'static'.

  But only do this if strictly necessary, ie, if you have problems
  with your compiler or suchlike.
*/

#ifndef SWIGRUNTIME
# define SWIGRUNTIME SWIGINTERN
#endif

#ifndef SWIGRUNTIMEINLINE
# define SWIGRUNTIMEINLINE SWIGRUNTIME SWIGINLINE
#endif

/*  Generic buffer size */
#ifndef SWIG_BUFFER_SIZE
# define SWIG_BUFFER_SIZE 1024
#endif

/* Flags for pointer conversions */
#define SWIG_POINTER_DISOWN        0x1
#define SWIG_CAST_NEW_MEMORY       0x2
#define SWIG_POINTER_NO_NULL       0x4
#define SWIG_POINTER_CLEAR         0x8
#define SWIG_POINTER_RELEASE       (SWIG_POINTER_CLEAR | SWIG_POINTER_DISOWN)

/* Flags for new pointer objects */
#define SWIG_POINTER_OWN           0x1


/*
   Flags/methods for returning states.

   The SWIG conversion methods, as ConvertPtr, return an integer
   that tells if the conversion was successful or not. And if not,
   an error code can be returned (see swigerrors.swg for the codes).

   Use the following macros/flags to set or process the returning
   states.

   In old versions of SWIG, code such as the following was usually written:

     if (SWIG_ConvertPtr(obj,vptr,ty.flags) != -1) {
       // success code
     } else {
       //fail code
     }

   Now you can be more explicit:

    int res = SWIG_ConvertPtr(obj,vptr,ty.flags);
    if (SWIG_IsOK(res)) {
      // success code
    } else {
      // fail code
    }

   which is the same really, but now you can also do

    Type *ptr;
    int res = SWIG_ConvertPtr(obj,(void **)(&ptr),ty.flags);
    if (SWIG_IsOK(res)) {
      // success code
      if (SWIG_IsNewObj(res) {
        ...
	delete *ptr;
      } else {
        ...
      }
    } else {
      // fail code
    }

   I.e., now SWIG_ConvertPtr can return new objects and you can
   identify the case and take care of the deallocation. Of course that
   also requires SWIG_ConvertPtr to return new result values, such as

      int SWIG_ConvertPtr(obj, ptr,...) {
        if (<obj is ok>) {
          if (<need new object>) {
            *ptr = <ptr to new allocated object>;
            return SWIG_NEWOBJ;
          } else {
            *ptr = <ptr to old object>;
            return SWIG_OLDOBJ;
          }
        } else {
          return SWIG_BADOBJ;
        }
      }

   Of course, returning the plain '0(success)/-1(fail)' still works, but you can be
   more explicit by returning SWIG_BADOBJ, SWIG_ERROR or any of the
   SWIG errors code.

   Finally, if the SWIG_CASTRANK_MODE is enabled, the result code
   allows returning the 'cast rank', for example, if you have this

       int food(double)
       int fooi(int);

   and you call

      food(1)   // cast rank '1'  (1 -> 1.0)
      fooi(1)   // cast rank '0'

   just use the SWIG_AddCast()/SWIG_CheckState()
*/

#define SWIG_OK                    (0)
/* Runtime errors are < 0 */
#define SWIG_ERROR                 (-1)
/* Errors in range -1 to -99 are in swigerrors.swg (errors for all languages including those not using the runtime) */
/* Errors in range -100 to -199 are language specific errors defined in *errors.swg */
/* Errors < -200 are generic runtime specific errors */
#define SWIG_ERROR_RELEASE_NOT_OWNED (-200)

#define SWIG_IsOK(r)               (r >= 0)
#define SWIG_ArgError(r)           ((r != SWIG_ERROR) ? r : SWIG_TypeError)

/* The CastRankLimit says how many bits are used for the cast rank */
#define SWIG_CASTRANKLIMIT         (1 << 8)
/* The NewMask denotes the object was created (using new/malloc) */
#define SWIG_NEWOBJMASK            (SWIG_CASTRANKLIMIT  << 1)
/* The TmpMask is for in/out typemaps that use temporary objects */
#define SWIG_TMPOBJMASK            (SWIG_NEWOBJMASK << 1)
/* Simple returning values */
#define SWIG_BADOBJ                (SWIG_ERROR)
#define SWIG_OLDOBJ                (SWIG_OK)
#define SWIG_NEWOBJ                (SWIG_OK | SWIG_NEWOBJMASK)
#define SWIG_TMPOBJ                (SWIG_OK | SWIG_TMPOBJMASK)
/* Check, add and del object mask methods */
#define SWIG_AddNewMask(r)         (SWIG_IsOK(r) ? (r | SWIG_NEWOBJMASK) : r)
#define SWIG_DelNewMask(r)         (SWIG_IsOK(r) ? (r & ~SWIG_NEWOBJMASK) : r)
#define SWIG_IsNewObj(r)           (SWIG_IsOK(r) && (r & SWIG_NEWOBJMASK))
#define SWIG_AddTmpMask(r)         (SWIG_IsOK(r) ? (r | SWIG_TMPOBJMASK) : r)
#define SWIG_DelTmpMask(r)         (SWIG_IsOK(r) ? (r & ~SWIG_TMPOBJMASK) : r)
#define SWIG_IsTmpObj(r)           (SWIG_IsOK(r) && (r & SWIG_TMPOBJMASK))

/* Cast-Rank Mode */
#if defined(SWIG_CASTRANK_MODE)
#  ifndef SWIG_TypeRank
#    define SWIG_TypeRank             unsigned long
#  endif
#  ifndef SWIG_MAXCASTRANK            /* Default cast allowed */
#    define SWIG_MAXCASTRANK          (2)
#  endif
#  define SWIG_CASTRANKMASK          ((SWIG_CASTRANKLIMIT) -1)
#  define SWIG_CastRank(r)           (r & SWIG_CASTRANKMASK)
SWIGINTERNINLINE int SWIG_AddCast(int r) {
  return SWIG_IsOK(r) ? ((SWIG_CastRank(r) < SWIG_MAXCASTRANK) ? (r + 1) : SWIG_ERROR) : r;
}
SWIGINTERNINLINE int SWIG_CheckState(int r) {
  return SWIG_IsOK(r) ? SWIG_CastRank(r) + 1 : 0;
}
#else /* no cast-rank mode */
#  define SWIG_AddCast(r) (r)
#  define SWIG_CheckState(r) (SWIG_IsOK(r) ? 1 : 0)
#endif


#include <string.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef void *(*swig_converter_func)(void *, int *);
typedef struct swig_type_info *(*swig_dycast_func)(void **);

/* Structure to store information on one type */
typedef struct swig_type_info {
  const char             *name;			/* mangled name of this type */
  const char             *str;			/* human readable name of this type */
  swig_dycast_func        dcast;		/* dynamic cast function down a hierarchy */
  struct swig_cast_info  *cast;			/* linked list of types that can cast into this type */
  void                   *clientdata;		/* language specific type data */
  int                    owndata;		/* flag if the structure owns the clientdata */
} swig_type_info;

/* Structure to store a type and conversion function used for casting */
typedef struct swig_cast_info {
  swig_type_info         *type;			/* pointer to type that is equivalent to this type */
  swig_converter_func     converter;		/* function to cast the void pointers */
  struct swig_cast_info  *next;			/* pointer to next array of casts | pointer to cast hashed by value */
  unsigned int            value;		/* index of the last valid element in the array | typename hash value */
} swig_cast_info;

/* Structure used to store module information
 * Each module generates one structure like this, and the runtime collects
 * all of these structures and stores them in a circularly linked list.*/
typedef struct swig_module_info {
  swig_type_info         **types;		/* Array of pointers to swig_type_info structures that are in this module */
  size_t                 size;		        /* Number of types in this module */
  struct swig_module_info *next;		/* Pointer to next element in circularly linked list */
  swig_type_info         **type_initial;	/* Array of initially generated type structures */
  swig_cast_info         **cast_initial;	/* Array of initially generated casting structures */
  void                    *clientdata;		/* Language specific module data */
} swig_module_info;

/*
  Compare two type names skipping the space characters, therefore
  "char*" == "char *" and "Class<int>" == "Class<int >", etc.

  Return 0 when the two name types are equivalent, as in
  strncmp, but skipping ' '.
*/
SWIGRUNTIME int
SWIG_TypeNameComp(const char *f1, const char *l1,
		  const char *f2, const char *l2) {
  for (;(f1 != l1) && (f2 != l2); ++f1, ++f2) {
    while ((*f1 == ' ') && (f1 != l1)) ++f1;
    while ((*f2 == ' ') && (f2 != l2)) ++f2;
    if (*f1 != *f2) return (*f1 > *f2) ? 1 : -1;
  }
  return (int)((l1 - f1) - (l2 - f2));
}

/*
  Check type equivalence in a name list like <name1>|<name2>|...
  Return 0 if equal, -1 if nb < tb, 1 if nb > tb
*/
SWIGRUNTIME int
SWIG_TypeCmp(const char *nb, const char *tb) {
  int equiv = 1;
  const char* te = tb + strlen(tb);
  const char* ne = nb;
  while (equiv != 0 && *ne) {
    for (nb = ne; *ne; ++ne) {
      if (*ne == '|') break;
    }
    equiv = SWIG_TypeNameComp(nb, ne, tb, te);
    if (*ne) ++ne;
  }
  return equiv;
}

/*
  Check type equivalence in a name list like <name1>|<name2>|...
  Return 0 if not equal, 1 if equal
*/
SWIGRUNTIME int
SWIG_TypeEquiv(const char *nb, const char *tb) {
  return SWIG_TypeCmp(nb, tb) == 0 ? 1 : 0;
}

/*
 * Hash function for type name strings, based on maRushPrime1Hash (http://amsoftware.narod.ru/algo2.html)
 */
SWIGRUNTIME unsigned int SWIG_Hash(const char *str, unsigned int len) {
  const unsigned char *data = (const unsigned char *)str;
  unsigned int hash = len, i = 0, k;
  int rem = (int)len;

  while (rem >= (int)sizeof(unsigned int)) {
    memcpy(&k, data, sizeof(unsigned int));
    k += i++;
    hash ^= k;
    hash *= 171717;
    data += sizeof(unsigned int);
    rem -= (int)sizeof(unsigned int);
  }

  switch (rem) {
    case 3: k = (unsigned int)(data[2]) << 16;
            k |= (unsigned int)(data[1]) << 8;
            k |= (unsigned int)(data[0]);
            k += i++;
            hash ^= k;
            hash *= 171717;
            break;
    case 2: k = (unsigned int)(data[1]) << 8;
            k |= (unsigned int)(data[0]);
            k += i++;
            hash ^= k;
            hash *= 171717;
            break;
    case 1: k = (unsigned int)(data[0]);
            k += i++;
            hash ^= k;
            hash *= 171717;
            break;
  }
  return hash;
}

/*
  Check the typename
*/
SWIGRUNTIME swig_cast_info *
SWIG_TypeCheck(const char *c, swig_type_info *ty) {
  static const unsigned int scan_threshold = 4;
  if (ty) {
    swig_cast_info *head = ty->cast;
    unsigned int hash_value = 0;
    int hashed = 0;

    while (head) {

      if (strcmp(head->type->name, c) == 0) {
        return head;
      }

      if (head->value) {
        swig_cast_info *iter;
        swig_cast_info *last = head + head->value;
        swig_cast_info *first = head + 1;
        int search = 1;

        if (!hashed) {
          if (head->value < scan_threshold) {
            for (iter = first; iter <= last; iter++) {
              if (strcmp(iter->type->name, c) == 0) {
                return iter;
              }
            }
            search = 0;
          } else {
            hashed = 1;
            hash_value = SWIG_Hash(c, (unsigned int)strlen(c));
          }
        }

        if (search) {
          /* Binary search over sorted <'next'|'value'> pairs */
          do {
            iter = first + ((last - first) >> 1);
            if (iter->value < hash_value) {
              first = iter + 1;
            } else if (iter->value == hash_value) {

              if (strcmp(iter->next->type->name, c) == 0) {
                return iter->next;
              }

              /* Hash collision check */
              for (last = iter + 1; last->next && last->value == hash_value; last++) {
                if (strcmp(last->next->type->name, c) == 0) {
                  return last->next;
                }
              }
              for (first = iter - 1; first != head && first->value == hash_value; first--) {
                if (strcmp(first->next->type->name, c) == 0) {
                  return first->next;
                }
              }
              break;
            } else
              last = iter - 1;
          } while (first <= last);
        }
      }
      head = head->next;
    }
  }
  return 0;
}

/*
  Check the type by type address
*/
SWIGRUNTIME swig_cast_info *
SWIG_TypeCheckStruct(const swig_type_info *from, swig_type_info *ty) {
  if (ty) {
    swig_cast_info *head = ty->cast;
    while (head) {
      if (head->type == from) {
        return head;
      }

      if (head->value) {
        swig_cast_info *iter;
        swig_cast_info *last = head + head->value;
        swig_cast_info *first = head + 1;

        /* Binary search over sorted array of casts */
        do {
          iter = first + ((last - first) >> 1);
          if (iter->type < from) {
            first = iter + 1;
          } else if (iter->type == from) {
            return iter;
          } else
            last = iter - 1;
        } while (first <= last);
      }
      head = head->next;
    }
  }
  return 0;
}

/*
  Cast a pointer up an inheritance hierarchy
*/
SWIGRUNTIMEINLINE void *
SWIG_TypeCast(swig_cast_info *ty, void *ptr, int *newmemory) {
  return ((!ty) || (!ty->converter)) ? ptr : (*ty->converter)(ptr, newmemory);
}

/*
   Dynamic pointer casting. Down an inheritance hierarchy
*/
SWIGRUNTIME swig_type_info *
SWIG_TypeDynamicCast(swig_type_info *ty, void **ptr) {
  swig_type_info *lastty = ty;
  if (!ty || !ty->dcast) return ty;
  while (ty && (ty->dcast)) {
    ty = (*ty->dcast)(ptr);
    if (ty) lastty = ty;
  }
  return lastty;
}

/*
  Return the name associated with this type
*/
SWIGRUNTIMEINLINE const char *
SWIG_TypeName(const swig_type_info *ty) {
  return ty->name;
}

/*
  Return the pretty name associated with this type,
  that is an unmangled type name in a form presentable to the user.
*/
SWIGRUNTIME const char *
SWIG_TypePrettyName(const swig_type_info *type) {
  /* The "str" field contains the equivalent pretty names of the
     type, separated by vertical-bar characters.  Choose the last
     name. It should be the most specific; a fully resolved name
     but not necessarily with default template parameters expanded. */
  if (!type) return NULL;
  if (type->str != NULL) {
    const char *last_name = type->str;
    const char *s;
    for (s = type->str; *s; s++)
      if (*s == '|') last_name = s+1;
    return last_name;
  }
  else
    return type->name;
}

/*
   Set the clientdata field for a type
*/
SWIGRUNTIME void
SWIG_TypeClientData(swig_type_info *ti, void *clientdata) {
  swig_cast_info *head = ti->cast;
  /* if (ti->clientdata == clientdata) return; */
  ti->clientdata = clientdata;

  while (head) {
    swig_cast_info *cast;
    for (cast = head; (unsigned int)(cast - head) <= head->value; cast++) {
      if (!cast->converter) {
        swig_type_info *tc = cast->type;
        if (!tc->clientdata) {
          SWIG_TypeClientData(tc, clientdata);
        }
      }
    }
    head = head->next;
  }
}

SWIGRUNTIME void
SWIG_TypeNewClientData(swig_type_info *ti, void *clientdata) {
  SWIG_TypeClientData(ti, clientdata);
  ti->owndata = 1;
}

/*
  Search for a swig_type_info structure only by mangled name
  Search is a O(log #types)

  We start searching at module start, and finish searching when start == end.
  Note: if start == end at the beginning of the function, we go all the way around
  the circular list.
*/
SWIGRUNTIME swig_type_info *
SWIG_MangledTypeQueryModule(swig_module_info *start,
                            swig_module_info *end,
		            const char *name) {
  swig_module_info *iter = start;
  do {
    if (iter->size) {
      size_t l = 0;
      size_t r = iter->size - 1;
      do {
	/* since l+r >= 0, we can (>> 1) instead (/ 2) */
	size_t i = (l + r) >> 1;
	const char *iname = iter->types[i]->name;
	if (iname) {
	  int compare = strcmp(name, iname);
	  if (compare == 0) {
	    return iter->types[i];
	  } else if (compare < 0) {
	    if (i) {
	      r = i - 1;
	    } else {
	      break;
	    }
	  } else if (compare > 0) {
	    l = i + 1;
	  }
	} else {
	  break; /* should never happen */
	}
      } while (l <= r);
    }
    iter = iter->next;
  } while (iter != end);
  return 0;
}

/*
  Search for a swig_type_info structure for either a mangled name or a human readable name.
  It first searches the mangled names of the types, which is a O(log #types)
  If a type is not found it then searches the human readable names, which is O(#types).

  We start searching at module start, and finish searching when start == end.
  Note: if start == end at the beginning of the function, we go all the way around
  the circular list.
*/
SWIGRUNTIME swig_type_info *
SWIG_TypeQueryModule(swig_module_info *start,
                     swig_module_info *end,
		     const char *name) {
  /* STEP 1: Search the name field using binary search */
  swig_type_info *ret = SWIG_MangledTypeQueryModule(start, end, name);
  if (ret) {
    return ret;
  } else {
    /* STEP 2: If the type hasn't been found, do a complete search
       of the str field (the human readable name) */
    swig_module_info *iter = start;
    do {
      size_t i = 0;
      for (; i < iter->size; ++i) {
	if (iter->types[i]->str && (SWIG_TypeEquiv(iter->types[i]->str, name)))
	  return iter->types[i];
      }
      iter = iter->next;
    } while (iter != end);
  }

  /* neither found a match */
  return 0;
}

/*
   Pack binary data into a string
*/
SWIGRUNTIME char *
SWIG_PackData(char *c, void *ptr, size_t sz) {
  static const char hex[17] = "0123456789abcdef";
  const unsigned char *u = (unsigned char *) ptr;
  const unsigned char *eu =  u + sz;
  for (; u != eu; ++u) {
    unsigned char uu = *u;
    *(c++) = hex[(uu & 0xf0) >> 4];
    *(c++) = hex[uu & 0xf];
  }
  return c;
}

/*
   Unpack binary data from a string
*/
SWIGRUNTIME const char *
SWIG_UnpackData(const char *c, void *ptr, size_t sz) {
  unsigned char *u = (unsigned char *) ptr;
  const unsigned char *eu = u + sz;
  for (; u != eu; ++u) {
    char d = *(c++);
    unsigned char uu;
    if ((d >= '0') && (d <= '9'))
      uu = (unsigned char)((d - '0') << 4);
    else if ((d >= 'a') && (d <= 'f'))
      uu = (unsigned char)((d - ('a'-10)) << 4);
    else
      return (char *) 0;
    d = *(c++);
    if ((d >= '0') && (d <= '9'))
      uu |= (unsigned char)(d - '0');
    else if ((d >= 'a') && (d <= 'f'))
      uu |= (unsigned char)(d - ('a'-10));
    else
      return (char *) 0;
    *u = uu;
  }
  return c;
}

/*
   Pack 'void *' into a string buffer.
*/
SWIGRUNTIME char *
SWIG_PackVoidPtr(char *buff, void *ptr, const char *name, size_t bsz) {
  char *r = buff;
  if ((2*sizeof(void *) + 2) > bsz) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,&ptr,sizeof(void *));
  if (strlen(name) + 1 > (bsz - (size_t)(r - buff))) return 0;
  strcpy(r,name);
  return buff;
}

SWIGRUNTIME const char *
SWIG_UnpackVoidPtr(const char *c, void **ptr, const char *name) {
  if (*c != '_') {
    if (strcmp(c,"NULL") == 0) {
      *ptr = (void *) 0;
      return name;
    } else {
      return 0;
    }
  }
  return SWIG_UnpackData(++c,ptr,sizeof(void *));
}

SWIGRUNTIME char *
SWIG_PackDataName(char *buff, void *ptr, size_t sz, const char *name, size_t bsz) {
  char *r = buff;
  size_t lname = (name ? strlen(name) : 0);
  if ((2*sz + 2 + lname) > bsz) return 0;
  *(r++) = '_';
  r = SWIG_PackData(r,ptr,sz);
  if (lname) {
    strncpy(r,name,lname+1);
  } else {
    *r = 0;
  }
  return buff;
}

SWIGRUNTIME const char *
SWIG_UnpackDataName(const char *c, void *ptr, size_t sz, const char *name) {
  if (*c != '_') {
    if (strcmp(c,"NULL") == 0) {
      memset(ptr,0,sz);
      return name;
    } else {
      return 0;
    }
  }
  return SWIG_UnpackData(++c,ptr,sz);
}

#ifdef __cplusplus
}
#endif

/* -------- TYPES TABLE (BEGIN) -------- */

static swig_type_info *swig_types[1];
static swig_module_info swig_module = {swig_types, 0, 0, 0, 0, 0};
#define SWIG_TypeQuery(name) SWIG_TypeQueryModule(&swig_module, &swig_module, name)
#define SWIG_MangledTypeQuery(name) SWIG_MangledTypeQueryModule(&swig_module, &swig_module, name)

/* -------- TYPES TABLE (END) -------- */

#include "class_scope_namespace_wrap.h"

#ifdef __cplusplus
#include <utility>
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigSmartPointer {
    T *ptr;
    SwigSmartPointer(T *p) : ptr(p) { }
    ~SwigSmartPointer() { delete ptr; }
    SwigSmartPointer& operator=(SwigSmartPointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
    void reset(T *p) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = p; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigSmartPointer tmp(new T(t)); pointer = tmp; return *this; }
#if __cplusplus >= 201103L
  SwigValueWrapper& operator=(T&& t) { SwigSmartPointer tmp(new T(std::move(t))); pointer = tmp; return *this; }
  operator T&&() const { return std::move(*pointer.ptr); }
#else
  operator T&() const { return *pointer.ptr; }
#endif
  T *operator&() const { return pointer.ptr; }
  static void reset(SwigValueWrapper& t, T *p) { t.pointer.reset(p); }
};

/*
 * SwigValueInit() is a generic initialisation solution as the following approach:
 * 
 *       T c_result = T();
 * 
 * doesn't compile for all types for example:
 * 
 *       unsigned int c_result = unsigned int();
 */
template <typename T> T SwigValueInit() {
  return T();
}

#if __cplusplus >= 201103L
# define SWIG_STD_MOVE(OBJ) std::move(OBJ)
#else
# define SWIG_STD_MOVE(OBJ) OBJ
#endif

#if __cplusplus >= 201103L
# define SWIG_OVERRIDE override
#else
# define SWIG_OVERRIDE
#endif

#endif


struct A;
namespace Space1 {
  namespace SubSpace1 {
    struct A {
      void aa(Space1::SubSpace1::A, SubSpace1::A, A) {}
    };
    void aaa(Space1::SubSpace1::A, SubSpace1::A, A) {}
  }
}
void global_namespace_a(A*) {}

namespace Space2 {
  struct B;
}
using Space2::B;
#ifdef __clang__
namespace Space2 {
  struct B {
    void bb(Space2::B, B) {}
  };
}
#else
struct B {
  void bb(Space2::B, B) {}
};
#endif
void bbb(Space2::B, B) {}

namespace Space3 {
  namespace SubSpace3 {
    struct C;
    struct D;
  }
}
struct C;
struct D;
namespace Space3 {
  struct C;
  struct SubSpace3::C {
    void cc(Space3::SubSpace3::C, SubSpace3::C) {}
  };
  using SubSpace3::D;
  struct SubSpace3::D {
    void dd(Space3::SubSpace3::D, SubSpace3::D, D) {}
  };
  void ccc(Space3::SubSpace3::C, SubSpace3::C) {}
  void ddd(Space3::SubSpace3::D, SubSpace3::D, D) {}
}

namespace Space4 {
  namespace SubSpace4 {
    struct E;
  }
}
using namespace Space4;
using SubSpace4::E;
// Was added to incorrect namespace in swig-3.0.12
struct SubSpace4::E {
  void ee(Space4::SubSpace4::E, SubSpace4::E, E) {}
};
void eee(Space4::SubSpace4::E, SubSpace4::E, E) {}

namespace Space5 {
  namespace SubSpace5 {
    namespace SubSubSpace5 {
      struct F;
    }
  }
}
namespace Space5 {
  using namespace SubSpace5;
  using SubSubSpace5::F;
  // Was added to incorrect namespace in swig-3.0.12
  struct SubSubSpace5::F {
    void ff(Space5::SubSpace5::SubSubSpace5::F, SubSpace5::SubSubSpace5::F, SubSubSpace5::F, F) {}
  };
  void fff(Space5::SubSpace5::SubSubSpace5::F, SubSpace5::SubSubSpace5::F, SubSubSpace5::F, F) {}
}

namespace Space6 {
  struct G;
  namespace SubSpace6 {
    struct G;
  }
}
namespace Space6 {
  struct SubSpace6::G {
    void gg(Space6::SubSpace6::G, SubSpace6::G) {}
  };
  void ggg(Space6::SubSpace6::G, SubSpace6::G) {}
}

struct HH;
struct H {
  struct HH {
    void hh(H::HH) {}
  };
};
void hhh(H::HH) {}

namespace Space8 {
  struct II;
  struct I_ {
    struct II {
      void ii(Space8::I_::II, I_::II) {}
    };
  };
  void iii(Space8::I_::II, I_::II) {}
}

struct J;
namespace Space9 {
  namespace SubSpace9 {
    struct J {
      void jj(Space9::SubSpace9::J, SubSpace9::J, J) {}
    };
    void jjj(Space9::SubSpace9::J, SubSpace9::J, J) {}
  }
}

namespace Space10 {
  struct K;
}
namespace Space10 {
  namespace SubSpace10 {
    struct K {
      void kk(Space10::SubSpace10::K, SubSpace10::K, K) {}
    };
    void kkk(Space10::SubSpace10::K, SubSpace10::K, K) {}
  }
}

namespace OtherSpace {
  struct L;
  struct M;
}
using OtherSpace::L;
namespace Space11 {
  using OtherSpace::M;
  namespace SubSpace11 {
    struct L {
      void ll(Space11::SubSpace11::L, SubSpace11::L, L) {}
    };
    void lll(Space11::SubSpace11::L, SubSpace11::L, L) {}
    struct M {
      void mm(Space11::SubSpace11::M, SubSpace11::M, M) {}
    };
    void mmm(Space11::SubSpace11::M, SubSpace11::M, M) {}
  }
}



#ifdef __cplusplus
extern "C" {
#endif


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (BEGIN) -------- */


static swig_type_info *swig_type_initial[] = {
  NULL
};


static swig_cast_info *swig_cast_initial[] = {
  NULL
};


/* -------- TYPE CONVERSION AND EQUIVALENCE RULES (END) -------- */

void _wrap_A_aa(void* imarg1, void* imarg2, void* imarg3, void* imarg4)
{
  Space1::SubSpace1::A *argp2 ;
  Space1::SubSpace1::A *argp3 ;
  Space1::SubSpace1::A *argp4 ;
  Space1::SubSpace1::A *arg1 = 0 ;
  Space1::SubSpace1::A arg2 ;
  Space1::SubSpace1::A arg3 ;
  Space1::SubSpace1::A arg4 ;
  Space1::SubSpace1::A *argp20 ;
  Space1::SubSpace1::A *argp30 ;
  Space1::SubSpace1::A *argp40 ;
  
  arg1 = (Space1::SubSpace1::A *)imarg1; 
  
  argp20 = (Space1::SubSpace1::A *)imarg2;
  arg2 = *argp20;
  
  
  argp30 = (Space1::SubSpace1::A *)imarg3;
  arg3 = *argp30;
  
  
  argp40 = (Space1::SubSpace1::A *)imarg4;
  arg4 = *argp40;
  
  (arg1)->aa(SWIG_STD_MOVE(*(&arg2)),SWIG_STD_MOVE(*(&arg3)),SWIG_STD_MOVE(*(&arg4)));
}

void* _wrap_new_A()
{
  void* imresult = 0 ;
  Space1::SubSpace1::A *result = 0 ;
  
  result = (Space1::SubSpace1::A *)new Space1::SubSpace1::A();
  
#ifdef __cplusplus
  imresult = (decltype(imresult))result;
#else
  imresult = (void*)result;
#endif
  
  return imresult;
}

void _wrap_delete_A(void* imarg1)
{
  Space1::SubSpace1::A *arg1 = 0 ;
  
  arg1 = (Space1::SubSpace1::A *)imarg1; 
  delete arg1;
}

void _wrap_aaa(void* imarg1, void* imarg2, void* imarg3)
{
  Space1::SubSpace1::A *argp1 ;
  Space1::SubSpace1::A *argp2 ;
  Space1::SubSpace1::A *argp3 ;
  Space1::SubSpace1::A arg1 ;
  Space1::SubSpace1::A arg2 ;
  Space1::SubSpace1::A arg3 ;
  Space1::SubSpace1::A *argp10 ;
  Space1::SubSpace1::A *argp20 ;
  Space1::SubSpace1::A *argp30 ;
  
  
  argp10 = (Space1::SubSpace1::A *)imarg1;
  arg1 = *argp10;
  
  
  argp20 = (Space1::SubSpace1::A *)imarg2;
  arg2 = *argp20;
  
  
  argp30 = (Space1::SubSpace1::A *)imarg3;
  arg3 = *argp30;
  
  Space1::SubSpace1::aaa(SWIG_STD_MOVE(*(&arg1)),SWIG_STD_MOVE(*(&arg2)),SWIG_STD_MOVE(*(&arg3)));
}

void _wrap_global_namespace_a(void* imarg1)
{
  A *arg1 = 0 ;
  
  arg1 = (A *)imarg1; 
  global_namespace_a(arg1);
}

void _wrap_B_bb(void* imarg1, void* imarg2, void* imarg3)
{
  Space2::B *argp2 ;
  Space2::B *argp3 ;
  Space2::B *arg1 = 0 ;
  Space2::B arg2 ;
  Space2::B arg3 ;
  Space2::B *argp20 ;
  Space2::B *argp30 ;
  
  arg1 = (Space2::B *)imarg1; 
  
  argp20 = (Space2::B *)imarg2;
  arg2 = *argp20;
  
  
  argp30 = (Space2::B *)imarg3;
  arg3 = *argp30;
  
  (arg1)->bb(SWIG_STD_MOVE(*(&arg2)),SWIG_STD_MOVE(*(&arg3)));
}

void* _wrap_new_B()
{
  void* imresult = 0 ;
  Space2::B *result = 0 ;
  
  result = (Space2::B *)new Space2::B();
  
#ifdef __cplusplus
  imresult = (decltype(imresult))result;
#else
  imresult = (void*)result;
#endif
  
  return imresult;
}

void _wrap_delete_B(void* imarg1)
{
  Space2::B *arg1 = 0 ;
  
  arg1 = (Space2::B *)imarg1; 
  delete arg1;
}

void _wrap_bbb(void* imarg1, void* imarg2)
{
  Space2::B *argp1 ;
  B *argp2 ;
  Space2::B arg1 ;
  B arg2 ;
  Space2::B *argp10 ;
  B *argp20 ;
  
  
  argp10 = (Space2::B *)imarg1;
  arg1 = *argp10;
  
  
  argp20 = (B *)imarg2;
  arg2 = *argp20;
  
  bbb(SWIG_STD_MOVE(*(&arg1)),SWIG_STD_MOVE(*(&arg2)));
}

void _wrap_C_cc(void* imarg1, void* imarg2, void* imarg3)
{
  Space3::SubSpace3::C *argp2 ;
  Space3::SubSpace3::C *argp3 ;
  Space3::SubSpace3::C *arg1 = 0 ;
  Space3::SubSpace3::C arg2 ;
  Space3::SubSpace3::C arg3 ;
  Space3::SubSpace3::C *argp20 ;
  Space3::SubSpace3::C *argp30 ;
  
  arg1 = (Space3::SubSpace3::C *)imarg1; 
  
  argp20 = (Space3::SubSpace3::C *)imarg2;
  arg2 = *argp20;
  
  
  argp30 = (Space3::SubSpace3::C *)imarg3;
  arg3 = *argp30;
  
  (arg1)->cc(SWIG_STD_MOVE(*(&arg2)),SWIG_STD_MOVE(*(&arg3)));
}

void* _wrap_new_C()
{
  void* imresult = 0 ;
  Space3::SubSpace3::C *result = 0 ;
  
  result = (Space3::SubSpace3::C *)new Space3::SubSpace3::C();
  
#ifdef __cplusplus
  imresult = (decltype(imresult))result;
#else
  imresult = (void*)result;
#endif
  
  return imresult;
}

void _wrap_delete_C(void* imarg1)
{
  Space3::SubSpace3::C *arg1 = 0 ;
  
  arg1 = (Space3::SubSpace3::C *)imarg1; 
  delete arg1;
}

void _wrap_D_dd(void* imarg1, void* imarg2, void* imarg3, void* imarg4)
{
  Space3::SubSpace3::D *argp2 ;
  Space3::SubSpace3::D *argp3 ;
  Space3::SubSpace3::D *argp4 ;
  Space3::SubSpace3::D *arg1 = 0 ;
  Space3::SubSpace3::D arg2 ;
  Space3::SubSpace3::D arg3 ;
  Space3::SubSpace3::D arg4 ;
  Space3::SubSpace3::D *argp20 ;
  Space3::SubSpace3::D *argp30 ;
  Space3::SubSpace3::D *argp40 ;
  
  arg1 = (Space3::SubSpace3::D *)imarg1; 
  
  argp20 = (Space3::SubSpace3::D *)imarg2;
  arg2 = *argp20;
  
  
  argp30 = (Space3::SubSpace3::D *)imarg3;
  arg3 = *argp30;
  
  
  argp40 = (Space3::SubSpace3::D *)imarg4;
  arg4 = *argp40;
  
  (arg1)->dd(SWIG_STD_MOVE(*(&arg2)),SWIG_STD_MOVE(*(&arg3)),SWIG_STD_MOVE(*(&arg4)));
}

void* _wrap_new_D()
{
  void* imresult = 0 ;
  Space3::SubSpace3::D *result = 0 ;
  
  result = (Space3::SubSpace3::D *)new Space3::SubSpace3::D();
  
#ifdef __cplusplus
  imresult = (decltype(imresult))result;
#else
  imresult = (void*)result;
#endif
  
  return imresult;
}

void _wrap_delete_D(void* imarg1)
{
  Space3::SubSpace3::D *arg1 = 0 ;
  
  arg1 = (Space3::SubSpace3::D *)imarg1; 
  delete arg1;
}

void _wrap_ccc(void* imarg1, void* imarg2)
{
  Space3::SubSpace3::C *argp1 ;
  Space3::SubSpace3::C *argp2 ;
  Space3::SubSpace3::C arg1 ;
  Space3::SubSpace3::C arg2 ;
  Space3::SubSpace3::C *argp10 ;
  Space3::SubSpace3::C *argp20 ;
  
  
  argp10 = (Space3::SubSpace3::C *)imarg1;
  arg1 = *argp10;
  
  
  argp20 = (Space3::SubSpace3::C *)imarg2;
  arg2 = *argp20;
  
  Space3::ccc(SWIG_STD_MOVE(*(&arg1)),SWIG_STD_MOVE(*(&arg2)));
}

void _wrap_ddd(void* imarg1, void* imarg2, void* imarg3)
{
  Space3::SubSpace3::D *argp1 ;
  Space3::SubSpace3::D *argp2 ;
  Space3::D *argp3 ;
  Space3::SubSpace3::D arg1 ;
  Space3::SubSpace3::D arg2 ;
  Space3::D arg3 ;
  Space3::SubSpace3::D *argp10 ;
  Space3::SubSpace3::D *argp20 ;
  Space3::D *argp30 ;
  
  
  argp10 = (Space3::SubSpace3::D *)imarg1;
  arg1 = *argp10;
  
  
  argp20 = (Space3::SubSpace3::D *)imarg2;
  arg2 = *argp20;
  
  
  argp30 = (Space3::D *)imarg3;
  arg3 = *argp30;
  
  Space3::ddd(SWIG_STD_MOVE(*(&arg1)),SWIG_STD_MOVE(*(&arg2)),SWIG_STD_MOVE(*(&arg3)));
}

void _wrap_E_ee(void* imarg1, void* imarg2, void* imarg3, void* imarg4)
{
  Space4::SubSpace4::E *argp2 ;
  Space4::SubSpace4::E *argp3 ;
  Space4::SubSpace4::E *argp4 ;
  Space4::SubSpace4::E *arg1 = 0 ;
  Space4::SubSpace4::E arg2 ;
  Space4::SubSpace4::E arg3 ;
  Space4::SubSpace4::E arg4 ;
  Space4::SubSpace4::E *argp20 ;
  Space4::SubSpace4::E *argp30 ;
  Space4::SubSpace4::E *argp40 ;
  
  arg1 = (Space4::SubSpace4::E *)imarg1; 
  
  argp20 = (Space4::SubSpace4::E *)imarg2;
  arg2 = *argp20;
  
  
  argp30 = (Space4::SubSpace4::E *)imarg3;
  arg3 = *argp30;
  
  
  argp40 = (Space4::SubSpace4::E *)imarg4;
  arg4 = *argp40;
  
  (arg1)->ee(SWIG_STD_MOVE(*(&arg2)),SWIG_STD_MOVE(*(&arg3)),SWIG_STD_MOVE(*(&arg4)));
}

void* _wrap_new_E()
{
  void* imresult = 0 ;
  Space4::SubSpace4::E *result = 0 ;
  
  result = (Space4::SubSpace4::E *)new Space4::SubSpace4::E();
  
#ifdef __cplusplus
  imresult = (decltype(imresult))result;
#else
  imresult = (void*)result;
#endif
  
  return imresult;
}

void _wrap_delete_E(void* imarg1)
{
  Space4::SubSpace4::E *arg1 = 0 ;
  
  arg1 = (Space4::SubSpace4::E *)imarg1; 
  delete arg1;
}

void _wrap_eee(void* imarg1, void* imarg2, void* imarg3)
{
  Space4::SubSpace4::E *argp1 ;
  Space4::SubSpace4::E *argp2 ;
  E *argp3 ;
  Space4::SubSpace4::E arg1 ;
  Space4::SubSpace4::E arg2 ;
  E arg3 ;
  Space4::SubSpace4::E *argp10 ;
  Space4::SubSpace4::E *argp20 ;
  E *argp30 ;
  
  
  argp10 = (Space4::SubSpace4::E *)imarg1;
  arg1 = *argp10;
  
  
  argp20 = (Space4::SubSpace4::E *)imarg2;
  arg2 = *argp20;
  
  
  argp30 = (E *)imarg3;
  arg3 = *argp30;
  
  eee(SWIG_STD_MOVE(*(&arg1)),SWIG_STD_MOVE(*(&arg2)),SWIG_STD_MOVE(*(&arg3)));
}

void _wrap_F_ff(void* imarg1, void* imarg2, void* imarg3, void* imarg4, void* imarg5)
{
  Space5::SubSpace5::SubSubSpace5::F *argp2 ;
  Space5::SubSpace5::SubSubSpace5::F *argp3 ;
  Space5::SubSpace5::SubSubSpace5::F *argp4 ;
  Space5::SubSpace5::SubSubSpace5::F *argp5 ;
  Space5::SubSpace5::SubSubSpace5::F *arg1 = 0 ;
  Space5::SubSpace5::SubSubSpace5::F arg2 ;
  Space5::SubSpace5::SubSubSpace5::F arg3 ;
  Space5::SubSpace5::SubSubSpace5::F arg4 ;
  Space5::SubSpace5::SubSubSpace5::F arg5 ;
  Space5::SubSpace5::SubSubSpace5::F *argp20 ;
  Space5::SubSpace5::SubSubSpace5::F *argp30 ;
  Space5::SubSpace5::SubSubSpace5::F *argp40 ;
  Space5::SubSpace5::SubSubSpace5::F *argp50 ;
  
  arg1 = (Space5::SubSpace5::SubSubSpace5::F *)imarg1; 
  
  argp20 = (Space5::SubSpace5::SubSubSpace5::F *)imarg2;
  arg2 = *argp20;
  
  
  argp30 = (Space5::SubSpace5::SubSubSpace5::F *)imarg3;
  arg3 = *argp30;
  
  
  argp40 = (Space5::SubSpace5::SubSubSpace5::F *)imarg4;
  arg4 = *argp40;
  
  
  argp50 = (Space5::SubSpace5::SubSubSpace5::F *)imarg5;
  arg5 = *argp50;
  
  (arg1)->ff(SWIG_STD_MOVE(*(&arg2)),SWIG_STD_MOVE(*(&arg3)),SWIG_STD_MOVE(*(&arg4)),SWIG_STD_MOVE(*(&arg5)));
}

void* _wrap_new_F()
{
  void* imresult = 0 ;
  Space5::SubSpace5::SubSubSpace5::F *result = 0 ;
  
  result = (Space5::SubSpace5::SubSubSpace5::F *)new Space5::SubSpace5::SubSubSpace5::F();
  
#ifdef __cplusplus
  imresult = (decltype(imresult))result;
#else
  imresult = (void*)result;
#endif
  
  return imresult;
}

void _wrap_delete_F(void* imarg1)
{
  Space5::SubSpace5::SubSubSpace5::F *arg1 = 0 ;
  
  arg1 = (Space5::SubSpace5::SubSubSpace5::F *)imarg1; 
  delete arg1;
}

void _wrap_fff(void* imarg1, void* imarg2, void* imarg3, void* imarg4)
{
  Space5::SubSpace5::SubSubSpace5::F *argp1 ;
  Space5::SubSpace5::SubSubSpace5::F *argp2 ;
  Space5::SubSpace5::SubSubSpace5::F *argp3 ;
  Space5::F *argp4 ;
  Space5::SubSpace5::SubSubSpace5::F arg1 ;
  Space5::SubSpace5::SubSubSpace5::F arg2 ;
  Space5::SubSpace5::SubSubSpace5::F arg3 ;
  Space5::F arg4 ;
  Space5::SubSpace5::SubSubSpace5::F *argp10 ;
  Space5::SubSpace5::SubSubSpace5::F *argp20 ;
  Space5::SubSpace5::SubSubSpace5::F *argp30 ;
  Space5::F *argp40 ;
  
  
  argp10 = (Space5::SubSpace5::SubSubSpace5::F *)imarg1;
  arg1 = *argp10;
  
  
  argp20 = (Space5::SubSpace5::SubSubSpace5::F *)imarg2;
  arg2 = *argp20;
  
  
  argp30 = (Space5::SubSpace5::SubSubSpace5::F *)imarg3;
  arg3 = *argp30;
  
  
  argp40 = (Space5::F *)imarg4;
  arg4 = *argp40;
  
  Space5::fff(SWIG_STD_MOVE(*(&arg1)),SWIG_STD_MOVE(*(&arg2)),SWIG_STD_MOVE(*(&arg3)),SWIG_STD_MOVE(*(&arg4)));
}

void _wrap_G_gg(void* imarg1, void* imarg2, void* imarg3)
{
  Space6::SubSpace6::G *argp2 ;
  Space6::SubSpace6::G *argp3 ;
  Space6::SubSpace6::G *arg1 = 0 ;
  Space6::SubSpace6::G arg2 ;
  Space6::SubSpace6::G arg3 ;
  Space6::SubSpace6::G *argp20 ;
  Space6::SubSpace6::G *argp30 ;
  
  arg1 = (Space6::SubSpace6::G *)imarg1; 
  
  argp20 = (Space6::SubSpace6::G *)imarg2;
  arg2 = *argp20;
  
  
  argp30 = (Space6::SubSpace6::G *)imarg3;
  arg3 = *argp30;
  
  (arg1)->gg(SWIG_STD_MOVE(*(&arg2)),SWIG_STD_MOVE(*(&arg3)));
}

void* _wrap_new_G()
{
  void* imresult = 0 ;
  Space6::SubSpace6::G *result = 0 ;
  
  result = (Space6::SubSpace6::G *)new Space6::SubSpace6::G();
  
#ifdef __cplusplus
  imresult = (decltype(imresult))result;
#else
  imresult = (void*)result;
#endif
  
  return imresult;
}

void _wrap_delete_G(void* imarg1)
{
  Space6::SubSpace6::G *arg1 = 0 ;
  
  arg1 = (Space6::SubSpace6::G *)imarg1; 
  delete arg1;
}

void _wrap_ggg(void* imarg1, void* imarg2)
{
  Space6::SubSpace6::G *argp1 ;
  Space6::SubSpace6::G *argp2 ;
  Space6::SubSpace6::G arg1 ;
  Space6::SubSpace6::G arg2 ;
  Space6::SubSpace6::G *argp10 ;
  Space6::SubSpace6::G *argp20 ;
  
  
  argp10 = (Space6::SubSpace6::G *)imarg1;
  arg1 = *argp10;
  
  
  argp20 = (Space6::SubSpace6::G *)imarg2;
  arg2 = *argp20;
  
  Space6::ggg(SWIG_STD_MOVE(*(&arg1)),SWIG_STD_MOVE(*(&arg2)));
}

void* _wrap_new_H()
{
  void* imresult = 0 ;
  H *result = 0 ;
  
  result = (H *)new H();
  
#ifdef __cplusplus
  imresult = (decltype(imresult))result;
#else
  imresult = (void*)result;
#endif
  
  return imresult;
}

void _wrap_delete_H(void* imarg1)
{
  H *arg1 = 0 ;
  
  arg1 = (H *)imarg1; 
  delete arg1;
}

void _wrap_hhh(void* imarg1)
{
  H::HH *argp1 ;
  H::HH arg1 ;
  H::HH *argp10 ;
  
  
  argp10 = (H::HH *)imarg1;
  arg1 = *argp10;
  
  hhh(SWIG_STD_MOVE(*(&arg1)));
}

void* _wrap_new_I_()
{
  void* imresult = 0 ;
  Space8::I_ *result = 0 ;
  
  result = (Space8::I_ *)new Space8::I_();
  
#ifdef __cplusplus
  imresult = (decltype(imresult))result;
#else
  imresult = (void*)result;
#endif
  
  return imresult;
}

void _wrap_delete_I_(void* imarg1)
{
  Space8::I_ *arg1 = 0 ;
  
  arg1 = (Space8::I_ *)imarg1; 
  delete arg1;
}

void _wrap_iii(void* imarg1, void* imarg2)
{
  Space8::I_::II *argp1 ;
  Space8::I_::II *argp2 ;
  Space8::I_::II arg1 ;
  Space8::I_::II arg2 ;
  Space8::I_::II *argp10 ;
  Space8::I_::II *argp20 ;
  
  
  argp10 = (Space8::I_::II *)imarg1;
  arg1 = *argp10;
  
  
  argp20 = (Space8::I_::II *)imarg2;
  arg2 = *argp20;
  
  Space8::iii(SWIG_STD_MOVE(*(&arg1)),SWIG_STD_MOVE(*(&arg2)));
}

void _wrap_J_jj(void* imarg1, void* imarg2, void* imarg3, void* imarg4)
{
  Space9::SubSpace9::J *argp2 ;
  Space9::SubSpace9::J *argp3 ;
  Space9::SubSpace9::J *argp4 ;
  Space9::SubSpace9::J *arg1 = 0 ;
  Space9::SubSpace9::J arg2 ;
  Space9::SubSpace9::J arg3 ;
  Space9::SubSpace9::J arg4 ;
  Space9::SubSpace9::J *argp20 ;
  Space9::SubSpace9::J *argp30 ;
  Space9::SubSpace9::J *argp40 ;
  
  arg1 = (Space9::SubSpace9::J *)imarg1; 
  
  argp20 = (Space9::SubSpace9::J *)imarg2;
  arg2 = *argp20;
  
  
  argp30 = (Space9::SubSpace9::J *)imarg3;
  arg3 = *argp30;
  
  
  argp40 = (Space9::SubSpace9::J *)imarg4;
  arg4 = *argp40;
  
  (arg1)->jj(SWIG_STD_MOVE(*(&arg2)),SWIG_STD_MOVE(*(&arg3)),SWIG_STD_MOVE(*(&arg4)));
}

void* _wrap_new_J()
{
  void* imresult = 0 ;
  Space9::SubSpace9::J *result = 0 ;
  
  result = (Space9::SubSpace9::J *)new Space9::SubSpace9::J();
  
#ifdef __cplusplus
  imresult = (decltype(imresult))result;
#else
  imresult = (void*)result;
#endif
  
  return imresult;
}

void _wrap_delete_J(void* imarg1)
{
  Space9::SubSpace9::J *arg1 = 0 ;
  
  arg1 = (Space9::SubSpace9::J *)imarg1; 
  delete arg1;
}

void _wrap_jjj(void* imarg1, void* imarg2, void* imarg3)
{
  Space9::SubSpace9::J *argp1 ;
  Space9::SubSpace9::J *argp2 ;
  Space9::SubSpace9::J *argp3 ;
  Space9::SubSpace9::J arg1 ;
  Space9::SubSpace9::J arg2 ;
  Space9::SubSpace9::J arg3 ;
  Space9::SubSpace9::J *argp10 ;
  Space9::SubSpace9::J *argp20 ;
  Space9::SubSpace9::J *argp30 ;
  
  
  argp10 = (Space9::SubSpace9::J *)imarg1;
  arg1 = *argp10;
  
  
  argp20 = (Space9::SubSpace9::J *)imarg2;
  arg2 = *argp20;
  
  
  argp30 = (Space9::SubSpace9::J *)imarg3;
  arg3 = *argp30;
  
  Space9::SubSpace9::jjj(SWIG_STD_MOVE(*(&arg1)),SWIG_STD_MOVE(*(&arg2)),SWIG_STD_MOVE(*(&arg3)));
}

void _wrap_K_kk(void* imarg1, void* imarg2, void* imarg3, void* imarg4)
{
  Space10::SubSpace10::K *argp2 ;
  Space10::SubSpace10::K *argp3 ;
  Space10::SubSpace10::K *argp4 ;
  Space10::SubSpace10::K *arg1 = 0 ;
  Space10::SubSpace10::K arg2 ;
  Space10::SubSpace10::K arg3 ;
  Space10::SubSpace10::K arg4 ;
  Space10::SubSpace10::K *argp20 ;
  Space10::SubSpace10::K *argp30 ;
  Space10::SubSpace10::K *argp40 ;
  
  arg1 = (Space10::SubSpace10::K *)imarg1; 
  
  argp20 = (Space10::SubSpace10::K *)imarg2;
  arg2 = *argp20;
  
  
  argp30 = (Space10::SubSpace10::K *)imarg3;
  arg3 = *argp30;
  
  
  argp40 = (Space10::SubSpace10::K *)imarg4;
  arg4 = *argp40;
  
  (arg1)->kk(SWIG_STD_MOVE(*(&arg2)),SWIG_STD_MOVE(*(&arg3)),SWIG_STD_MOVE(*(&arg4)));
}

void* _wrap_new_K()
{
  void* imresult = 0 ;
  Space10::SubSpace10::K *result = 0 ;
  
  result = (Space10::SubSpace10::K *)new Space10::SubSpace10::K();
  
#ifdef __cplusplus
  imresult = (decltype(imresult))result;
#else
  imresult = (void*)result;
#endif
  
  return imresult;
}

void _wrap_delete_K(void* imarg1)
{
  Space10::SubSpace10::K *arg1 = 0 ;
  
  arg1 = (Space10::SubSpace10::K *)imarg1; 
  delete arg1;
}

void _wrap_kkk(void* imarg1, void* imarg2, void* imarg3)
{
  Space10::SubSpace10::K *argp1 ;
  Space10::SubSpace10::K *argp2 ;
  Space10::SubSpace10::K *argp3 ;
  Space10::SubSpace10::K arg1 ;
  Space10::SubSpace10::K arg2 ;
  Space10::SubSpace10::K arg3 ;
  Space10::SubSpace10::K *argp10 ;
  Space10::SubSpace10::K *argp20 ;
  Space10::SubSpace10::K *argp30 ;
  
  
  argp10 = (Space10::SubSpace10::K *)imarg1;
  arg1 = *argp10;
  
  
  argp20 = (Space10::SubSpace10::K *)imarg2;
  arg2 = *argp20;
  
  
  argp30 = (Space10::SubSpace10::K *)imarg3;
  arg3 = *argp30;
  
  Space10::SubSpace10::kkk(SWIG_STD_MOVE(*(&arg1)),SWIG_STD_MOVE(*(&arg2)),SWIG_STD_MOVE(*(&arg3)));
}

void _wrap_L_ll(void* imarg1, void* imarg2, void* imarg3, void* imarg4)
{
  Space11::SubSpace11::L *argp2 ;
  Space11::SubSpace11::L *argp3 ;
  Space11::SubSpace11::L *argp4 ;
  Space11::SubSpace11::L *arg1 = 0 ;
  Space11::SubSpace11::L arg2 ;
  Space11::SubSpace11::L arg3 ;
  Space11::SubSpace11::L arg4 ;
  Space11::SubSpace11::L *argp20 ;
  Space11::SubSpace11::L *argp30 ;
  Space11::SubSpace11::L *argp40 ;
  
  arg1 = (Space11::SubSpace11::L *)imarg1; 
  
  argp20 = (Space11::SubSpace11::L *)imarg2;
  arg2 = *argp20;
  
  
  argp30 = (Space11::SubSpace11::L *)imarg3;
  arg3 = *argp30;
  
  
  argp40 = (Space11::SubSpace11::L *)imarg4;
  arg4 = *argp40;
  
  (arg1)->ll(SWIG_STD_MOVE(*(&arg2)),SWIG_STD_MOVE(*(&arg3)),SWIG_STD_MOVE(*(&arg4)));
}

void* _wrap_new_L()
{
  void* imresult = 0 ;
  Space11::SubSpace11::L *result = 0 ;
  
  result = (Space11::SubSpace11::L *)new Space11::SubSpace11::L();
  
#ifdef __cplusplus
  imresult = (decltype(imresult))result;
#else
  imresult = (void*)result;
#endif
  
  return imresult;
}

void _wrap_delete_L(void* imarg1)
{
  Space11::SubSpace11::L *arg1 = 0 ;
  
  arg1 = (Space11::SubSpace11::L *)imarg1; 
  delete arg1;
}

void _wrap_lll(void* imarg1, void* imarg2, void* imarg3)
{
  Space11::SubSpace11::L *argp1 ;
  Space11::SubSpace11::L *argp2 ;
  Space11::SubSpace11::L *argp3 ;
  Space11::SubSpace11::L arg1 ;
  Space11::SubSpace11::L arg2 ;
  Space11::SubSpace11::L arg3 ;
  Space11::SubSpace11::L *argp10 ;
  Space11::SubSpace11::L *argp20 ;
  Space11::SubSpace11::L *argp30 ;
  
  
  argp10 = (Space11::SubSpace11::L *)imarg1;
  arg1 = *argp10;
  
  
  argp20 = (Space11::SubSpace11::L *)imarg2;
  arg2 = *argp20;
  
  
  argp30 = (Space11::SubSpace11::L *)imarg3;
  arg3 = *argp30;
  
  Space11::SubSpace11::lll(SWIG_STD_MOVE(*(&arg1)),SWIG_STD_MOVE(*(&arg2)),SWIG_STD_MOVE(*(&arg3)));
}

void _wrap_M_mm(void* imarg1, void* imarg2, void* imarg3, void* imarg4)
{
  Space11::SubSpace11::M *argp2 ;
  Space11::SubSpace11::M *argp3 ;
  Space11::SubSpace11::M *argp4 ;
  Space11::SubSpace11::M *arg1 = 0 ;
  Space11::SubSpace11::M arg2 ;
  Space11::SubSpace11::M arg3 ;
  Space11::SubSpace11::M arg4 ;
  Space11::SubSpace11::M *argp20 ;
  Space11::SubSpace11::M *argp30 ;
  Space11::SubSpace11::M *argp40 ;
  
  arg1 = (Space11::SubSpace11::M *)imarg1; 
  
  argp20 = (Space11::SubSpace11::M *)imarg2;
  arg2 = *argp20;
  
  
  argp30 = (Space11::SubSpace11::M *)imarg3;
  arg3 = *argp30;
  
  
  argp40 = (Space11::SubSpace11::M *)imarg4;
  arg4 = *argp40;
  
  (arg1)->mm(SWIG_STD_MOVE(*(&arg2)),SWIG_STD_MOVE(*(&arg3)),SWIG_STD_MOVE(*(&arg4)));
}

void* _wrap_new_M()
{
  void* imresult = 0 ;
  Space11::SubSpace11::M *result = 0 ;
  
  result = (Space11::SubSpace11::M *)new Space11::SubSpace11::M();
  
#ifdef __cplusplus
  imresult = (decltype(imresult))result;
#else
  imresult = (void*)result;
#endif
  
  return imresult;
}

void _wrap_delete_M(void* imarg1)
{
  Space11::SubSpace11::M *arg1 = 0 ;
  
  arg1 = (Space11::SubSpace11::M *)imarg1; 
  delete arg1;
}

void _wrap_mmm(void* imarg1, void* imarg2, void* imarg3)
{
  Space11::SubSpace11::M *argp1 ;
  Space11::SubSpace11::M *argp2 ;
  Space11::SubSpace11::M *argp3 ;
  Space11::SubSpace11::M arg1 ;
  Space11::SubSpace11::M arg2 ;
  Space11::SubSpace11::M arg3 ;
  Space11::SubSpace11::M *argp10 ;
  Space11::SubSpace11::M *argp20 ;
  Space11::SubSpace11::M *argp30 ;
  
  
  argp10 = (Space11::SubSpace11::M *)imarg1;
  arg1 = *argp10;
  
  
  argp20 = (Space11::SubSpace11::M *)imarg2;
  arg2 = *argp20;
  
  
  argp30 = (Space11::SubSpace11::M *)imarg3;
  arg3 = *argp30;
  
  Space11::SubSpace11::mmm(SWIG_STD_MOVE(*(&arg1)),SWIG_STD_MOVE(*(&arg2)),SWIG_STD_MOVE(*(&arg3)));
}


#ifdef __cplusplus
}
#endif
