/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#import <objc/NSObject.h>

#ifndef SWIG_OBJC_RUNTIME_DECLARATIONS
#define SWIG_OBJC_RUNTIME_DECLARATIONS
typedef unsigned long NSUInteger;
typedef unsigned short unichar;
struct objc_object;
typedef struct objc_object *SWIGObjectiveCId;
#endif

@class NSString;
@class NSArray;
@class NSMutableArray;
@class NSData;
@class NSAutoreleasePool;
@class NSException;

#ifdef __cplusplus
extern "C" {
#endif
extern void NSLog(NSString *format, ...);
#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif

@class ParametersTest;
@class MemberVariablesTest;
@class ReturnValuesTest;
@class B;
@class Foo;
@class SWIGTYPE_p_int;
@class SWIGTYPE_A;
@class SWIGTYPE_p_p_B;
@class SWIGTYPE_p_p_int;
@class SWIGTYPE_p_p_char;
@class SWIGTYPE_p_p_ParametersTest;
@class SWIGTYPE_p_A;

@interface SWIGTYPE_p_int : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForSWIGTYPE_p_int;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

@end

@interface SWIGTYPE_A : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForSWIGTYPE_A;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

@end

@interface SWIGTYPE_p_p_B : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForSWIGTYPE_p_p_B;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

@end

@interface SWIGTYPE_p_p_int : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForSWIGTYPE_p_p_int;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

@end

@interface SWIGTYPE_p_p_char : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForSWIGTYPE_p_p_char;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

@end

@interface SWIGTYPE_p_p_ParametersTest : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForSWIGTYPE_p_p_ParametersTest;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

@end

@interface SWIGTYPE_p_A : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForSWIGTYPE_p_A;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

@end

void setGlobalInt(int value);
int getGlobalInt();
int getConstInt();
void setGlobalIntPtr(int * value);
int * getGlobalIntPtr();
int * getGlobalConstIntPtr();
extern int ARRAY_SIZE;
@interface ParametersTest : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForParametersTest;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(void)param1: (int *)a;
-(void)param2: (int *)a;
-(void)param3: (int *)a;
-(void)param4: (int)a;
-(void)param5: (int)a;
-(void)param6: (int *)a;
-(void)param7: (int *)a;
-(void)param8: (int *)a;
-(void)param9: (SWIGTYPE_p_p_int*)a;
-(void)param10: (SWIGTYPE_p_p_int*)a;
-(void)param11: (int *)a;
-(void)param_array1: (SWIGTYPE_p_p_int*)a;
-(void)param_array2: (SWIGTYPE_p_p_int*)a;
-(void)param_array3: (SWIGTYPE_p_p_int*)a;
-(void)param_array4: (SWIGTYPE_p_int*)a;
-(void)param_array5: (SWIGTYPE_p_int*)a;
-(void)param_array6: (SWIGTYPE_p_p_int*)a;
-(id)init;

-(void)dealloc;

@end

@interface MemberVariablesTest : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForMemberVariablesTest;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(void)setMember1: (int *)value;
-(int *)getMember1;
-(void)setMember2: (ParametersTest*)value;
-(ParametersTest*)getMember2;
-(int *)getMember3;
-(ParametersTest*)getMember4;
-(void)setArray_member1: (SWIGTYPE_p_p_int*)value;
-(SWIGTYPE_p_p_int*)getArray_member1;
-(void)setArray_member2: (SWIGTYPE_p_p_ParametersTest*)value;
-(SWIGTYPE_p_p_ParametersTest*)getArray_member2;
-(id)init;

-(void)dealloc;

@end

void ObjcFoofunction(int * i);
void setInt1(int value);
int getInt1();
void setInt2(int value);
int getInt2();
void setInt3(int * value);
int * getInt3();
int * getInt4();
SWIGTYPE_p_p_int* getGlobal_const_int_ptr_array();
SWIGTYPE_p_p_ParametersTest* getArray_member4();
@interface ReturnValuesTest : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForReturnValuesTest;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(void)setTd1: (int *)value;
-(int *)getTd1;
-(void)setTd2: (int)value;
-(int)getTd2;
-(void)setInt1: (int)value;
-(int)getInt1;
-(void)setInt2: (int)value;
-(int)getInt2;
-(int *)getInt3;
-(void)setInt4: (int *)value;
-(int *)getInt4;
-(void)setArray1: (SWIGTYPE_p_int*)value;
-(SWIGTYPE_p_int*)getArray1;
-(int)ret1;
-(int)ret2;
-(int)ret3;
-(int *)ret4;
-(int *)ret5;
-(void)ret6: (SWIGTYPE_p_p_int*)a;
-(SWIGTYPE_p_p_int*)ret7;
-(void)ret8: (SWIGTYPE_p_p_int*)a;
-(SWIGTYPE_p_p_int*)ret9;
-(id)init;

-(void)dealloc;

@end

int * ObjcGlobalRet1();
int * ObjcGlobalRet2();
SWIGTYPE_p_A* ObjcOpaque(SWIGTYPE_p_A* aptr);
@interface B : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForB;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;
-(SWIGTYPE_A*)getCa;
-(void)setA: (SWIGTYPE_A*)value;
-(SWIGTYPE_A*)getA;
-(void)setAp: (SWIGTYPE_p_A*)value;
-(SWIGTYPE_p_A*)getAp;
-(void)setCap: (SWIGTYPE_p_A*)value;
-(SWIGTYPE_p_A*)getCap;
-(void)setAcptr: (SWIGTYPE_p_A*)value;
-(SWIGTYPE_p_A*)getAcptr;

-(void)dealloc;

@end

B* ObjcBar(B* b);
SWIGTYPE_p_p_B* ObjcCbar(SWIGTYPE_p_p_B* b);
void setWxEVENT_COMMAND_BUTTON_CLICKEDr(int * value);
int * getWxEVENT_COMMAND_BUTTON_CLICKEDr();
void setWxEVENT_COMMAND_BUTTON_CLICKEDp(int * value);
int * getWxEVENT_COMMAND_BUTTON_CLICKEDp();
void setLanguages1(SWIGTYPE_p_p_char* value);
SWIGTYPE_p_p_char* getLanguages1();
void setLanguages2(SWIGTYPE_p_p_char* value);
SWIGTYPE_p_p_char* getLanguages2();
@interface Foo : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForFoo;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(void)setIcap: (int *)value;
-(int *)getIcap;
-(id)init;

-(void)dealloc;

@end

void setIcap(int * value);
int * getIcap();
void setCap(Foo* value);
Foo* getCap();

#ifdef __cplusplus
}
#endif

