/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
#include "curiously_recurring_template_pattern_proxy.h"
#include "curiously_recurring_template_pattern_wrap.h"


@implementation basederived
-(void*)getCptr {
	return [self swigCPtrForbasederived];
}

-(void*)swigCPtrForbasederived {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_basederived();
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}

-(int)getBase1Param
{
  return _wrap_basederived_getBase1Param([self swigCPtrForbasederived]); 
}

-(Derived*)setBase1Param: (int)value
{
    void* cPtr = _wrap_basederived_setBase1Param([self swigCPtrForbasederived], value);
     Derived* ret = 0;
     if(cPtr) {
        ret = [[[Derived alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

-(int)getBase2Param
{
  return _wrap_basederived_getBase2Param([self swigCPtrForbasederived]); 
}

-(Derived*)setBase2Param: (int)value
{
    void* cPtr = _wrap_basederived_setBase2Param([self swigCPtrForbasederived], value);
     Derived* ret = 0;
     if(cPtr) {
        ret = [[[Derived alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_basederived((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation Derived
- (void*)getCptr {
	return [self swigCPtrForDerived];
}

-(void*)swigCPtrForDerived {
	return swigCPtr_Derived;
}

-(void*)swigRelease {
	void *cptr = swigCPtr_Derived;
	swigCPtr_Derived = NULL;
	swigCPtr = NULL;
    
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = SWIG_ObjectiveC_cast__p_Derived_to__p_BaseT_Derived_t(cptr);
        swigCPtr_Derived = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_Derived();
        swigCPtr = SWIG_ObjectiveC_cast__p_Derived_to__p_BaseT_Derived_t(cptr);
        swigCPtr_Derived = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}

-(int)getDerived1Param
{
  return _wrap_Derived_getDerived1Param([self swigCPtrForDerived]); 
}

-(Derived*)setDerived1Param: (int)value
{
    void* cPtr = _wrap_Derived_setDerived1Param([self swigCPtrForDerived], value);
     Derived* ret = 0;
     if(cPtr) {
        ret = [[[Derived alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

-(int)getDerived2Param
{
  return _wrap_Derived_getDerived2Param([self swigCPtrForDerived]); 
}

-(Derived*)setDerived2Param: (int)value
{
    void* cPtr = _wrap_Derived_setDerived2Param([self swigCPtrForDerived], value);
     Derived* ret = 0;
     if(cPtr) {
        ret = [[[Derived alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}


-(void)dealloc{

  if (swigCPtr_Derived != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_Derived((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr_Derived = NULL;
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end

