/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
#include "director_unroll_proxy.h"
#include "director_unroll_wrap.h"


@implementation Foo
-(void*)getCptr {
	return [self swigCPtrForFoo];
}

-(void*)swigCPtrForFoo {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(NSString*)ping
{
 {
    return _wrap_Foo_ping([self swigCPtrForFoo]);
  }
}

-(NSString*)pong
{
 {
    return _wrap_Foo_pong([self swigCPtrForFoo]);
  }
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_Foo();
        swigCPtr = cptr;
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_Foo((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation Bar
-(void*)getCptr {
	return [self swigCPtrForBar];
}

-(void*)swigCPtrForBar {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(void)set: (Foo*)x
{
 _wrap_Bar_set([self swigCPtrForBar], [x getCptr]);
}

-(Foo*)get
{
    void* cPtr = _wrap_Bar_get([self swigCPtrForBar]);
     Foo* ret = 0;
     if(cPtr) {
        ret = [[[Foo alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_Bar();
        swigCPtr = cptr;
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_Bar((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end

