/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
#include "director_basic_proxy.h"
#include "director_basic_wrap.h"


@implementation SWIGTYPE_std__complexT_double_t
-(void*)getCptr {
	return [self swigCPtrForSWIGTYPE_std__complexT_double_t];
}

-(void*)swigCPtrForSWIGTYPE_std__complexT_double_t {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

@end


@implementation SWIGTYPE_p_void
-(void*)getCptr {
	return [self swigCPtrForSWIGTYPE_p_void];
}

-(void*)swigCPtrForSWIGTYPE_p_void {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

@end


@implementation Foo
-(void*)getCptr {
	return [self swigCPtrForFoo];
}

-(void*)swigCPtrForFoo {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(NSString*)ping
{
 {
    return _wrap_Foo_ping([self swigCPtrForFoo]);
  }
}

-(NSString*)pong
{
 {
    return _wrap_Foo_pong([self swigCPtrForFoo]);
  }
}

+(Foo*)get_self: (Foo*)slf
{
    void* cPtr = _wrap_Foo_get_self([slf getCptr]);
     Foo* ret = 0;
     if(cPtr) {
        ret = [[[Foo alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_Foo();
        swigCPtr = cptr;
        _wrap_Foo_director_connect(cptr, self);
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_Foo((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation A
-(void*)getCptr {
	return [self swigCPtrForA];
}

-(void*)swigCPtrForA {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(id)initWithI: (SWIGTYPE_std__complexT_double_t*)i d: (double)d
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_A([i getCptr], d);
        swigCPtr = cptr;
        _wrap_A_director_connect(cptr, self);
        
        swigCMemOwn = YES;
	}
	return self;

}

-(int)f: (int)i
{
  return _wrap_A_f([self swigCPtrForA], i); 
}

-(int)rg: (int)i
{
  return _wrap_A_rg([self swigCPtrForA], i); 
}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_A((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation A1
- (void*)getCptr {
	return [self swigCPtrForA1];
}

-(void*)swigCPtrForA1 {
	return swigCPtr_A1;
}

-(void*)swigRelease {
	void *cptr = swigCPtr_A1;
	swigCPtr_A1 = NULL;
	swigCPtr = NULL;
    
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = SWIG_ObjectiveC_cast__p_hi__A1_to__p_A(cptr);
        swigCPtr_A1 = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(id)initWithI: (SWIGTYPE_std__complexT_double_t*)i d: (double)d
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_A1([i getCptr], d);
        swigCPtr = SWIG_ObjectiveC_cast__p_hi__A1_to__p_A(cptr);
        swigCPtr_A1 = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}

-(int)ff: (int)i
{
  return _wrap_A1_ff([self swigCPtrForA1], i); 
}


-(void)dealloc{

  if (swigCPtr_A1 != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_A1((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr_A1 = NULL;
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation Bar
-(void*)getCptr {
	return [self swigCPtrForBar];
}

-(void*)swigCPtrForBar {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(void)setX: (int)value
{
 _wrap_Bar_x_set([self swigCPtrForBar], value);
}

-(int)getX
{
  return _wrap_Bar_x_get([self swigCPtrForBar]); 
}

-(id)initWith_x: (int)_x
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_Bar(_x);
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_Bar((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation MyClass
-(void*)getCptr {
	return [self swigCPtrForMyClass];
}

-(void*)swigCPtrForMyClass {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(id)initWithA: (int)a
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_MyClass(a);
        swigCPtr = cptr;
        _wrap_MyClass_director_connect(cptr, self);
        
        swigCMemOwn = YES;
	}
	return self;

}

-(void)method: (SWIGTYPE_p_void*)arg0
{
 _wrap_MyClass_method([self swigCPtrForMyClass], [arg0 getCptr]);
}

-(Bar*)vmethod: (Bar*)b
{
    void* cPtr = _wrap_MyClass_vmethod([self swigCPtrForMyClass], [b getCptr]);
     Bar* ret = 0;
     if(cPtr) {
        ret = [[[Bar alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

-(Bar*)pmethod: (Bar*)b
{
    void* cPtr = _wrap_MyClass_pmethod([self swigCPtrForMyClass], [b getCptr]);
     Bar* ret = 0;
     if(cPtr) {
        ret = [[[Bar alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

-(Bar*)cmethod: (Bar*)b
{
    void* cPtr = _wrap_MyClass_cmethod([self swigCPtrForMyClass], [b getCptr]);
     Bar* ret = 0;
     if(cPtr) {
        ret = [[[Bar alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

+(MyClass*)get_self: (MyClass*)c
{
    void* cPtr = _wrap_MyClass_get_self([c getCptr]);
     MyClass* ret = 0;
     if(cPtr) {
        ret = [[[MyClass alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

+(Bar*)call_pmethod: (MyClass*)myclass b: (Bar*)b
{
    void* cPtr = _wrap_MyClass_call_pmethod([myclass getCptr], [b getCptr]);
     Bar* ret = 0;
     if(cPtr) {
        ret = [[[Bar alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

-(int)nonVirtual
{
  return _wrap_MyClass_nonVirtual([self swigCPtrForMyClass]); 
}

-(int)nonOverride
{
  return _wrap_MyClass_nonOverride([self swigCPtrForMyClass]); 
}

+(int)call_nonVirtual: (MyClass*)myclass
{
  return _wrap_MyClass_call_nonVirtual([myclass getCptr]); 
}

+(int)call_nonOverride: (MyClass*)myclass
{
  return _wrap_MyClass_call_nonOverride([myclass getCptr]); 
}

-(void)Connect
{
 _wrap_MyClass_Connect([self swigCPtrForMyClass]);
}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_MyClass((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation MyClassT_i
-(void*)getCptr {
	return [self swigCPtrForMyClassT_i];
}

-(void*)swigCPtrForMyClassT_i {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(id)initWithA: (int)a
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_MyClassT_i(a);
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}

-(void)method: (SWIGTYPE_p_void*)arg1
{
 _wrap_MyClassT_i_method([self swigCPtrForMyClassT_i], [arg1 getCptr]);
}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_MyClassT_i((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation ConstPtrClass
-(void*)getCptr {
	return [self swigCPtrForConstPtrClass];
}

-(void*)swigCPtrForConstPtrClass {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(int *)getConstPtr
{
  return _wrap_ConstPtrClass_getConstPtr([self swigCPtrForConstPtrClass]); 
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_ConstPtrClass();
        swigCPtr = cptr;
        _wrap_ConstPtrClass_director_connect(cptr, self);
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_ConstPtrClass((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end

