/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
#include "director_thread_proxy.h"
#include "director_thread_wrap.h"

void ObjcMilliSecondSleep(int milliseconds)
{
 _wrap_MilliSecondSleep(milliseconds);
}


@implementation Foo
-(void*)getCptr {
	return [self swigCPtrForFoo];
}

-(void*)swigCPtrForFoo {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(void)setVal: (int)value
{
 _wrap_Foo_val_set([self swigCPtrForFoo], value);
}

-(int)getVal
{
  return _wrap_Foo_val_get([self swigCPtrForFoo]); 
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_Foo();
        swigCPtr = cptr;
        swigCMemOwn = YES;
	}
	return self;

}

-(void)stop
{
 _wrap_Foo_stop([self swigCPtrForFoo]);
}

-(void)run
{
 _wrap_Foo_run([self swigCPtrForFoo]);
}

-(void)setThreadName
{
 _wrap_Foo_setThreadName([self swigCPtrForFoo]);
}

+(BOOL)namedThread
{
  return _wrap_Foo_namedThread(); 
}

-(void)do_foo
{
 _wrap_Foo_do_foo([self swigCPtrForFoo]);
}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_Foo((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end

