/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#import <objc/NSObject.h>
#import <objc/runtime.h>
#import <objc/message.h>

#ifdef nil
#undef nil
#endif
#ifdef Nil
#undef Nil
#endif

@class NSString;
@class NSArray;
@class NSMutableArray;
@class NSData;
@class NSAutoreleasePool;
@class NSException;

#ifndef DIRECTOR_REF_WRAP_H
#define DIRECTOR_REF_WRAP_H


#ifdef __cplusplus
extern "C" {
#endif

void _wrap_Foo_director_connect(void* imarg1, void* imarg2);
void* _wrap_new_Foo(int imarg1);
void _wrap_Foo_OnDelete(void* imarg1);
void _wrap_delete_Foo(void* imarg1);
NSString* _wrap_Foo_Msg(void* imarg1, NSString* imarg2);
NSString* _wrap_Foo_GetMsg(void* imarg1);
void _wrap_Foo_Ref(void* imarg1);
void _wrap_Foo_Unref(void* imarg1);
int _wrap_Foo_GetRefCount(void* imarg1);
void* _wrap_new_FooPtr(void* imarg1);
void _wrap_delete_FooPtr(void* imarg1);
void _wrap_FooPtr_Reset(void* imarg1, void* imarg2);
int _wrap_FooPtr_GetOwnedRefCount(void* imarg1);

#ifdef __cplusplus
}
#endif

#endif

