/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#import <objc/NSObject.h>
#import <objc/runtime.h>
#import <objc/message.h>

#ifdef nil
#undef nil
#endif
#ifdef Nil
#undef Nil
#endif

@class NSString;
@class NSArray;
@class NSMutableArray;
@class NSData;
@class NSAutoreleasePool;
@class NSException;

#ifndef DIRECTOR_CONVERSION_OPERATORS_WRAP_H
#define DIRECTOR_CONVERSION_OPERATORS_WRAP_H


#ifdef __cplusplus
extern "C" {
#endif

void* _wrap_new_Foo();
void _wrap_delete_Foo(void* imarg1);
void* _wrap_new_OtherFoo();
void _wrap_delete_OtherFoo(void* imarg1);
void _wrap_Bar_director_connect(void* imarg1, void* imarg2);
void _wrap_Bar_myFoo_set(void* imarg1, void* imarg2);
void* _wrap_Bar_myFoo_get(void* imarg1);
void _wrap_Bar_myFooPtr_set(void* imarg1, void* imarg2);
void* _wrap_Bar_myFooPtr_get(void* imarg1);
void _wrap_delete_Bar(void* imarg1);
void* _wrap_Bar_toFoo(void* imarg1);
void* _wrap_Bar_toFooPtr(void* imarg1);
void* _wrap_Bar_toFooRef(void* imarg1);
void* _wrap_Bar_toFooPtrRef(void* imarg1);
void* _wrap_Bar_toOtherFoo(void* imarg1);
void* _wrap_Bar_toOtherFooPtr(void* imarg1);
void* _wrap_Bar_toOtherFooRef(void* imarg1);
void* _wrap_Bar_toOtherFooPtrRef(void* imarg1);
void* _wrap_new_Bar();

#ifdef __cplusplus
}
#endif

#endif

