/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#import <objc/NSObject.h>

@class NSString;
@class NSArray;
@class NSMutableArray;
@class NSData;
@class NSAutoreleasePool;
@class NSException;
extern void NSLog(NSString *format, ...);


#ifdef __cplusplus
extern "C" {
#endif

@class Base;
@class Bar;

@interface Base : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForBase;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;

-(void)dealloc;

@end

@interface Bar : Base
{
	void *swigCPtr_Bar;
}
-(void*)getCptr;
-(void*)swigCPtrForBar;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(NSString*)pang;
-(id)init;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

