/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#import <objc/NSObject.h>

@class NSString;
@class NSArray;
@class NSMutableArray;
@class NSData;
@class NSAutoreleasePool;
@class NSException;
extern void NSLog(NSString *format, ...);


#ifdef __cplusplus
extern "C" {
#endif

@class Foo_int;
@class Bar;
@class FooBar_int;
@class SomeBase;
@class PrivateDerived;

@interface Foo_int : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForFoo_int;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(NSString*)advance;

-(void)dealloc;

@end

@interface Bar : Foo_int
{
	void *swigCPtr_Bar;
}
-(void*)getCptr;
-(void*)swigCPtrForBar;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(NSString*)step;
-(NSString*)do_step;

-(void)dealloc;

@end

@interface FooBar_int : Bar
{
	void *swigCPtr_FooBar_int;
}
-(void*)getCptr;
-(void*)swigCPtrForFooBar_int;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(int)get_value;
-(NSString*)do_advance;

-(void)dealloc;

@end

@interface SomeBase : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForSomeBase;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(void)method1;
-(void)method2;
-(id)init;

-(void)dealloc;

@end

@interface PrivateDerived : SomeBase
{
	void *swigCPtr_PrivateDerived;
}
-(void*)getCptr;
-(void*)swigCPtrForPrivateDerived;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

