/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#import <objc/NSObject.h>
#import <objc/runtime.h>
#import <objc/message.h>

#ifdef nil
#undef nil
#endif
#ifdef Nil
#undef Nil
#endif

@class NSString;
@class NSArray;
@class NSMutableArray;
@class NSData;
@class NSAutoreleasePool;
@class NSException;

#ifndef DIRECTOR_WOMBAT_WRAP_H
#define DIRECTOR_WOMBAT_WRAP_H


#ifdef __cplusplus
extern "C" {
#endif

void _wrap_Bar_director_connect(void* imarg1, void* imarg2);
void _wrap_delete_Bar(void* imarg1);
void* _wrap_Bar_meth(void* imarg1);
void _wrap_Bar_foo_meth_ref(void* imarg1, void* imarg2, int imarg3);
void _wrap_Bar_foo_meth_ptr(void* imarg1, void* imarg2, int imarg3);
void _wrap_Bar_foo_meth_val(void* imarg1, void* imarg2, int imarg3);
void _wrap_Bar_foo_meth_cref(void* imarg1, void* imarg2, int imarg3);
void _wrap_Bar_foo_meth_cptr(void* imarg1, void* imarg2, int imarg3);
void* _wrap_new_Bar();
void _wrap_Foo_integers_director_connect(void* imarg1, void* imarg2);
void* _wrap_new_Foo_integers();
void _wrap_delete_Foo_integers(void* imarg1);
int _wrap_Foo_integers_meth(void* imarg1, int imarg2);

#ifdef __cplusplus
}
#endif

#endif

