/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
#include "duplicate_class_name_in_ns_proxy.h"
#include "duplicate_class_name_in_ns_wrap.h"


@implementation XA
-(void*)getCptr {
	return [self swigCPtrForXA];
}

-(void*)swigCPtrForXA {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_XA();
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_XA((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation Bar
-(void*)getCptr {
	return [self swigCPtrForBar];
}

-(void*)swigCPtrForBar {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_Bar();
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_Bar((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation XB
- (void*)getCptr {
	return [self swigCPtrForXB];
}

-(void*)swigCPtrForXB {
	return swigCPtr_XB;
}

-(void*)swigRelease {
	void *cptr = swigCPtr_XB;
	swigCPtr_XB = NULL;
	swigCPtr = NULL;
    
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = SWIG_ObjectiveC_cast__p_B__X_to__p_A__X(cptr);
        swigCPtr_XB = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_XB();
        swigCPtr = SWIG_ObjectiveC_cast__p_B__X_to__p_A__X(cptr);
        swigCPtr_XB = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}

-(XA*)do_x
{
    void* cPtr = _wrap_XB_do_x([self swigCPtrForXB]);
     XA* ret = 0;
     if(cPtr) {
        ret = [[[XA alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}


-(void)dealloc{

  if (swigCPtr_XB != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_XB((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr_XB = NULL;
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation AFoo
-(void*)getCptr {
	return [self swigCPtrForAFoo];
}

-(void*)swigCPtrForAFoo {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_AFoo();
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_AFoo((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation ABaz
-(void*)getCptr {
	return [self swigCPtrForABaz];
}

-(void*)swigCPtrForABaz {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_ABaz();
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_ABaz((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation BFoo
- (void*)getCptr {
	return [self swigCPtrForBFoo];
}

-(void*)swigCPtrForBFoo {
	return swigCPtr_BFoo;
}

-(void*)swigRelease {
	void *cptr = swigCPtr_BFoo;
	swigCPtr_BFoo = NULL;
	swigCPtr = NULL;
    
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = SWIG_ObjectiveC_cast__p_B__FooT_int_double_t_to__p_A__FooT_double_t(cptr);
        swigCPtr_BFoo = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_BFoo();
        swigCPtr = SWIG_ObjectiveC_cast__p_B__FooT_int_double_t_to__p_A__FooT_double_t(cptr);
        swigCPtr_BFoo = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}

-(AFoo*)do_foo
{
    void* cPtr = _wrap_BFoo_do_foo([self swigCPtrForBFoo]);
     AFoo* ret = 0;
     if(cPtr) {
        ret = [[[AFoo alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}


-(void)dealloc{

  if (swigCPtr_BFoo != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_BFoo((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr_BFoo = NULL;
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation BBar
- (void*)getCptr {
	return [self swigCPtrForBBar];
}

-(void*)swigCPtrForBBar {
	return swigCPtr_BBar;
}

-(void*)swigRelease {
	void *cptr = swigCPtr_BBar;
	swigCPtr_BBar = NULL;
	swigCPtr = NULL;
    
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = SWIG_ObjectiveC_cast__p_B__BarT_int_double_t_to__p_A__Bar(cptr);
        swigCPtr_BBar = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_BBar();
        swigCPtr = SWIG_ObjectiveC_cast__p_B__BarT_int_double_t_to__p_A__Bar(cptr);
        swigCPtr_BBar = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}

-(Bar*)do_bar
{
    void* cPtr = _wrap_BBar_do_bar([self swigCPtrForBBar]);
     Bar* ret = 0;
     if(cPtr) {
        ret = [[[Bar alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}


-(void)dealloc{

  if (swigCPtr_BBar != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_BBar((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr_BBar = NULL;
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation BBaz
- (void*)getCptr {
	return [self swigCPtrForBBaz];
}

-(void*)swigCPtrForBBaz {
	return swigCPtr_BBaz;
}

-(void*)swigRelease {
	void *cptr = swigCPtr_BBaz;
	swigCPtr_BBaz = NULL;
	swigCPtr = NULL;
    
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = SWIG_ObjectiveC_cast__p_B__BazT_double_t_to__p_A__BazT_double_t(cptr);
        swigCPtr_BBaz = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_BBaz();
        swigCPtr = SWIG_ObjectiveC_cast__p_B__BazT_double_t_to__p_A__BazT_double_t(cptr);
        swigCPtr_BBaz = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}

-(ABaz*)do_baz
{
    void* cPtr = _wrap_BBaz_do_baz([self swigCPtrForBBaz]);
     ABaz* ret = 0;
     if(cPtr) {
        ret = [[[ABaz alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}


-(void)dealloc{

  if (swigCPtr_BBaz != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_BBaz((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr_BBaz = NULL;
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end

XA* ObjcGet_a_x()
{
    void* cPtr = _wrap_get_a_x();
     XA* ret = 0;
     if(cPtr) {
        ret = [[[XA alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

AFoo* ObjcGet_a_foo()
{
    void* cPtr = _wrap_get_a_foo();
     AFoo* ret = 0;
     if(cPtr) {
        ret = [[[AFoo alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

Bar* ObjcGet_a_bar()
{
    void* cPtr = _wrap_get_a_bar();
     Bar* ret = 0;
     if(cPtr) {
        ret = [[[Bar alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

ABaz* ObjcGet_a_baz()
{
    void* cPtr = _wrap_get_a_baz();
     ABaz* ret = 0;
     if(cPtr) {
        ret = [[[ABaz alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

