/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#import <objc/NSObject.h>

#ifndef SWIG_OBJC_RUNTIME_DECLARATIONS
#define SWIG_OBJC_RUNTIME_DECLARATIONS
typedef unsigned long NSUInteger;
typedef unsigned short unichar;
struct objc_object;
typedef struct objc_object *SWIGObjectiveCId;
#endif

@class NSString;
@class NSArray;
@class NSMutableArray;
@class NSData;
@class NSAutoreleasePool;
@class NSException;

#ifdef __cplusplus
extern "C" {
#endif
extern void NSLog(NSString *format, ...);
#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif

@class Foo;
@class iFoo;
@class SWIGTYPE_p_ContainYourself;

@interface SWIGTYPE_p_ContainYourself : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForSWIGTYPE_p_ContainYourself;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

@end

enum foo1 {
  CSP_ITERATION_FWD,
  CSP_ITERATION_BWD = 11
};

enum foo3 {
  ABCDE = 0,
  FGHJI = 1
};

enum sad {
  boo,
  hoo = 5
};


enum {
  globalinstance1,
  globalinstance2,
  globalinstance3 = 30
};


enum {
  AnonEnum1,
  AnonEnum2 = 100
};


enum {
  Foo_BAR1,
  Foo_BAR2
};


enum {
  iFoo_Phoo = +50,
  iFoo_Char = 'a'
};

enum Exclamation {
  goodness,
  gracious,
  me
};

enum ContainYourself {
  slap = 10,
  mine,
  thigh
};

void ObjcBar1(enum foo1 x);
void ObjcBar2(enum foo3 x);
void ObjcBar3(enum foo3 x);
void setGlobalInstance(int value);
int getGlobalInstance();
@interface Foo : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForFoo;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(void)setE: (int)value;
-(int)getE;
-(id)init;

-(void)dealloc;

@end

@interface iFoo : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForiFoo;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(void)setE: (int)value;
-(int)getE;
-(id)init;

-(void)dealloc;

@end

void setEnumInstance(enum Exclamation value);
enum Exclamation getEnumInstance();
void setSlap(enum ContainYourself value);
enum ContainYourself getSlap();
void setMine(enum ContainYourself value);
enum ContainYourself getMine();
void setThigh(enum ContainYourself value);
enum ContainYourself getThigh();
void setPThigh(SWIGTYPE_p_ContainYourself* value);
SWIGTYPE_p_ContainYourself* getPThigh();
void setArrayContainYourself(SWIGTYPE_p_ContainYourself* value);
SWIGTYPE_p_ContainYourself* getArrayContainYourself();

#ifdef __cplusplus
}
#endif

