/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#import <objc/NSObject.h>

#ifndef SWIG_OBJC_RUNTIME_DECLARATIONS
#define SWIG_OBJC_RUNTIME_DECLARATIONS
typedef unsigned long NSUInteger;
typedef unsigned short unichar;
struct objc_object;
typedef struct objc_object *SWIGObjectiveCId;
#endif

@class NSString;
@class NSArray;
@class NSMutableArray;
@class NSData;
@class NSAutoreleasePool;
@class NSException;

#ifdef __cplusplus
extern "C" {
#endif
extern void NSLog(NSString *format, ...);
#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif

@class Klass1;
@class Klass2;
@class Klass3;
@class Klass4;
@class Klass5;
@class Klass6;
@class Klass7;
@class KlassMethods;
@class XYZ1;
@class XYZ2;
@class XYZ3;
@class XYZ4;
@class XYZ5;
@class XYZ6;
@class XYZ7;
@class XYZMethods;
@class AnEnumMethods;
@class TheEnumMethods;
@class SWIGTYPE_p_p_Klass7;
@class SWIGTYPE_p_p_Space__XYZ7;

@interface SWIGTYPE_p_p_Klass7 : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForSWIGTYPE_p_p_Klass7;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

@end

@interface SWIGTYPE_p_p_Space__XYZ7 : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForSWIGTYPE_p_p_Space__XYZ7;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

@end

enum AnEnum1 {
  anenum1
};

enum AnEnum2 {
  anenum2
};

enum AnEnum3 {
  anenum3
};

enum TheEnum1 {
  theenum1
};

enum TheEnum2 {
  theenum2
};

enum TheEnum3 {
  theenum3
};

@interface Klass1 : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForKlass1;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;

-(void)dealloc;

@end

@interface Klass2 : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForKlass2;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;

-(void)dealloc;

@end

@interface Klass3 : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForKlass3;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;

-(void)dealloc;

@end

@interface Klass4 : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForKlass4;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;

-(void)dealloc;

@end

@interface Klass5 : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForKlass5;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;

-(void)dealloc;

@end

@interface Klass6 : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForKlass6;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;

-(void)dealloc;

@end

@interface Klass7 : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForKlass7;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;

-(void)dealloc;

@end

@interface KlassMethods : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForKlassMethods;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
+(void)methodA: (Klass1*)v cv: (Klass2*)cv cp: (Klass3*)cp p: (Klass4*)p cr: (Klass5*)cr r: (Klass6*)r pr: (SWIGTYPE_p_p_Klass7*)pr;
+(void)methodB: (Klass1*)v cv: (Klass2*)cv cp: (Klass3*)cp p: (Klass4*)p cr: (Klass5*)cr r: (Klass6*)r pr: (SWIGTYPE_p_p_Klass7*)pr;
-(id)init;

-(void)dealloc;

@end

@interface XYZ1 : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForXYZ1;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;

-(void)dealloc;

@end

@interface XYZ2 : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForXYZ2;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;

-(void)dealloc;

@end

@interface XYZ3 : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForXYZ3;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;

-(void)dealloc;

@end

@interface XYZ4 : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForXYZ4;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;

-(void)dealloc;

@end

@interface XYZ5 : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForXYZ5;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;

-(void)dealloc;

@end

@interface XYZ6 : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForXYZ6;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;

-(void)dealloc;

@end

@interface XYZ7 : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForXYZ7;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;

-(void)dealloc;

@end

@interface XYZMethods : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForXYZMethods;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
+(void)methodA: (XYZ1*)v cv: (XYZ2*)cv cp: (XYZ3*)cp p: (XYZ4*)p cr: (XYZ5*)cr r: (XYZ6*)r pr: (SWIGTYPE_p_p_Space__XYZ7*)pr;
+(void)methodB: (XYZ1*)v cv: (XYZ2*)cv cp: (XYZ3*)cp p: (XYZ4*)p cr: (XYZ5*)cr r: (XYZ6*)r pr: (SWIGTYPE_p_p_Space__XYZ7*)pr;
-(id)init;

-(void)dealloc;

@end

@interface AnEnumMethods : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForAnEnumMethods;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
+(void)methodA: (enum AnEnum1)v cv: (enum AnEnum2)cv cr: (enum AnEnum3)cr;
+(void)methodB: (enum AnEnum1)v cv: (enum AnEnum2)cv cr: (enum AnEnum3)cr;
-(id)init;

-(void)dealloc;

@end

@interface TheEnumMethods : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForTheEnumMethods;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
+(void)methodA: (enum TheEnum1)v cv: (enum TheEnum2)cv cr: (enum TheEnum3)cr;
+(void)methodB: (enum TheEnum1)v cv: (enum TheEnum2)cv cr: (enum TheEnum3)cr;
-(id)init;

-(void)dealloc;

@end

Klass1* ObjcGetKlass1A();
Klass1* ObjcGetKlass1B();
Klass2* ObjcGetKlass2A();
Klass2* ObjcGetKlass2B();
Klass3* ObjcGetKlass3A();
Klass3* ObjcGetKlass3B();
Klass4* ObjcGetKlass4A();
Klass4* ObjcGetKlass4B();
Klass5* ObjcGetKlass5A();
Klass5* ObjcGetKlass5B();
Klass6* ObjcGetKlass6A();
Klass6* ObjcGetKlass6B();
Klass7* ObjcGetKlass7A();
Klass7* ObjcGetKlass7B();

#ifdef __cplusplus
}
#endif

