/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
#include "global_scope_types_proxy.h"
#include "global_scope_types_wrap.h"


@implementation SWIGTYPE_p_f_Dingaling__void
-(void*)getCptr {
	return [self swigCPtrForSWIGTYPE_p_f_Dingaling__void];
}

-(void*)swigCPtrForSWIGTYPE_p_f_Dingaling__void {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

@end


@implementation SWIGTYPE_MyTemplateT_Dingaling_t
-(void*)getCptr {
	return [self swigCPtrForSWIGTYPE_MyTemplateT_Dingaling_t];
}

-(void*)swigCPtrForSWIGTYPE_MyTemplateT_Dingaling_t {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

@end


@implementation SWIGTYPE_MyTemplateT_Dingaling_const_p_t
-(void*)getCptr {
	return [self swigCPtrForSWIGTYPE_MyTemplateT_Dingaling_const_p_t];
}

-(void*)swigCPtrForSWIGTYPE_MyTemplateT_Dingaling_const_p_t {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

@end


@implementation Dingaling
-(void*)getCptr {
	return [self swigCPtrForDingaling];
}

-(void*)swigCPtrForDingaling {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        [NSException raise:@"UnsupportedOperationException" format: @"%@",                        @"C++ destructor does not have public access"];
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation Ting
-(void*)getCptr {
	return [self swigCPtrForTing];
}

-(void*)swigCPtrForTing {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_Ting();
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_Ting((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation Test
-(void*)getCptr {
	return [self swigCPtrForTest];
}

-(void*)swigCPtrForTest {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(void)something: (Dingaling*)t pt: (Dingaling*)pt rt: (Dingaling*)rt crt: (Dingaling*)crt
{
 _wrap_Test_something([self swigCPtrForTest], [t getCptr], [pt getCptr], [rt getCptr], [crt getCptr]);
}

-(void)tsomething: (SWIGTYPE_MyTemplateT_Dingaling_t*)t1 t2: (SWIGTYPE_MyTemplateT_Dingaling_const_p_t*)t2
{
 _wrap_Test_tsomething([self swigCPtrForTest], [t1 getCptr], [t2 getCptr]);
}

-(void)nothing: (Ting*)arg1 arg2: (Ting*)arg2
{
 _wrap_Test_nothing([self swigCPtrForTest], [arg1 getCptr], [arg2 getCptr]);
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_Test();
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_Test((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end

void ObjcFuncptrtest(SWIGTYPE_p_f_Dingaling__void* arg0)
{
 _wrap_funcptrtest([arg0 getCptr]);
}

