/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#import <objc/NSObject.h>

#ifndef SWIG_OBJC_RUNTIME_DECLARATIONS
#define SWIG_OBJC_RUNTIME_DECLARATIONS
typedef unsigned long NSUInteger;
typedef unsigned short unichar;
struct objc_object;
typedef struct objc_object *SWIGObjectiveCId;
#endif

@class NSString;
@class NSArray;
@class NSMutableArray;
@class NSData;
@class NSAutoreleasePool;
@class NSException;

#ifdef __cplusplus
extern "C" {
#endif
extern void NSLog(NSString *format, ...);
#ifdef __cplusplus
}
#endif

#import "import_share_a_proxy.h"


#ifdef __cplusplus
extern "C" {
#endif

@class SWIGTYPE_p_DenseMatrix;

@interface SWIGTYPE_p_DenseMatrix : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForSWIGTYPE_p_DenseMatrix;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

@end

Operator* ObjcMake_DenseMatrix(int height, int width);
void ObjcDelete_DenseMatrix(SWIGTYPE_p_DenseMatrix* op);

#ifdef __cplusplus
}
#endif

