/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
#include "inherit_same_name_proxy.h"
#include "inherit_same_name_wrap.h"


@implementation Base
-(void*)getCptr {
	return [self swigCPtrForBase];
}

-(void*)swigCPtrForBase {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_Base();
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_Base((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation Derived
- (void*)getCptr {
	return [self swigCPtrForDerived];
}

-(void*)swigCPtrForDerived {
	return swigCPtr_Derived;
}

-(void*)swigRelease {
	void *cptr = swigCPtr_Derived;
	swigCPtr_Derived = NULL;
	swigCPtr = NULL;
    
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = SWIG_ObjectiveC_cast__p_Derived_to__p_Base(cptr);
        swigCPtr_Derived = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(void)MethodOrVariable
{
 _wrap_Derived_MethodOrVariable([self swigCPtrForDerived]);
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_Derived();
        swigCPtr = SWIG_ObjectiveC_cast__p_Derived_to__p_Base(cptr);
        swigCPtr_Derived = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr_Derived != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_Derived((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr_Derived = NULL;
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation Bottom
- (void*)getCptr {
	return [self swigCPtrForBottom];
}

-(void*)swigCPtrForBottom {
	return swigCPtr_Bottom;
}

-(void*)swigRelease {
	void *cptr = swigCPtr_Bottom;
	swigCPtr_Bottom = NULL;
	swigCPtr_Derived = NULL;
    swigCPtr = NULL;
    
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr_Derived = SWIG_ObjectiveC_cast__p_Bottom_to__p_Derived(cptr);
        swigCPtr = SWIG_ObjectiveC_cast__p_Bottom_to__p_Base(cptr);
        swigCPtr_Bottom = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(void)MethodOrVariable
{
 _wrap_Bottom_MethodOrVariable([self swigCPtrForBottom]);
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_Bottom();
        swigCPtr_Derived = SWIG_ObjectiveC_cast__p_Bottom_to__p_Derived(cptr);
        swigCPtr = SWIG_ObjectiveC_cast__p_Bottom_to__p_Base(cptr);
        swigCPtr_Bottom = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr_Bottom != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_Bottom((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr_Bottom = NULL;
    swigCPtr_Derived = NULL;
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end

