/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#import <objc/NSObject.h>

#ifndef SWIG_OBJC_RUNTIME_DECLARATIONS
#define SWIG_OBJC_RUNTIME_DECLARATIONS
typedef unsigned long NSUInteger;
typedef unsigned short unichar;
struct objc_object;
typedef struct objc_object *SWIGObjectiveCId;
#endif

@class NSString;
@class NSArray;
@class NSMutableArray;
@class NSData;
@class NSAutoreleasePool;
@class NSException;

#ifdef __cplusplus
extern "C" {
#endif
extern void NSLog(NSString *format, ...);
#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif

@class SWIGTYPE_p_void;

@interface SWIGTYPE_p_void : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForSWIGTYPE_p_void;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

@end

NSData * ObjcCdata(SWIGTYPE_p_void* ptr, unsigned long nelements);
void ObjcMemmove(SWIGTYPE_p_void* data, NSData * indata);
NSData * ObjcCdata_int(int * ptr, unsigned long nelements);
NSData * ObjcCdata_double(double * ptr, unsigned long nelements);
SWIGTYPE_p_void* ObjcMalloc(unsigned long size);

#ifdef __cplusplus
}
#endif

