/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
#include "li_std_pair_proxy.h"
#include "li_std_pair_wrap.h"


@implementation IntPair
-(void*)getCptr {
	return [self swigCPtrForIntPair];
}

-(void*)swigCPtrForIntPair {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_IntPair();
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}

-(id)initWithP: (IntPair*)p
{
 
	if((self = [super init])) {
		void* cptr = _wrap_copy_IntPair([p getCptr]);
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}

-(void)setFirst: (int)value
{
 _wrap_IntPair_first_set([self swigCPtrForIntPair], value);
}

-(int)getFirst
{
  return _wrap_IntPair_first_get([self swigCPtrForIntPair]); 
}

-(void)setSecond: (int)value
{
 _wrap_IntPair_second_set([self swigCPtrForIntPair], value);
}

-(int)getSecond
{
  return _wrap_IntPair_second_get([self swigCPtrForIntPair]); 
}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_IntPair((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end

IntPair* ObjcMakeIntPair(int a, int b)
{
    void* cPtr = _wrap_makeIntPair(a, b);
     IntPair* ret = 0;
     if(cPtr) {
        ret = [[[IntPair alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

IntPair* ObjcMakeIntPairPtr(int a, int b)
{
    void* cPtr = _wrap_makeIntPairPtr(a, b);
     IntPair* ret = 0;
     if(cPtr) {
        ret = [[[IntPair alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

IntPair* ObjcMakeIntPairRef(int a, int b)
{
    void* cPtr = _wrap_makeIntPairRef(a, b);
     IntPair* ret = 0;
     if(cPtr) {
        ret = [[[IntPair alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

IntPair* ObjcMakeIntPairConstRef(int a, int b)
{
    void* cPtr = _wrap_makeIntPairConstRef(a, b);
     IntPair* ret = 0;
     if(cPtr) {
        ret = [[[IntPair alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

int ObjcProduct1(IntPair* p)
{
  return _wrap_product1([p getCptr]); 
}

int ObjcProduct2(IntPair* p)
{
  return _wrap_product2([p getCptr]); 
}

int ObjcProduct3(IntPair* p)
{
  return _wrap_product3([p getCptr]); 
}


@implementation Holder
-(void*)getCptr {
	return [self swigCPtrForHolder];
}

-(void*)swigCPtrForHolder {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(id)initWithN: (int)n
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_Holder(n);
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}

-(void)setNumber: (int)value
{
 _wrap_Holder_number_set([self swigCPtrForHolder], value);
}

-(int)getNumber
{
  return _wrap_Holder_number_get([self swigCPtrForHolder]); 
}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_Holder((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation PairTest
-(void*)getCptr {
	return [self swigCPtrForPairTest];
}

-(void*)swigCPtrForPairTest {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_PairTest();
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}

-(id)initWithP: (PairTest*)p
{
 
	if((self = [super init])) {
		void* cptr = _wrap_copy_PairTest([p getCptr]);
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}

-(void)setFirst: (Holder*)value
{
 _wrap_PairTest_first_set([self swigCPtrForPairTest], [value getCptr]);
}

-(Holder*)getFirst
{
    void* cPtr = _wrap_PairTest_first_get([self swigCPtrForPairTest]);
     Holder* ret = 0;
     if(cPtr) {
        ret = [[[Holder alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

-(void)setSecond: (int)value
{
 _wrap_PairTest_second_set([self swigCPtrForPairTest], value);
}

-(int)getSecond
{
  return _wrap_PairTest_second_get([self swigCPtrForPairTest]); 
}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_PairTest((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end

PairTest* ObjcPair1(PairTest* x)
{
    void* cPtr = _wrap_pair1([x getCptr]);
     PairTest* ret = 0;
     if(cPtr) {
        ret = [[[PairTest alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

