/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
#include "long_long_proxy.h"
#include "long_long_wrap.h"

void ObjcFoo1(long long x)
{
 _wrap_foo1(x);
}

void ObjcFoo2(long long x)
{
 _wrap_foo2(x);
}

void ObjcFoo3(long long x)
{
 _wrap_foo3(x);
}

void ObjcFoo4(unsigned long long x)
{
 _wrap_foo4(x);
}

void ObjcFoo5(long long x)
{
 _wrap_foo5(x);
}

void ObjcFoo6(unsigned long long x)
{
 _wrap_foo6(x);
}

long long ObjcBar1()
{
  return _wrap_bar1(); 
}

long long ObjcBar2()
{
  return _wrap_bar2(); 
}

long long ObjcBar3()
{
  return _wrap_bar3(); 
}

unsigned long long ObjcBar4()
{
  return _wrap_bar4(); 
}

long long ObjcBar5()
{
  return _wrap_bar5(); 
}

unsigned long long ObjcBar6()
{
  return _wrap_bar6(); 
}

void setLl(long long value)
{
 _wrap_ll_set(value);
}

long long getLl()
{
  return _wrap_ll_get(); 
}

void setUll(unsigned long long value)
{
 _wrap_ull_set(value);
}

unsigned long long getUll()
{
  return _wrap_ull_get(); 
}

long long lconst1= (1234567890LL);
unsigned long long lconst2= (1234567890ULL);
long long lconst3= (1234567LL);
unsigned long long lconst4= (1234567ULL);
long long lconst5= (987654321LL);
unsigned long long lconst6= (987654321ULL);
long long ObjcUnsignedToSigned(unsigned long long ull)
{
  return _wrap_UnsignedToSigned(ull); 
}

