/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
#include "minherit2_proxy.h"
#include "minherit2_wrap.h"


@implementation IRemoteSyncIO
-(void*)getCptr {
	return [self swigCPtrForIRemoteSyncIO];
}

-(void*)swigCPtrForIRemoteSyncIO {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(void)syncmethod
{
 _wrap_IRemoteSyncIO_syncmethod([self swigCPtrForIRemoteSyncIO]);
}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_IRemoteSyncIO((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation IRemoteAsyncIO
-(void*)getCptr {
	return [self swigCPtrForIRemoteAsyncIO];
}

-(void*)swigCPtrForIRemoteAsyncIO {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(void)asyncmethod
{
 _wrap_IRemoteAsyncIO_asyncmethod([self swigCPtrForIRemoteAsyncIO]);
}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_IRemoteAsyncIO((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation RemoteMpe
- (void*)getCptr {
	return [self swigCPtrForRemoteMpe];
}

-(void*)swigCPtrForRemoteMpe {
	return swigCPtr_RemoteMpe;
}

-(void*)swigRelease {
	void *cptr = swigCPtr_RemoteMpe;
	swigCPtr_RemoteMpe = NULL;
	swigCPtr = NULL;
    
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = SWIG_ObjectiveC_cast__p_RemoteMpe_to__p_IRemoteSyncIO(cptr);
        swigCPtr_RemoteMpe = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(void)syncmethod
{
 _wrap_RemoteMpe_syncmethod([self swigCPtrForRemoteMpe]);
}

-(void)asyncmethod
{
 _wrap_RemoteMpe_asyncmethod([self swigCPtrForRemoteMpe]);
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_RemoteMpe();
        swigCPtr = SWIG_ObjectiveC_cast__p_RemoteMpe_to__p_IRemoteSyncIO(cptr);
        swigCPtr_RemoteMpe = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}

-(IRemoteAsyncIO*)asIRemoteAsyncIO {
  void *cptr = SWIG_ObjectiveC_cast__p_RemoteMpe_to__p_IRemoteAsyncIO([self swigCPtrForRemoteMpe]);
  return cptr ? [[[IRemoteAsyncIO alloc] initWithCptr:cptr swigOwnCObject:NO] autorelease] : 0;
}


-(void)dealloc{

  if (swigCPtr_RemoteMpe != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_RemoteMpe((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr_RemoteMpe = NULL;
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end

