/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
#include "mod_a_proxy.h"
#include "mod_a_wrap.h"


@implementation SWIGTYPE_p_C
-(void*)getCptr {
	return [self swigCPtrForSWIGTYPE_p_C];
}

-(void*)swigCPtrForSWIGTYPE_p_C {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

@end


@implementation A
-(void*)getCptr {
	return [self swigCPtrForA];
}

-(void*)swigCPtrForA {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_A();
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}

-(SWIGTYPE_p_C*)GetC
{
    void* cPtr = _wrap_A_GetC([self swigCPtrForA]);
     SWIGTYPE_p_C* ret = 0;
     if(cPtr) {
        ret = [[[SWIGTYPE_p_C alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

-(void)DoSomething: (A*)a
{
 _wrap_A_DoSomething([self swigCPtrForA], [a getCptr]);
}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_A((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation B
- (void*)getCptr {
	return [self swigCPtrForB];
}

-(void*)swigCPtrForB {
	return swigCPtr_B;
}

-(void*)swigRelease {
	void *cptr = swigCPtr_B;
	swigCPtr_B = NULL;
	swigCPtr = NULL;
    
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = SWIG_ObjectiveC_cast__p_B_to__p_A(cptr);
        swigCPtr_B = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_B();
        swigCPtr = SWIG_ObjectiveC_cast__p_B_to__p_A(cptr);
        swigCPtr_B = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr_B != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_B((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr_B = NULL;
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end

