/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
#include "multiple_inheritance_shared_ptr_proxy.h"
#include "multiple_inheritance_shared_ptr_wrap.h"


@implementation SWIGTYPE_boost__shared_ptrT_Space__Derived1_t
-(void*)getCptr {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

@end


@implementation SWIGTYPE_boost__shared_ptrT_Space__Derived2_t
-(void*)getCptr {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

@end


@implementation SWIGTYPE_p_boost__shared_ptrT_Space__ABase1_t
-(void*)getCptr {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

@end


@implementation SWIGTYPE_boost__shared_ptrT_Space__Derived3_t
-(void*)getCptr {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

@end


@implementation SWIGTYPE_p_p_Space__Derived1
-(void*)getCptr {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

@end


@implementation SWIGTYPE_p_p_Space__Derived2
-(void*)getCptr {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

@end


@implementation SWIGTYPE_p_boost__shared_ptrT_Space__Derived1_t
-(void*)getCptr {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

@end


@implementation SWIGTYPE_p_boost__shared_ptrT_Space__Bottom1_t
-(void*)getCptr {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

@end


@implementation SWIGTYPE_p_p_Space__Derived3
-(void*)getCptr {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

@end


@implementation SWIGTYPE_p_boost__shared_ptrT_Space__Derived2_t
-(void*)getCptr {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

@end


@implementation SWIGTYPE_p_p_Space__Bottom1
-(void*)getCptr {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

@end


@implementation SWIGTYPE_p_boost__shared_ptrT_Space__Bottom2_t
-(void*)getCptr {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

@end


@implementation SWIGTYPE_boost__shared_ptrT_Space__CBase1_t
-(void*)getCptr {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

@end


@implementation SWIGTYPE_p_boost__shared_ptrT_Space__Derived3_t
-(void*)getCptr {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

@end


@implementation SWIGTYPE_p_p_Space__Bottom2
-(void*)getCptr {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

@end


@implementation SWIGTYPE_p_boost__shared_ptrT_Space__Bottom3_t
-(void*)getCptr {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

@end


@implementation SWIGTYPE_boost__shared_ptrT_Space__CBase2_t
-(void*)getCptr {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

@end


@implementation SWIGTYPE_p_p_Space__Bottom3
-(void*)getCptr {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

@end


@implementation SWIGTYPE_p_p_Space__CBase1
-(void*)getCptr {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

@end


@implementation SWIGTYPE_p_p_Space__CBase2
-(void*)getCptr {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

@end


@implementation SWIGTYPE_boost__shared_ptrT_Space__ABase1_t
-(void*)getCptr {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

@end


@implementation SWIGTYPE_p_p_Space__ABase1
-(void*)getCptr {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

@end


@implementation SWIGTYPE_boost__shared_ptrT_Space__Bottom1_t
-(void*)getCptr {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

@end


@implementation SWIGTYPE_p_boost__shared_ptrT_Space__CBase1_t
-(void*)getCptr {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

@end


@implementation SWIGTYPE_boost__shared_ptrT_Space__Bottom2_t
-(void*)getCptr {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

@end


@implementation SWIGTYPE_p_boost__shared_ptrT_Space__CBase2_t
-(void*)getCptr {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

@end


@implementation SWIGTYPE_boost__shared_ptrT_Space__Bottom3_t
-(void*)getCptr {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

@end


@implementation CBase1
-(void*)getCptr {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(void)cbase1x
{
 _wrap_CBase1_cbase1x([self getCptr]);
}

-(int)cbase1y
{
  return _wrap_CBase1_cbase1y([self getCptr]); 
}

-(int)cbase1z
{
  return _wrap_CBase1_cbase1z([self getCptr]); 
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_CBase1();
        swigCPtr = cptr;
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_CBase1((void*)swigCPtr);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
  }
  [super dealloc];

}

@end


@implementation CBase2
-(void*)getCptr {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(int)cbase2
{
  return _wrap_CBase2_cbase2([self getCptr]); 
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_CBase2();
        swigCPtr = cptr;
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_CBase2((void*)swigCPtr);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
  }
  [super dealloc];

}

@end


@implementation ABase1
-(void*)getCptr {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(int)abase1
{
  return _wrap_ABase1_abase1([self getCptr]); 
}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_ABase1((void*)swigCPtr);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
  }
  [super dealloc];

}

@end


@implementation Derived1
- (void*)getCptr {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(void)cbase1x
{
 _wrap_Derived1_cbase1x([self getCptr]);
}

-(int)cbase1y
{
  return _wrap_Derived1_cbase1y([self getCptr]); 
}

-(int)cbase2
{
  return _wrap_Derived1_cbase2([self getCptr]); 
}

-(CBase2*)cloneit
{
    void* cPtr = _wrap_Derived1_cloneit([self getCptr]);
     CBase2* ret = 0;
     if(cPtr) {
        ret = [[[CBase2 alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

-(void)derived1
{
 _wrap_Derived1_derived1([self getCptr]);
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_Derived1();
        swigCPtr = cptr;
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_Derived1((void*)swigCPtr);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
  }
  [super dealloc];

}

@end


@implementation Derived2
- (void*)getCptr {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(void)cbase1x
{
 _wrap_Derived2_cbase1x([self getCptr]);
}

-(int)cbase1y
{
  return _wrap_Derived2_cbase1y([self getCptr]); 
}

-(int)abase1
{
  return _wrap_Derived2_abase1([self getCptr]); 
}

-(CBase1*)cloneit
{
    void* cPtr = _wrap_Derived2_cloneit([self getCptr]);
     CBase1* ret = 0;
     if(cPtr) {
        ret = [[[CBase1 alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

-(void)derived2
{
 _wrap_Derived2_derived2([self getCptr]);
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_Derived2();
        swigCPtr = cptr;
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_Derived2((void*)swigCPtr);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
  }
  [super dealloc];

}

@end


@implementation Derived3
- (void*)getCptr {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(int)cbase1y
{
  return _wrap_Derived3_cbase1y([self getCptr]); 
}

-(int)cbase2
{
  return _wrap_Derived3_cbase2([self getCptr]); 
}

-(int)abase1
{
  return _wrap_Derived3_abase1([self getCptr]); 
}

-(void)cbase1x
{
 _wrap_Derived3_cbase1x([self getCptr]);
}

-(ABase1*)cloneit
{
    void* cPtr = _wrap_Derived3_cloneit([self getCptr]);
     ABase1* ret = 0;
     if(cPtr) {
        ret = [[[ABase1 alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

-(void)derived3
{
 _wrap_Derived3_derived3([self getCptr]);
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_Derived3();
        swigCPtr = cptr;
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_Derived3((void*)swigCPtr);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
  }
  [super dealloc];

}

@end


@implementation Bottom1
- (void*)getCptr {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(void)cbase1x
{
 _wrap_Bottom1_cbase1x([self getCptr]);
}

-(int)cbase1y
{
  return _wrap_Bottom1_cbase1y([self getCptr]); 
}

-(int)cbase2
{
  return _wrap_Bottom1_cbase2([self getCptr]); 
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_Bottom1();
        swigCPtr = cptr;
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_Bottom1((void*)swigCPtr);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
  }
  [super dealloc];

}

@end


@implementation Bottom2
- (void*)getCptr {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(int)cbase1y
{
  return _wrap_Bottom2_cbase1y([self getCptr]); 
}

-(int)abase1
{
  return _wrap_Bottom2_abase1([self getCptr]); 
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_Bottom2();
        swigCPtr = cptr;
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_Bottom2((void*)swigCPtr);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
  }
  [super dealloc];

}

@end


@implementation Bottom3
- (void*)getCptr {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(int)cbase1y
{
  return _wrap_Bottom3_cbase1y([self getCptr]); 
}

-(int)cbase2
{
  return _wrap_Bottom3_cbase2([self getCptr]); 
}

-(int)abase1
{
  return _wrap_Bottom3_abase1([self getCptr]); 
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_Bottom3();
        swigCPtr = cptr;
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_Bottom3((void*)swigCPtr);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
  }
  [super dealloc];

}

@end

int ObjcInputValCBase1(CBase1* cb1)
{
  return _wrap_InputValCBase1([cb1 getCptr]); 
}

int ObjcInputValCBase2(CBase2* cb2)
{
  return _wrap_InputValCBase2([cb2 getCptr]); 
}

int ObjcInputPtrABase1(ABase1* pab1)
{
  return _wrap_InputPtrABase1([pab1 getCptr]); 
}

int ObjcInputPtrCBase1(CBase1* pcb1)
{
  return _wrap_InputPtrCBase1([pcb1 getCptr]); 
}

int ObjcInputPtrCBase2(CBase2* pcb2)
{
  return _wrap_InputPtrCBase2([pcb2 getCptr]); 
}

int ObjcInputRefABase1(ABase1* rab1)
{
  return _wrap_InputRefABase1([rab1 getCptr]); 
}

int ObjcInputRefCBase1(CBase1* rcb1)
{
  return _wrap_InputRefCBase1([rcb1 getCptr]); 
}

int ObjcInputRefCBase2(CBase2* rcb2)
{
  return _wrap_InputRefCBase2([rcb2 getCptr]); 
}

int ObjcInputCPtrRefABase1(SWIGTYPE_p_p_Space__ABase1* pab1)
{
  return _wrap_InputCPtrRefABase1([pab1 getCptr]); 
}

int ObjcInputCPtrRefCBase1(SWIGTYPE_p_p_Space__CBase1* pcb1)
{
  return _wrap_InputCPtrRefCBase1([pcb1 getCptr]); 
}

int ObjcInputCPtrRefCBase2(SWIGTYPE_p_p_Space__CBase2* pcb2)
{
  return _wrap_InputCPtrRefCBase2([pcb2 getCptr]); 
}

int ObjcInputSharedPtrABase1(SWIGTYPE_boost__shared_ptrT_Space__ABase1_t* pab1)
{
  return _wrap_InputSharedPtrABase1([pab1 getCptr]); 
}

int ObjcInputSharedPtrCBase1(SWIGTYPE_boost__shared_ptrT_Space__CBase1_t* pcb1)
{
  return _wrap_InputSharedPtrCBase1([pcb1 getCptr]); 
}

int ObjcInputSharedPtrCBase2(SWIGTYPE_boost__shared_ptrT_Space__CBase2_t* pcb2)
{
  return _wrap_InputSharedPtrCBase2([pcb2 getCptr]); 
}

int ObjcInputSharedPtrRefABase1(SWIGTYPE_p_boost__shared_ptrT_Space__ABase1_t* pab1)
{
  return _wrap_InputSharedPtrRefABase1([pab1 getCptr]); 
}

int ObjcInputSharedPtrRefCBase1(SWIGTYPE_p_boost__shared_ptrT_Space__CBase1_t* pcb1)
{
  return _wrap_InputSharedPtrRefCBase1([pcb1 getCptr]); 
}

int ObjcInputSharedPtrRefCBase2(SWIGTYPE_p_boost__shared_ptrT_Space__CBase2_t* pcb2)
{
  return _wrap_InputSharedPtrRefCBase2([pcb2 getCptr]); 
}

int ObjcInputValDerived1(Derived1* d)
{
  return _wrap_InputValDerived1([d getCptr]); 
}

int ObjcInputValDerived2(Derived2* d)
{
  return _wrap_InputValDerived2([d getCptr]); 
}

int ObjcInputValDerived3(Derived3* d)
{
  return _wrap_InputValDerived3([d getCptr]); 
}

int ObjcInputRefDerived1(Derived1* d)
{
  return _wrap_InputRefDerived1([d getCptr]); 
}

int ObjcInputRefDerived2(Derived2* d)
{
  return _wrap_InputRefDerived2([d getCptr]); 
}

int ObjcInputRefDerived3(Derived3* d)
{
  return _wrap_InputRefDerived3([d getCptr]); 
}

int ObjcInputPtrDerived1(Derived1* d)
{
  return _wrap_InputPtrDerived1([d getCptr]); 
}

int ObjcInputPtrDerived2(Derived2* d)
{
  return _wrap_InputPtrDerived2([d getCptr]); 
}

int ObjcInputPtrDerived3(Derived3* d)
{
  return _wrap_InputPtrDerived3([d getCptr]); 
}

int ObjcInputCPtrRefDerived1(SWIGTYPE_p_p_Space__Derived1* d)
{
  return _wrap_InputCPtrRefDerived1([d getCptr]); 
}

int ObjcInputCPtrRefDerived2(SWIGTYPE_p_p_Space__Derived2* d)
{
  return _wrap_InputCPtrRefDerived2([d getCptr]); 
}

int ObjcInputCPtrRefDerived3(SWIGTYPE_p_p_Space__Derived3* d)
{
  return _wrap_InputCPtrRefDerived3([d getCptr]); 
}

int ObjcInputSharedPtrDerived1(SWIGTYPE_boost__shared_ptrT_Space__Derived1_t* d)
{
  return _wrap_InputSharedPtrDerived1([d getCptr]); 
}

int ObjcInputSharedPtrDerived2(SWIGTYPE_boost__shared_ptrT_Space__Derived2_t* d)
{
  return _wrap_InputSharedPtrDerived2([d getCptr]); 
}

int ObjcInputSharedPtrDerived3(SWIGTYPE_boost__shared_ptrT_Space__Derived3_t* d)
{
  return _wrap_InputSharedPtrDerived3([d getCptr]); 
}

int ObjcInputSharedPtrRefDerived1(SWIGTYPE_p_boost__shared_ptrT_Space__Derived1_t* d)
{
  return _wrap_InputSharedPtrRefDerived1([d getCptr]); 
}

int ObjcInputSharedPtrRefDerived2(SWIGTYPE_p_boost__shared_ptrT_Space__Derived2_t* d)
{
  return _wrap_InputSharedPtrRefDerived2([d getCptr]); 
}

int ObjcInputSharedPtrRefDerived3(SWIGTYPE_p_boost__shared_ptrT_Space__Derived3_t* d)
{
  return _wrap_InputSharedPtrRefDerived3([d getCptr]); 
}

int ObjcInputValBottom1(Bottom1* d)
{
  return _wrap_InputValBottom1([d getCptr]); 
}

int ObjcInputValBottom2(Bottom2* d)
{
  return _wrap_InputValBottom2([d getCptr]); 
}

int ObjcInputValBottom3(Bottom3* d)
{
  return _wrap_InputValBottom3([d getCptr]); 
}

int ObjcInputRefBottom1(Bottom1* d)
{
  return _wrap_InputRefBottom1([d getCptr]); 
}

int ObjcInputRefBottom2(Bottom2* d)
{
  return _wrap_InputRefBottom2([d getCptr]); 
}

int ObjcInputRefBottom3(Bottom3* d)
{
  return _wrap_InputRefBottom3([d getCptr]); 
}

int ObjcInputPtrBottom1(Bottom1* d)
{
  return _wrap_InputPtrBottom1([d getCptr]); 
}

int ObjcInputPtrBottom2(Bottom2* d)
{
  return _wrap_InputPtrBottom2([d getCptr]); 
}

int ObjcInputPtrBottom3(Bottom3* d)
{
  return _wrap_InputPtrBottom3([d getCptr]); 
}

int ObjcInputCPtrRefBottom1(SWIGTYPE_p_p_Space__Bottom1* d)
{
  return _wrap_InputCPtrRefBottom1([d getCptr]); 
}

int ObjcInputCPtrRefBottom2(SWIGTYPE_p_p_Space__Bottom2* d)
{
  return _wrap_InputCPtrRefBottom2([d getCptr]); 
}

int ObjcInputCPtrRefBottom3(SWIGTYPE_p_p_Space__Bottom3* d)
{
  return _wrap_InputCPtrRefBottom3([d getCptr]); 
}

int ObjcInputSharedPtrBottom1(SWIGTYPE_boost__shared_ptrT_Space__Bottom1_t* d)
{
  return _wrap_InputSharedPtrBottom1([d getCptr]); 
}

int ObjcInputSharedPtrBottom2(SWIGTYPE_boost__shared_ptrT_Space__Bottom2_t* d)
{
  return _wrap_InputSharedPtrBottom2([d getCptr]); 
}

int ObjcInputSharedPtrBottom3(SWIGTYPE_boost__shared_ptrT_Space__Bottom3_t* d)
{
  return _wrap_InputSharedPtrBottom3([d getCptr]); 
}

int ObjcInputSharedPtrRefBottom1(SWIGTYPE_p_boost__shared_ptrT_Space__Bottom1_t* d)
{
  return _wrap_InputSharedPtrRefBottom1([d getCptr]); 
}

int ObjcInputSharedPtrRefBottom2(SWIGTYPE_p_boost__shared_ptrT_Space__Bottom2_t* d)
{
  return _wrap_InputSharedPtrRefBottom2([d getCptr]); 
}

int ObjcInputSharedPtrRefBottom3(SWIGTYPE_p_boost__shared_ptrT_Space__Bottom3_t* d)
{
  return _wrap_InputSharedPtrRefBottom3([d getCptr]); 
}

CBase1* ObjcMakePtrDerived1_CBase1()
{
    void* cPtr = _wrap_MakePtrDerived1_CBase1();
     CBase1* ret = 0;
     if(cPtr) {
        ret = [[[CBase1 alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

CBase2* ObjcMakePtrDerived1_CBase2()
{
    void* cPtr = _wrap_MakePtrDerived1_CBase2();
     CBase2* ret = 0;
     if(cPtr) {
        ret = [[[CBase2 alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

CBase1* ObjcMakePtrDerived2_CBase1()
{
    void* cPtr = _wrap_MakePtrDerived2_CBase1();
     CBase1* ret = 0;
     if(cPtr) {
        ret = [[[CBase1 alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

ABase1* ObjcMakePtrDerived2_ABase1()
{
    void* cPtr = _wrap_MakePtrDerived2_ABase1();
     ABase1* ret = 0;
     if(cPtr) {
        ret = [[[ABase1 alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

ABase1* ObjcMakePtrDerived3_ABase1()
{
    void* cPtr = _wrap_MakePtrDerived3_ABase1();
     ABase1* ret = 0;
     if(cPtr) {
        ret = [[[ABase1 alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

CBase1* ObjcMakePtrDerived3_CBase1()
{
    void* cPtr = _wrap_MakePtrDerived3_CBase1();
     CBase1* ret = 0;
     if(cPtr) {
        ret = [[[CBase1 alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

CBase2* ObjcMakePtrDerived3_CBase2()
{
    void* cPtr = _wrap_MakePtrDerived3_CBase2();
     CBase2* ret = 0;
     if(cPtr) {
        ret = [[[CBase2 alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

CBase1* ObjcMakeRefDerived1_CBase1()
{
    void* cPtr = _wrap_MakeRefDerived1_CBase1();
     CBase1* ret = 0;
     if(cPtr) {
        ret = [[[CBase1 alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

CBase2* ObjcMakeRefDerived1_CBase2()
{
    void* cPtr = _wrap_MakeRefDerived1_CBase2();
     CBase2* ret = 0;
     if(cPtr) {
        ret = [[[CBase2 alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

CBase1* ObjcMakeRefDerived2_CBase1()
{
    void* cPtr = _wrap_MakeRefDerived2_CBase1();
     CBase1* ret = 0;
     if(cPtr) {
        ret = [[[CBase1 alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

ABase1* ObjcMakeRefDerived2_ABase1()
{
    void* cPtr = _wrap_MakeRefDerived2_ABase1();
     ABase1* ret = 0;
     if(cPtr) {
        ret = [[[ABase1 alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

ABase1* ObjcMakeRefDerived3_ABase1()
{
    void* cPtr = _wrap_MakeRefDerived3_ABase1();
     ABase1* ret = 0;
     if(cPtr) {
        ret = [[[ABase1 alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

CBase1* ObjcMakeRefDerived3_CBase1()
{
    void* cPtr = _wrap_MakeRefDerived3_CBase1();
     CBase1* ret = 0;
     if(cPtr) {
        ret = [[[CBase1 alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

CBase2* ObjcMakeRefDerived3_CBase2()
{
    void* cPtr = _wrap_MakeRefDerived3_CBase2();
     CBase2* ret = 0;
     if(cPtr) {
        ret = [[[CBase2 alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

SWIGTYPE_p_p_Space__CBase1* ObjcMakeConstPtrRefDerived1_CBase1()
{
    void* cPtr = _wrap_MakeConstPtrRefDerived1_CBase1();
     SWIGTYPE_p_p_Space__CBase1* ret = 0;
     if(cPtr) {
        ret = [[[SWIGTYPE_p_p_Space__CBase1 alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

SWIGTYPE_p_p_Space__CBase2* ObjcMakeConstPtrRefDerived1_CBase2()
{
    void* cPtr = _wrap_MakeConstPtrRefDerived1_CBase2();
     SWIGTYPE_p_p_Space__CBase2* ret = 0;
     if(cPtr) {
        ret = [[[SWIGTYPE_p_p_Space__CBase2 alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

SWIGTYPE_p_p_Space__CBase1* ObjcMakeConstPtrRefDerived2_CBase1()
{
    void* cPtr = _wrap_MakeConstPtrRefDerived2_CBase1();
     SWIGTYPE_p_p_Space__CBase1* ret = 0;
     if(cPtr) {
        ret = [[[SWIGTYPE_p_p_Space__CBase1 alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

SWIGTYPE_p_p_Space__ABase1* ObjcMakeConstPtrRefDerived2_ABase1()
{
    void* cPtr = _wrap_MakeConstPtrRefDerived2_ABase1();
     SWIGTYPE_p_p_Space__ABase1* ret = 0;
     if(cPtr) {
        ret = [[[SWIGTYPE_p_p_Space__ABase1 alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

SWIGTYPE_p_p_Space__ABase1* ObjcMakeConstPtrRefDerived3_ABase1()
{
    void* cPtr = _wrap_MakeConstPtrRefDerived3_ABase1();
     SWIGTYPE_p_p_Space__ABase1* ret = 0;
     if(cPtr) {
        ret = [[[SWIGTYPE_p_p_Space__ABase1 alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

SWIGTYPE_p_p_Space__CBase1* ObjcMakeConstPtrRefDerived3_CBase1()
{
    void* cPtr = _wrap_MakeConstPtrRefDerived3_CBase1();
     SWIGTYPE_p_p_Space__CBase1* ret = 0;
     if(cPtr) {
        ret = [[[SWIGTYPE_p_p_Space__CBase1 alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

SWIGTYPE_p_p_Space__CBase2* ObjcMakeConstPtrRefDerived3_CBase2()
{
    void* cPtr = _wrap_MakeConstPtrRefDerived3_CBase2();
     SWIGTYPE_p_p_Space__CBase2* ret = 0;
     if(cPtr) {
        ret = [[[SWIGTYPE_p_p_Space__CBase2 alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

CBase1* ObjcMakeValDerived1_CBase1()
{
    void* cPtr = _wrap_MakeValDerived1_CBase1();
     CBase1* ret = 0;
     if(cPtr) {
        ret = [[[CBase1 alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

CBase2* ObjcMakeValDerived1_CBase2()
{
    void* cPtr = _wrap_MakeValDerived1_CBase2();
     CBase2* ret = 0;
     if(cPtr) {
        ret = [[[CBase2 alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

CBase1* ObjcMakeValDerived2_CBase1()
{
    void* cPtr = _wrap_MakeValDerived2_CBase1();
     CBase1* ret = 0;
     if(cPtr) {
        ret = [[[CBase1 alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

CBase1* ObjcMakeValDerived3_CBase1()
{
    void* cPtr = _wrap_MakeValDerived3_CBase1();
     CBase1* ret = 0;
     if(cPtr) {
        ret = [[[CBase1 alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

CBase2* ObjcMakeValDerived3_CBase2()
{
    void* cPtr = _wrap_MakeValDerived3_CBase2();
     CBase2* ret = 0;
     if(cPtr) {
        ret = [[[CBase2 alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

SWIGTYPE_boost__shared_ptrT_Space__CBase1_t* ObjcMakeSharedPtrDerived1_CBase1()
{
 {
  void *cptr = _wrap_MakeSharedPtrDerived1_CBase1();
  SWIGTYPE_boost__shared_ptrT_Space__CBase1_t *ret = [[SWIGTYPE_boost__shared_ptrT_Space__CBase1_t alloc] initWithCptr:cptr swigOwnCObject:YES];
  return ret;
}
}

SWIGTYPE_boost__shared_ptrT_Space__CBase2_t* ObjcMakeSharedPtrDerived1_CBase2()
{
 {
  void *cptr = _wrap_MakeSharedPtrDerived1_CBase2();
  SWIGTYPE_boost__shared_ptrT_Space__CBase2_t *ret = [[SWIGTYPE_boost__shared_ptrT_Space__CBase2_t alloc] initWithCptr:cptr swigOwnCObject:YES];
  return ret;
}
}

SWIGTYPE_boost__shared_ptrT_Space__CBase1_t* ObjcMakeSharedPtrDerived2_CBase1()
{
 {
  void *cptr = _wrap_MakeSharedPtrDerived2_CBase1();
  SWIGTYPE_boost__shared_ptrT_Space__CBase1_t *ret = [[SWIGTYPE_boost__shared_ptrT_Space__CBase1_t alloc] initWithCptr:cptr swigOwnCObject:YES];
  return ret;
}
}

SWIGTYPE_boost__shared_ptrT_Space__ABase1_t* ObjcMakeSharedPtrDerived2_ABase1()
{
 {
  void *cptr = _wrap_MakeSharedPtrDerived2_ABase1();
  SWIGTYPE_boost__shared_ptrT_Space__ABase1_t *ret = [[SWIGTYPE_boost__shared_ptrT_Space__ABase1_t alloc] initWithCptr:cptr swigOwnCObject:YES];
  return ret;
}
}

SWIGTYPE_boost__shared_ptrT_Space__ABase1_t* ObjcMakeSharedPtrDerived3_ABase1()
{
 {
  void *cptr = _wrap_MakeSharedPtrDerived3_ABase1();
  SWIGTYPE_boost__shared_ptrT_Space__ABase1_t *ret = [[SWIGTYPE_boost__shared_ptrT_Space__ABase1_t alloc] initWithCptr:cptr swigOwnCObject:YES];
  return ret;
}
}

SWIGTYPE_boost__shared_ptrT_Space__CBase1_t* ObjcMakeSharedPtrDerived3_CBase1()
{
 {
  void *cptr = _wrap_MakeSharedPtrDerived3_CBase1();
  SWIGTYPE_boost__shared_ptrT_Space__CBase1_t *ret = [[SWIGTYPE_boost__shared_ptrT_Space__CBase1_t alloc] initWithCptr:cptr swigOwnCObject:YES];
  return ret;
}
}

SWIGTYPE_boost__shared_ptrT_Space__CBase2_t* ObjcMakeSharedPtrDerived3_CBase2()
{
 {
  void *cptr = _wrap_MakeSharedPtrDerived3_CBase2();
  SWIGTYPE_boost__shared_ptrT_Space__CBase2_t *ret = [[SWIGTYPE_boost__shared_ptrT_Space__CBase2_t alloc] initWithCptr:cptr swigOwnCObject:YES];
  return ret;
}
}

SWIGTYPE_boost__shared_ptrT_Space__CBase1_t* ObjcMakeSharedPtrRefDerived1_CBase1()
{
 {
  void *cptr = _wrap_MakeSharedPtrRefDerived1_CBase1();
  SWIGTYPE_boost__shared_ptrT_Space__CBase1_t *ret = [[SWIGTYPE_boost__shared_ptrT_Space__CBase1_t alloc] initWithCptr:cptr swigOwnCObject:YES];
  return ret;
}
}

SWIGTYPE_boost__shared_ptrT_Space__CBase2_t* ObjcMakeSharedPtrRefDerived1_CBase2()
{
 {
  void *cptr = _wrap_MakeSharedPtrRefDerived1_CBase2();
  SWIGTYPE_boost__shared_ptrT_Space__CBase2_t *ret = [[SWIGTYPE_boost__shared_ptrT_Space__CBase2_t alloc] initWithCptr:cptr swigOwnCObject:YES];
  return ret;
}
}

SWIGTYPE_boost__shared_ptrT_Space__CBase1_t* ObjcMakeSharedPtrRefDerived2_CBase1()
{
 {
  void *cptr = _wrap_MakeSharedPtrRefDerived2_CBase1();
  SWIGTYPE_boost__shared_ptrT_Space__CBase1_t *ret = [[SWIGTYPE_boost__shared_ptrT_Space__CBase1_t alloc] initWithCptr:cptr swigOwnCObject:YES];
  return ret;
}
}

SWIGTYPE_boost__shared_ptrT_Space__ABase1_t* ObjcMakeSharedPtrRefDerived2_ABase1()
{
 {
  void *cptr = _wrap_MakeSharedPtrRefDerived2_ABase1();
  SWIGTYPE_boost__shared_ptrT_Space__ABase1_t *ret = [[SWIGTYPE_boost__shared_ptrT_Space__ABase1_t alloc] initWithCptr:cptr swigOwnCObject:YES];
  return ret;
}
}

SWIGTYPE_boost__shared_ptrT_Space__ABase1_t* ObjcMakeSharedPtrRefDerived3_ABase1()
{
 {
  void *cptr = _wrap_MakeSharedPtrRefDerived3_ABase1();
  SWIGTYPE_boost__shared_ptrT_Space__ABase1_t *ret = [[SWIGTYPE_boost__shared_ptrT_Space__ABase1_t alloc] initWithCptr:cptr swigOwnCObject:YES];
  return ret;
}
}

SWIGTYPE_boost__shared_ptrT_Space__CBase1_t* ObjcMakeSharedPtrRefDerived3_CBase1()
{
 {
  void *cptr = _wrap_MakeSharedPtrRefDerived3_CBase1();
  SWIGTYPE_boost__shared_ptrT_Space__CBase1_t *ret = [[SWIGTYPE_boost__shared_ptrT_Space__CBase1_t alloc] initWithCptr:cptr swigOwnCObject:YES];
  return ret;
}
}

SWIGTYPE_boost__shared_ptrT_Space__CBase2_t* ObjcMakeSharedPtrRefDerived3_CBase2()
{
 {
  void *cptr = _wrap_MakeSharedPtrRefDerived3_CBase2();
  SWIGTYPE_boost__shared_ptrT_Space__CBase2_t *ret = [[SWIGTYPE_boost__shared_ptrT_Space__CBase2_t alloc] initWithCptr:cptr swigOwnCObject:YES];
  return ret;
}
}

