/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
#include "namespace_virtual_method_proxy.h"
#include "namespace_virtual_method_wrap.h"


@implementation SWIGTYPE_p_A__B__Foo
-(void*)getCptr {
	return [self swigCPtrForSWIGTYPE_p_A__B__Foo];
}

-(void*)swigCPtrForSWIGTYPE_p_A__B__Foo {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

@end


@implementation Foo
-(void*)getCptr {
	return [self swigCPtrForFoo];
}

-(void*)swigCPtrForFoo {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(int)bar: (SWIGTYPE_p_A__B__Foo*)x
{
  return _wrap_Foo_bar([self swigCPtrForFoo], [x getCptr]); 
}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_Foo((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation Spam
- (void*)getCptr {
	return [self swigCPtrForSpam];
}

-(void*)swigCPtrForSpam {
	return swigCPtr_Spam;
}

-(void*)swigRelease {
	void *cptr = swigCPtr_Spam;
	swigCPtr_Spam = NULL;
	swigCPtr = NULL;
    
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = SWIG_ObjectiveC_cast__p_A__C__Spam_to__p_A__C__Foo(cptr);
        swigCPtr_Spam = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_Spam();
        swigCPtr = SWIG_ObjectiveC_cast__p_A__C__Spam_to__p_A__C__Foo(cptr);
        swigCPtr_Spam = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}

-(int)bar: (SWIGTYPE_p_A__B__Foo*)x
{
  return _wrap_Spam_bar([self swigCPtrForSpam], [x getCptr]); 
}


-(void)dealloc{

  if (swigCPtr_Spam != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_Spam((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr_Spam = NULL;
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end

