/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#import <objc/NSObject.h>

#ifndef SWIG_OBJC_RUNTIME_DECLARATIONS
#define SWIG_OBJC_RUNTIME_DECLARATIONS
typedef unsigned long NSUInteger;
typedef unsigned short unichar;
struct objc_object;
typedef struct objc_object *SWIGObjectiveCId;
#endif

@class NSString;
@class NSArray;
@class NSMutableArray;
@class NSData;
@class NSAutoreleasePool;
@class NSException;

#ifdef __cplusplus
extern "C" {
#endif
extern void NSLog(NSString *format, ...);
#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif

@class Struct1A;
@class Struct1B;
@class Struct1C;
@class SWIGTYPE_Space2A__Space1B__Struct1B;
@class SWIGTYPE_Space2A__Space1B__Space1C__Struct1C;

@interface SWIGTYPE_Space2A__Space1B__Struct1B : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForSWIGTYPE_Space2A__Space1B__Struct1B;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

@end

@interface SWIGTYPE_Space2A__Space1B__Space1C__Struct1C : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForSWIGTYPE_Space2A__Space1B__Space1C__Struct1C;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

@end

@interface Struct1A : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForStruct1A;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;

-(void)dealloc;

@end

@interface Struct1B : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForStruct1B;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;

-(void)dealloc;

@end

@interface Struct1C : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForStruct1C;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;

-(void)dealloc;

@end

void ObjcSss3a(Struct1A* arg0, Struct1B* arg1, Struct1C* arg2);
void ObjcSss3b(Struct1A* arg0, Struct1B* arg1, Struct1C* arg2);
void ObjcSss3c(Struct1A* arg0, SWIGTYPE_Space2A__Space1B__Struct1B* arg1, SWIGTYPE_Space2A__Space1B__Space1C__Struct1C* arg2);
void ObjcSss4a(Struct1A* arg0, Struct1B* arg1, Struct1C* arg2);
void ObjcSss4b(Struct1A* arg0, Struct1B* arg1, Struct1C* arg2);

#ifdef __cplusplus
}
#endif

