/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
#include "numeric_bounds_checking_proxy.h"
#include "numeric_bounds_checking_wrap.h"


@implementation Limits
-(void*)getCptr {
	return [self swigCPtrForLimits];
}

-(void*)swigCPtrForLimits {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(signed char)schar_min
{
  return _wrap_Limits_schar_min([self swigCPtrForLimits]); 
}

-(signed char)schar_max
{
  return _wrap_Limits_schar_max([self swigCPtrForLimits]); 
}

-(unsigned char)uchar_min
{
  return _wrap_Limits_uchar_min([self swigCPtrForLimits]); 
}

-(unsigned char)uchar_max
{
  return _wrap_Limits_uchar_max([self swigCPtrForLimits]); 
}

-(short)shrt_min
{
  return _wrap_Limits_shrt_min([self swigCPtrForLimits]); 
}

-(short)shrt_max
{
  return _wrap_Limits_shrt_max([self swigCPtrForLimits]); 
}

-(unsigned short)ushrt_min
{
  return _wrap_Limits_ushrt_min([self swigCPtrForLimits]); 
}

-(unsigned short)ushrt_max
{
  return _wrap_Limits_ushrt_max([self swigCPtrForLimits]); 
}

-(int)int_min
{
  return _wrap_Limits_int_min([self swigCPtrForLimits]); 
}

-(int)int_max
{
  return _wrap_Limits_int_max([self swigCPtrForLimits]); 
}

-(unsigned int)uint_min
{
  return _wrap_Limits_uint_min([self swigCPtrForLimits]); 
}

-(unsigned int)uint_max
{
  return _wrap_Limits_uint_max([self swigCPtrForLimits]); 
}

-(long)long_min
{
  return _wrap_Limits_long_min([self swigCPtrForLimits]); 
}

-(long)long_max
{
  return _wrap_Limits_long_max([self swigCPtrForLimits]); 
}

-(unsigned long)ulong_min
{
  return _wrap_Limits_ulong_min([self swigCPtrForLimits]); 
}

-(unsigned long)ulong_max
{
  return _wrap_Limits_ulong_max([self swigCPtrForLimits]); 
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_Limits();
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_Limits((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation Checker
-(void*)getCptr {
	return [self swigCPtrForChecker];
}

-(void*)swigCPtrForChecker {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(signed char)pass_schar: (signed char)v
{
  return _wrap_Checker_pass_schar([self swigCPtrForChecker], v); 
}

-(unsigned char)pass_uchar: (unsigned char)v
{
  return _wrap_Checker_pass_uchar([self swigCPtrForChecker], v); 
}

-(short)pass_shrt: (short)v
{
  return _wrap_Checker_pass_shrt([self swigCPtrForChecker], v); 
}

-(unsigned short)pass_ushrt: (unsigned short)v
{
  return _wrap_Checker_pass_ushrt([self swigCPtrForChecker], v); 
}

-(int)pass_int: (int)v
{
  return _wrap_Checker_pass_int([self swigCPtrForChecker], v); 
}

-(unsigned int)pass_uint: (unsigned int)v
{
  return _wrap_Checker_pass_uint([self swigCPtrForChecker], v); 
}

-(long)pass_long: (long)v
{
  return _wrap_Checker_pass_long([self swigCPtrForChecker], v); 
}

-(unsigned long)pass_ulong: (unsigned long)v
{
  return _wrap_Checker_pass_ulong([self swigCPtrForChecker], v); 
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_Checker();
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_Checker((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end

