/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
#include "operator_overload_break_proxy.h"
#include "operator_overload_break_wrap.h"


@implementation Op
-(void*)getCptr {
	return [self swigCPtrForOp];
}

-(void*)swigCPtrForOp {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(id)initWithN: (int)n
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_Op(n);
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}

-(id)initWithOther: (Op*)other
{
 
	if((self = [super init])) {
		void* cptr = _wrap_copy_Op([other getCptr]);
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}

-(BOOL)EqualEqual: (Op*)rhs
{
  return _wrap_Op_EqualEqual([self swigCPtrForOp], [rhs getCptr]); 
}

-(Op*)Plus: (Op*)rhs
{
    void* cPtr = _wrap_Op_Plus([self swigCPtrForOp], [rhs getCptr]);
     Op* ret = 0;
     if(cPtr) {
        ret = [[[Op alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

-(Op*)Minus: (Op*)rhs
{
    void* cPtr = _wrap_Op_Minus([self swigCPtrForOp], [rhs getCptr]);
     Op* ret = 0;
     if(cPtr) {
        ret = [[[Op alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

-(Op*)__rsub__: (int)lhs
{
    void* cPtr = _wrap_Op___rsub__([self swigCPtrForOp], lhs);
     Op* ret = 0;
     if(cPtr) {
        ret = [[[Op alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

-(Op*)PlusPlusPrefix
{
    void* cPtr = _wrap_Op_PlusPlusPrefix([self swigCPtrForOp]);
     Op* ret = 0;
     if(cPtr) {
        ret = [[[Op alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

-(void)PrintK
{
 _wrap_Op_PrintK([self swigCPtrForOp]);
}

-(void)setK: (int)value
{
 _wrap_Op_k_set([self swigCPtrForOp], value);
}

-(int)getK
{
  return _wrap_Op_k_get([self swigCPtrForOp]); 
}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_Op((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation Op2
-(void*)getCptr {
	return [self swigCPtrForOp2];
}

-(void*)swigCPtrForOp2 {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_Op2();
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_Op2((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end

