/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#import <objc/NSObject.h>

@class NSString;
@class NSArray;
@class NSData;
@class NSAutoreleasePool;
@class NSException;
extern void NSLog(NSString *format, ...);


#ifdef __cplusplus
extern "C" {
#endif

@class RCObjBase;
@class RCObj;
@class A;
@class A1;
@class A2;
@class A3;
@class B;
@class Factory;
@class SWIGTYPE_RCPtrT_A_t;

@interface SWIGTYPE_RCPtrT_A_t : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

@end

@interface RCObjBase : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(int)ref_count;
-(int)addref;
-(int)delref;

-(void)dealloc;

@end

@interface RCObj : RCObjBase
-(void*)getCptr;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

-(void)dealloc;

@end

@interface A : RCObj
-(void*)getCptr;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;

-(void)dealloc;

@end

@interface A1 : A
-(void*)getCptr;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

-(void)dealloc;

@end

@interface A2 : A
-(void*)getCptr;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;

-(void)dealloc;

@end

@interface A3 : A1
-(void*)getCptr;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;

-(void)dealloc;

@end

@interface B : RCObj
-(void*)getCptr;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)initWithA: (A*)a;
-(A*)get_a;
+(B*)create: (A*)a;
-(B*)cloner;
-(SWIGTYPE_RCPtrT_A_t*)get_rca;

-(void)dealloc;

@end

B* ObjcGlobal_create(A* a);
@interface Factory : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
+(B*)create: (A*)a;
-(B*)create2: (A*)a;
-(id)init;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

