/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
#include "rename_wildcard_proxy.h"
#include "rename_wildcard_wrap.h"


@implementation GlobalWildStruct
-(void*)getCptr {
	return [self swigCPtrForGlobalWildStruct];
}

-(void*)swigCPtrForGlobalWildStruct {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(void)mm1
{
 _wrap_GlobalWildStruct_mm1([self swigCPtrForGlobalWildStruct]);
}

-(void)mm2a
{
 _wrap_GlobalWildStruct_mm2a([self swigCPtrForGlobalWildStruct]);
}

-(void)mm3a
{
 _wrap_GlobalWildStruct_mm3a([self swigCPtrForGlobalWildStruct]);
}

-(void)mm4a
{
 _wrap_GlobalWildStruct_mm4a([self swigCPtrForGlobalWildStruct]);
}

-(void)mm5a
{
 _wrap_GlobalWildStruct_mm5a([self swigCPtrForGlobalWildStruct]);
}

-(int)opinta
{
  return _wrap_GlobalWildStruct_opinta([self swigCPtrForGlobalWildStruct]); 
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_GlobalWildStruct();
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_GlobalWildStruct((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation SpaceWildStruct
-(void*)getCptr {
	return [self swigCPtrForSpaceWildStruct];
}

-(void*)swigCPtrForSpaceWildStruct {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(void)mm1
{
 _wrap_SpaceWildStruct_mm1([self swigCPtrForSpaceWildStruct]);
}

-(void)mm2c
{
 _wrap_SpaceWildStruct_mm2c([self swigCPtrForSpaceWildStruct]);
}

-(void)mm3c
{
 _wrap_SpaceWildStruct_mm3c([self swigCPtrForSpaceWildStruct]);
}

-(void)mm4c
{
 _wrap_SpaceWildStruct_mm4c([self swigCPtrForSpaceWildStruct]);
}

-(void)mm5c
{
 _wrap_SpaceWildStruct_mm5c([self swigCPtrForSpaceWildStruct]);
}

-(int)opintc
{
  return _wrap_SpaceWildStruct_opintc([self swigCPtrForSpaceWildStruct]); 
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_SpaceWildStruct();
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_SpaceWildStruct((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation NoChangeStruct
-(void*)getCptr {
	return [self swigCPtrForNoChangeStruct];
}

-(void*)swigCPtrForNoChangeStruct {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(void)mm1
{
 _wrap_NoChangeStruct_mm1([self swigCPtrForNoChangeStruct]);
}

-(void)mm2
{
 _wrap_NoChangeStruct_mm2([self swigCPtrForNoChangeStruct]);
}

-(void)mm3
{
 _wrap_NoChangeStruct_mm3([self swigCPtrForNoChangeStruct]);
}

-(void)mm4
{
 _wrap_NoChangeStruct_mm4([self swigCPtrForNoChangeStruct]);
}

-(void)mm5
{
 _wrap_NoChangeStruct_mm5([self swigCPtrForNoChangeStruct]);
}

-(int)opint
{
  return _wrap_NoChangeStruct_opint([self swigCPtrForNoChangeStruct]); 
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_NoChangeStruct();
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_NoChangeStruct((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation SpaceNoChangeStruct
-(void*)getCptr {
	return [self swigCPtrForSpaceNoChangeStruct];
}

-(void*)swigCPtrForSpaceNoChangeStruct {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(void)mm1
{
 _wrap_SpaceNoChangeStruct_mm1([self swigCPtrForSpaceNoChangeStruct]);
}

-(void)mm2
{
 _wrap_SpaceNoChangeStruct_mm2([self swigCPtrForSpaceNoChangeStruct]);
}

-(void)mm3
{
 _wrap_SpaceNoChangeStruct_mm3([self swigCPtrForSpaceNoChangeStruct]);
}

-(void)mm4
{
 _wrap_SpaceNoChangeStruct_mm4([self swigCPtrForSpaceNoChangeStruct]);
}

-(void)mm5
{
 _wrap_SpaceNoChangeStruct_mm5([self swigCPtrForSpaceNoChangeStruct]);
}

-(int)opint
{
  return _wrap_SpaceNoChangeStruct_opint([self swigCPtrForSpaceNoChangeStruct]); 
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_SpaceNoChangeStruct();
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_SpaceNoChangeStruct((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation GlobalWildTemplateStructInt
-(void*)getCptr {
	return [self swigCPtrForGlobalWildTemplateStructInt];
}

-(void*)swigCPtrForGlobalWildTemplateStructInt {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(void)mm1
{
 _wrap_GlobalWildTemplateStructInt_mm1([self swigCPtrForGlobalWildTemplateStructInt]);
}

-(void)mm2b
{
 _wrap_GlobalWildTemplateStructInt_mm2b([self swigCPtrForGlobalWildTemplateStructInt]);
}

-(void)tt2b
{
 _wrap_GlobalWildTemplateStructInt_tt2b([self swigCPtrForGlobalWildTemplateStructInt]);
}

-(void)mm3b
{
 _wrap_GlobalWildTemplateStructInt_mm3b([self swigCPtrForGlobalWildTemplateStructInt]);
}

-(void)tt3b
{
 _wrap_GlobalWildTemplateStructInt_tt3b([self swigCPtrForGlobalWildTemplateStructInt]);
}

-(void)mm4b
{
 _wrap_GlobalWildTemplateStructInt_mm4b([self swigCPtrForGlobalWildTemplateStructInt]);
}

-(void)tt4b
{
 _wrap_GlobalWildTemplateStructInt_tt4b([self swigCPtrForGlobalWildTemplateStructInt]);
}

-(void)mm5b
{
 _wrap_GlobalWildTemplateStructInt_mm5b([self swigCPtrForGlobalWildTemplateStructInt]);
}

-(void)tt5b
{
 _wrap_GlobalWildTemplateStructInt_tt5b([self swigCPtrForGlobalWildTemplateStructInt]);
}

-(int)opintb
{
  return _wrap_GlobalWildTemplateStructInt_opintb([self swigCPtrForGlobalWildTemplateStructInt]); 
}

-(double)opdoubleb
{
  return _wrap_GlobalWildTemplateStructInt_opdoubleb([self swigCPtrForGlobalWildTemplateStructInt]); 
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_GlobalWildTemplateStructInt();
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_GlobalWildTemplateStructInt((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation SpaceWildTemplateStructInt
-(void*)getCptr {
	return [self swigCPtrForSpaceWildTemplateStructInt];
}

-(void*)swigCPtrForSpaceWildTemplateStructInt {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(void)mm1
{
 _wrap_SpaceWildTemplateStructInt_mm1([self swigCPtrForSpaceWildTemplateStructInt]);
}

-(void)mm2d
{
 _wrap_SpaceWildTemplateStructInt_mm2d([self swigCPtrForSpaceWildTemplateStructInt]);
}

-(void)tt2d
{
 _wrap_SpaceWildTemplateStructInt_tt2d([self swigCPtrForSpaceWildTemplateStructInt]);
}

-(void)mm3d
{
 _wrap_SpaceWildTemplateStructInt_mm3d([self swigCPtrForSpaceWildTemplateStructInt]);
}

-(void)tt3d
{
 _wrap_SpaceWildTemplateStructInt_tt3d([self swigCPtrForSpaceWildTemplateStructInt]);
}

-(void)mm4d
{
 _wrap_SpaceWildTemplateStructInt_mm4d([self swigCPtrForSpaceWildTemplateStructInt]);
}

-(void)tt4d
{
 _wrap_SpaceWildTemplateStructInt_tt4d([self swigCPtrForSpaceWildTemplateStructInt]);
}

-(void)mm5d
{
 _wrap_SpaceWildTemplateStructInt_mm5d([self swigCPtrForSpaceWildTemplateStructInt]);
}

-(void)tt5d
{
 _wrap_SpaceWildTemplateStructInt_tt5d([self swigCPtrForSpaceWildTemplateStructInt]);
}

-(int)opintd
{
  return _wrap_SpaceWildTemplateStructInt_opintd([self swigCPtrForSpaceWildTemplateStructInt]); 
}

-(double)opdoubled
{
  return _wrap_SpaceWildTemplateStructInt_opdoubled([self swigCPtrForSpaceWildTemplateStructInt]); 
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_SpaceWildTemplateStructInt();
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_SpaceWildTemplateStructInt((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end

