/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
#include "simple_array_proxy.h"
#include "simple_array_wrap.h"


@implementation SWIGTYPE_p_double
-(void*)getCptr {
	return [self swigCPtrForSWIGTYPE_p_double];
}

-(void*)swigCPtrForSWIGTYPE_p_double {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

@end


@implementation SWIGTYPE_p_int
-(void*)getCptr {
	return [self swigCPtrForSWIGTYPE_p_int];
}

-(void*)swigCPtrForSWIGTYPE_p_int {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

@end

void setX(SWIGTYPE_p_int* value)
{
 _wrap_x_set([value getCptr]);
}

SWIGTYPE_p_int* getX()
{
    void* cPtr = _wrap_x_get();
     SWIGTYPE_p_int* ret = 0;
     if(cPtr) {
        ret = [[[SWIGTYPE_p_int alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

void setY(SWIGTYPE_p_double* value)
{
 _wrap_y_set([value getCptr]);
}

SWIGTYPE_p_double* getY()
{
    void* cPtr = _wrap_y_get();
     SWIGTYPE_p_double* ret = 0;
     if(cPtr) {
        ret = [[[SWIGTYPE_p_double alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}


@implementation BarArray
-(void*)getCptr {
	return [self swigCPtrForBarArray];
}

-(void*)swigCPtrForBarArray {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(void)setI: (int)value
{
 _wrap_BarArray_i_set([self swigCPtrForBarArray], value);
}

-(int)getI
{
  return _wrap_BarArray_i_get([self swigCPtrForBarArray]); 
}

-(void)setD: (double)value
{
 _wrap_BarArray_d_set([self swigCPtrForBarArray], value);
}

-(double)getD
{
  return _wrap_BarArray_d_get([self swigCPtrForBarArray]); 
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_BarArray();
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_BarArray((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end

void setBars(BarArray* value)
{
 _wrap_bars_set([value getCptr]);
}

BarArray* getBars()
{
    void* cPtr = _wrap_bars_get();
     BarArray* ret = 0;
     if(cPtr) {
        ret = [[[BarArray alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

void ObjcInitArray()
{
 _wrap_initArray();
}

