/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
#include "template_typedef_class_template_proxy.h"
#include "template_typedef_class_template_wrap.h"


@implementation SWIGTYPE_Standard__PairT_Standard__MultimapT_int_A_p_t__iterator_Standard__MultimapT_int_A_p_t__iterator_t
-(void*)getCptr {
	return [self swigCPtrForSWIGTYPE_Standard__PairT_Standard__MultimapT_int_A_p_t__iterator_Standard__MultimapT_int_A_p_t__iterator_t];
}

-(void*)swigCPtrForSWIGTYPE_Standard__PairT_Standard__MultimapT_int_A_p_t__iterator_Standard__MultimapT_int_A_p_t__iterator_t {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

@end


@implementation SWIGTYPE_Standard__PairT_Standard__MultimapT_int_A_p_t__const_iterator_Standard__MultimapT_int_A_p_t__const_iterator_t
-(void*)getCptr {
	return [self swigCPtrForSWIGTYPE_Standard__PairT_Standard__MultimapT_int_A_p_t__const_iterator_Standard__MultimapT_int_A_p_t__const_iterator_t];
}

-(void*)swigCPtrForSWIGTYPE_Standard__PairT_Standard__MultimapT_int_A_p_t__const_iterator_Standard__MultimapT_int_A_p_t__const_iterator_t {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

@end


@implementation A
-(void*)getCptr {
	return [self swigCPtrForA];
}

-(void*)swigCPtrForA {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(void)setVal: (int)value
{
 _wrap_A_val_set([self swigCPtrForA], value);
}

-(int)getVal
{
  return _wrap_A_val_get([self swigCPtrForA]); 
}

-(id)initWithV: (int)v
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_A(v);
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_A((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation PairA
-(void*)getCptr {
	return [self swigCPtrForPairA];
}

-(void*)swigCPtrForPairA {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(void)setFirst: (int)value
{
 _wrap_PairA_first_set([self swigCPtrForPairA], value);
}

-(int)getFirst
{
  return _wrap_PairA_first_get([self swigCPtrForPairA]); 
}

-(void)setSecond: (A*)value
{
 _wrap_PairA_second_set([self swigCPtrForPairA], [value getCptr]);
}

-(A*)getSecond
{
    void* cPtr = _wrap_PairA_second_get([self swigCPtrForPairA]);
     A* ret = 0;
     if(cPtr) {
        ret = [[[A alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_PairA();
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_PairA((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation MultimapA
-(void*)getCptr {
	return [self swigCPtrForMultimapA];
}

-(void*)swigCPtrForMultimapA {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(SWIGTYPE_Standard__PairT_Standard__MultimapT_int_A_p_t__iterator_Standard__MultimapT_int_A_p_t__iterator_t*)equal_range_1: (int *)kt1
{
    void* cPtr = _wrap_MultimapA_equal_range_1([self swigCPtrForMultimapA], kt1);
     SWIGTYPE_Standard__PairT_Standard__MultimapT_int_A_p_t__iterator_Standard__MultimapT_int_A_p_t__iterator_t* ret = 0;
     if(cPtr) {
        ret = [[[SWIGTYPE_Standard__PairT_Standard__MultimapT_int_A_p_t__iterator_Standard__MultimapT_int_A_p_t__iterator_t alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

-(SWIGTYPE_Standard__PairT_Standard__MultimapT_int_A_p_t__const_iterator_Standard__MultimapT_int_A_p_t__const_iterator_t*)equal_range_2: (int *)kt2
{
    void* cPtr = _wrap_MultimapA_equal_range_2([self swigCPtrForMultimapA], kt2);
     SWIGTYPE_Standard__PairT_Standard__MultimapT_int_A_p_t__const_iterator_Standard__MultimapT_int_A_p_t__const_iterator_t* ret = 0;
     if(cPtr) {
        ret = [[[SWIGTYPE_Standard__PairT_Standard__MultimapT_int_A_p_t__const_iterator_Standard__MultimapT_int_A_p_t__const_iterator_t alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_MultimapA();
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_MultimapA((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end

