/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#import <Foundation/Foundation.h>

#ifndef SWIG_OBJC_RUNTIME_DECLARATIONS
#define SWIG_OBJC_RUNTIME_DECLARATIONS
struct objc_object;
typedef struct objc_object *SWIGObjectiveCId;
#endif


#ifdef __cplusplus
extern "C" {
#endif

@class interface_traits;
@class module_traits;
@class Interface_UP;
@class Module_1;
@class ExtInterface1;
@class ExtInterface2;
@class ExtModule1;
@class ExtModule2;

enum Polarization {
  UnaryPolarization,
  BinaryPolarization
};

@interface interface_traits : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForinterface_traits;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;

-(void)dealloc;

@end

@interface module_traits : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrFormodule_traits;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;

-(void)dealloc;

@end

@interface Interface_UP : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForInterface_UP;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;

-(void)dealloc;

@end

@interface Module_1 : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForModule_1;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;

-(void)dealloc;

@end

@interface ExtInterface1 : Interface_UP
{
	void *swigCPtr_ExtInterface1;
}
-(void*)getCptr;
-(void*)swigCPtrForExtInterface1;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;

-(void)dealloc;

@end

@interface ExtInterface2 : Interface_UP
{
	void *swigCPtr_ExtInterface2;
}
-(void*)getCptr;
-(void*)swigCPtrForExtInterface2;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;

-(void)dealloc;

@end

@interface ExtModule1 : Module_1
{
	void *swigCPtr_ExtModule1;
}
-(void*)getCptr;
-(void*)swigCPtrForExtModule1;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;

-(void)dealloc;

@end

@interface ExtModule2 : Module_1
{
	void *swigCPtr_ExtModule2;
}
-(void*)getCptr;
-(void*)swigCPtrForExtModule2;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

