/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
#include "template_using_member_default_arg_proxy.h"
#include "template_using_member_default_arg_wrap.h"


@implementation ThingAInt
-(void*)getCptr {
	return [self swigCPtrForThingAInt];
}

-(void*)swigCPtrForThingAInt {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_ThingAInt();
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_ThingAInt((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation ThingADerivedInt
- (void*)getCptr {
	return [self swigCPtrForThingADerivedInt];
}

-(void*)swigCPtrForThingADerivedInt {
	return swigCPtr_ThingADerivedInt;
}

-(void*)swigRelease {
	void *cptr = swigCPtr_ThingADerivedInt;
	swigCPtr_ThingADerivedInt = NULL;
	swigCPtr = NULL;
    
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = SWIG_ObjectiveC_cast__p_ThingADerivedT_int_t_to__p_ThingAT_int_t(cptr);
        swigCPtr_ThingADerivedInt = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(void)describeA
{
 _wrap_ThingADerivedInt_describeA([self swigCPtrForThingADerivedInt]);
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_ThingADerivedInt();
        swigCPtr = SWIG_ObjectiveC_cast__p_ThingADerivedT_int_t_to__p_ThingAT_int_t(cptr);
        swigCPtr_ThingADerivedInt = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr_ThingADerivedInt != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_ThingADerivedInt((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr_ThingADerivedInt = NULL;
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation ThingBInt
-(void*)getCptr {
	return [self swigCPtrForThingBInt];
}

-(void*)swigCPtrForThingBInt {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_ThingBInt();
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_ThingBInt((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation ThingBDerivedInt
- (void*)getCptr {
	return [self swigCPtrForThingBDerivedInt];
}

-(void*)swigCPtrForThingBDerivedInt {
	return swigCPtr_ThingBDerivedInt;
}

-(void*)swigRelease {
	void *cptr = swigCPtr_ThingBDerivedInt;
	swigCPtr_ThingBDerivedInt = NULL;
	swigCPtr = NULL;
    
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = SWIG_ObjectiveC_cast__p_ThingBDerivedT_int_t_to__p_ThingBT_int_short_t(cptr);
        swigCPtr_ThingBDerivedInt = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(void)describeB
{
 _wrap_ThingBDerivedInt_describeB([self swigCPtrForThingBDerivedInt]);
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_ThingBDerivedInt();
        swigCPtr = SWIG_ObjectiveC_cast__p_ThingBDerivedT_int_t_to__p_ThingBT_int_short_t(cptr);
        swigCPtr_ThingBDerivedInt = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr_ThingBDerivedInt != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_ThingBDerivedInt((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr_ThingBDerivedInt = NULL;
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end

