/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
#include "template_ns4_proxy.h"
#include "template_ns4_wrap.h"


@implementation Double
-(void*)getCptr {
	return [self swigCPtrForDouble];
}

-(void*)swigCPtrForDouble {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_Double();
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_Double((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation Function_DD
-(void*)getCptr {
	return [self swigCPtrForFunction_DD];
}

-(void*)swigCPtrForFunction_DD {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(NSString *)test
{
   NSString *ret = _wrap_Function_DD_test([self swigCPtrForFunction_DD]);
    return ret; 
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_Function_DD();
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_Function_DD((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation ArithFunction_DD
- (void*)getCptr {
	return [self swigCPtrForArithFunction_DD];
}

-(void*)swigCPtrForArithFunction_DD {
	return swigCPtr_ArithFunction_DD;
}

-(void*)swigRelease {
	void *cptr = swigCPtr_ArithFunction_DD;
	swigCPtr_ArithFunction_DD = NULL;
	swigCPtr = NULL;
    
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = SWIG_ObjectiveC_cast__p_hello__ArithFunctionT_hello__Double_hello__Double_t_to__p_hello__Function_T_hello__Double_hello__Double_t(cptr);
        swigCPtr_ArithFunction_DD = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_ArithFunction_DD();
        swigCPtr = SWIG_ObjectiveC_cast__p_hello__ArithFunctionT_hello__Double_hello__Double_t_to__p_hello__Function_T_hello__Double_hello__Double_t(cptr);
        swigCPtr_ArithFunction_DD = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr_ArithFunction_DD != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_ArithFunction_DD((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr_ArithFunction_DD = NULL;
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation Class_DD
- (void*)getCptr {
	return [self swigCPtrForClass_DD];
}

-(void*)swigCPtrForClass_DD {
	return swigCPtr_Class_DD;
}

-(void*)swigRelease {
	void *cptr = swigCPtr_Class_DD;
	swigCPtr_Class_DD = NULL;
	swigCPtr_ArithFunction_DD = NULL;
    swigCPtr = NULL;
    
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr_ArithFunction_DD = SWIG_ObjectiveC_cast__p_hello__Class_T_hello__Double_hello__Double_t_to__p_hello__ArithFunctionT_hello__Double_hello__Double_t(cptr);
        swigCPtr = SWIG_ObjectiveC_cast__p_hello__Class_T_hello__Double_hello__Double_t_to__p_hello__Function_T_hello__Double_hello__Double_t(cptr);
        swigCPtr_Class_DD = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_Class_DD();
        swigCPtr_ArithFunction_DD = SWIG_ObjectiveC_cast__p_hello__Class_T_hello__Double_hello__Double_t_to__p_hello__ArithFunctionT_hello__Double_hello__Double_t(cptr);
        swigCPtr = SWIG_ObjectiveC_cast__p_hello__Class_T_hello__Double_hello__Double_t_to__p_hello__Function_T_hello__Double_hello__Double_t(cptr);
        swigCPtr_Class_DD = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr_Class_DD != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_Class_DD((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr_Class_DD = NULL;
    swigCPtr_ArithFunction_DD = NULL;
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end

ArithFunction_DD* ObjcMake_Class_DD()
{
    void* cPtr = _wrap_make_Class_DD();
     ArithFunction_DD* ret = 0;
     if(cPtr) {
        ret = [[[ArithFunction_DD alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

