/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#import <objc/NSObject.h>

#ifndef SWIG_OBJC_RUNTIME_DECLARATIONS
#define SWIG_OBJC_RUNTIME_DECLARATIONS
typedef unsigned long NSUInteger;
typedef unsigned short unichar;
struct objc_object;
typedef struct objc_object *SWIGObjectiveCId;
#endif

@class NSString;
@class NSArray;
@class NSMutableArray;
@class NSData;
@class NSAutoreleasePool;
@class NSException;

#ifdef __cplusplus
extern "C" {
#endif
extern void NSLog(NSString *format, ...);
#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif

@class LineObj;
@class FontSetObj;
@class A_t;
@class Foo;
@class SWIGTYPE_p_f_int__void;

@interface SWIGTYPE_p_f_int__void : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForSWIGTYPE_p_f_int__void;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;

@end


enum {
  Foo_NONAME1,
  Foo_NONAME2
};

@interface LineObj : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForLineObj;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(void)setNumpoints: (int)value;
-(int)getNumpoints;
-(id)init;

-(void)dealloc;

@end

@interface FontSetObj : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForFontSetObj;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(NSString *)getFilename;
-(int)getNumfonts;
-(void)setFonts: (int *)value;
-(int *)getFonts;
-(id)init;

-(void)dealloc;

@end

extern int MS_NOOVERRIDE;
@interface A_t : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForA_t;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(void)setA: (int)value;
-(int)getA;
-(void)setB: (int)value;
-(int)getB;
-(id)init;

-(void)dealloc;

@end

A_t* ObjcMake_a();
A_t* ObjcMake_b();
@interface Foo : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForFoo;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(void)setEnumvar: (int)value;
-(int)getEnumvar;
-(void)setFoovar: (int)value;
-(int)getFoovar;
-(void)setFptr: (SWIGTYPE_p_f_int__void*)value;
-(SWIGTYPE_p_f_int__void*)getFptr;
-(id)init;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

