/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
#include "unicode_strings_proxy.h"
#include "unicode_strings_wrap.h"

NSString * ObjcNon_utf8_c_str()
{
   NSString *ret = _wrap_non_utf8_c_str();
    return ret; 
}

NSString* ObjcNon_utf8_std_string()
{
 {
    return _wrap_non_utf8_std_string();
  }
}

NSString * ObjcCharstring(NSString * s)
{
   NSString *ret = _wrap_charstring(s);
    return ret; 
}

void ObjcInstring(NSString * s)
{
 _wrap_instring(s);
}

