/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */
#include "unions_proxy.h"
#include "unions_wrap.h"


@implementation SmallStruct
-(void*)getCptr {
	return [self swigCPtrForSmallStruct];
}

-(void*)swigCPtrForSmallStruct {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(void)setJill: (short)value
{
 _wrap_SmallStruct_jill_set([self swigCPtrForSmallStruct], value);
}

-(short)getJill
{
  return _wrap_SmallStruct_jill_get([self swigCPtrForSmallStruct]); 
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_SmallStruct();
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_SmallStruct((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation BigStruct
-(void*)getCptr {
	return [self swigCPtrForBigStruct];
}

-(void*)swigCPtrForBigStruct {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(void)setJack: (int)value
{
 _wrap_BigStruct_jack_set([self swigCPtrForBigStruct], value);
}

-(int)getJack
{
  return _wrap_BigStruct_jack_get([self swigCPtrForBigStruct]); 
}

-(void)setSmallstruct: (SmallStruct*)value
{
 _wrap_BigStruct_smallstruct_set([self swigCPtrForBigStruct], [value getCptr]);
}

-(SmallStruct*)getSmallstruct
{
    void* cPtr = _wrap_BigStruct_smallstruct_get([self swigCPtrForBigStruct]);
     SmallStruct* ret = 0;
     if(cPtr) {
        ret = [[[SmallStruct alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_BigStruct();
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_BigStruct((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation UnionTest
-(void*)getCptr {
	return [self swigCPtrForUnionTest];
}

-(void*)swigCPtrForUnionTest {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(void)setBs: (BigStruct*)value
{
 _wrap_UnionTest_bs_set([self swigCPtrForUnionTest], [value getCptr]);
}

-(BigStruct*)getBs
{
    void* cPtr = _wrap_UnionTest_bs_get([self swigCPtrForUnionTest]);
     BigStruct* ret = 0;
     if(cPtr) {
        ret = [[[BigStruct alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

-(void)setSs: (SmallStruct*)value
{
 _wrap_UnionTest_ss_set([self swigCPtrForUnionTest], [value getCptr]);
}

-(SmallStruct*)getSs
{
    void* cPtr = _wrap_UnionTest_ss_get([self swigCPtrForUnionTest]);
     SmallStruct* ret = 0;
     if(cPtr) {
        ret = [[[SmallStruct alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_UnionTest();
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_UnionTest((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation EmbeddedUnionTest
-(void*)getCptr {
	return [self swigCPtrForEmbeddedUnionTest];
}

-(void*)swigCPtrForEmbeddedUnionTest {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(EmbeddedUnionTest_uni*)getUni
{
    void* cPtr = _wrap_EmbeddedUnionTest_uni_get([self swigCPtrForEmbeddedUnionTest]);
     EmbeddedUnionTest_uni* ret = 0;
     if(cPtr) {
        ret = [[[EmbeddedUnionTest_uni alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

-(void)setNumber: (int)value
{
 _wrap_EmbeddedUnionTest_number_set([self swigCPtrForEmbeddedUnionTest], value);
}

-(int)getNumber
{
  return _wrap_EmbeddedUnionTest_number_get([self swigCPtrForEmbeddedUnionTest]); 
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_EmbeddedUnionTest();
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_EmbeddedUnionTest((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end


@implementation EmbeddedUnionTest_uni
-(void*)getCptr {
	return [self swigCPtrForEmbeddedUnionTest_uni];
}

-(void*)swigCPtrForEmbeddedUnionTest_uni {
	return swigCPtr;
}

-(void*)swigRelease {
	void *cptr = swigCPtr;
	swigCPtr = NULL;
	swigCMemOwn = NO;
	return cptr;
}

-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject {
	if((self = [super init])) {
		swigCPtr = cptr;
        swigCMemOwn = ownCObject;
	}
	return self;
}

-(void)setBig: (BigStruct*)value
{
 _wrap_EmbeddedUnionTest_uni_big_set([self swigCPtrForEmbeddedUnionTest_uni], [value getCptr]);
}

-(BigStruct*)getBig
{
    void* cPtr = _wrap_EmbeddedUnionTest_uni_big_get([self swigCPtrForEmbeddedUnionTest_uni]);
     BigStruct* ret = 0;
     if(cPtr) {
        ret = [[[BigStruct alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

-(void)setSmall: (SmallStruct*)value
{
 _wrap_EmbeddedUnionTest_uni_small_set([self swigCPtrForEmbeddedUnionTest_uni], [value getCptr]);
}

-(SmallStruct*)getSmall
{
    void* cPtr = _wrap_EmbeddedUnionTest_uni_small_get([self swigCPtrForEmbeddedUnionTest_uni]);
     SmallStruct* ret = 0;
     if(cPtr) {
        ret = [[[SmallStruct alloc] initWithCptr:cPtr swigOwnCObject:NO] autorelease];
     }
    return ret; 
}

-(id)init
{
 
	if((self = [super init])) {
		void* cptr = _wrap_new_EmbeddedUnionTest_uni();
        swigCPtr = cptr;
        
        swigCMemOwn = YES;
	}
	return self;

}


-(void)dealloc{

  if (swigCPtr != NULL) {
    if (swigCMemOwn) {
        _wrap_delete_EmbeddedUnionTest_uni((void*)[self getCptr]);
        swigCMemOwn = NO;
    }
    swigCPtr = NULL;
    
  }
  [super dealloc];

}

@end

