/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#import <objc/NSObject.h>

#ifndef SWIG_OBJC_RUNTIME_DECLARATIONS
#define SWIG_OBJC_RUNTIME_DECLARATIONS
typedef unsigned long NSUInteger;
typedef unsigned short unichar;
struct objc_object;
typedef struct objc_object *SWIGObjectiveCId;
#endif

@class NSString;
@class NSArray;
@class NSMutableArray;
@class NSData;
@class NSAutoreleasePool;
@class NSException;

#ifdef __cplusplus
extern "C" {
#endif
extern void NSLog(NSString *format, ...);
#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif

@class Foo;
@class FooBar;

@interface Foo : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForFoo;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(void)setX: (int)value;
-(int)getX;
-(Foo*)blah;
-(Foo*)exception_spec: (int)what_to_throw;
-(id)init;

-(void)dealloc;

@end

@interface FooBar : Foo
{
	void *swigCPtr_FooBar;
}
-(void*)getCptr;
-(void*)swigCPtrForFooBar;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(Foo*)blah;
-(void)setX: (int)value;
-(int)getX;
-(Foo*)exception_spec: (int)what_to_throw;
-(id)init;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

