/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#import <objc/NSObject.h>

#ifndef SWIG_OBJC_RUNTIME_DECLARATIONS
#define SWIG_OBJC_RUNTIME_DECLARATIONS
typedef unsigned long NSUInteger;
typedef unsigned short unichar;
struct objc_object;
typedef struct objc_object *SWIGObjectiveCId;
#endif

@class NSString;
@class NSArray;
@class NSMutableArray;
@class NSData;
@class NSAutoreleasePool;
@class NSException;

#ifdef __cplusplus
extern "C" {
#endif
extern void NSLog(NSString *format, ...);
#ifdef __cplusplus
}
#endif


#ifdef __cplusplus
extern "C" {
#endif

@class Susing1;
@class Susing2;
@class Susing3;
@class Using1;
@class Using2;
@class Using3;
@class Musing2;
@class Musing3;
@class Dusing2;
@class Dusing3;
@class Mult1;
@class Mult2;
@class MultMiddleA;
@class MultBottomA;
@class MultMiddleB;
@class MultBottomB;
@class Vusing;
@class Vusing1;
@class Vusing2;

@interface Susing1 : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForSusing1;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;

-(void)dealloc;

@end

@interface Susing2 : Susing1
{
	void *swigCPtr_Susing2;
}
-(void*)getCptr;
-(void*)swigCPtrForSusing2;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;

-(void)dealloc;

@end

@interface Susing3 : Susing2
{
	void *swigCPtr_Susing3;
}
-(void*)getCptr;
-(void*)swigCPtrForSusing3;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(void)usingmethod: (int)i;
-(id)init;

-(void)dealloc;

@end

@interface Using1 : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForUsing1;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;

-(void)dealloc;

@end

@interface Using2 : Using1
{
	void *swigCPtr_Using2;
}
-(void*)getCptr;
-(void*)swigCPtrForUsing2;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;

-(void)dealloc;

@end

@interface Using3 : Using2
{
	void *swigCPtr_Using3;
}
-(void*)getCptr;
-(void*)swigCPtrForUsing3;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(void)usingmethod: (int)i j: (int)j k: (int)k;
-(id)init;

-(void)dealloc;

@end

@interface Musing2 : Using1
{
	void *swigCPtr_Musing2;
}
-(void*)getCptr;
-(void*)swigCPtrForMusing2;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;

-(void)dealloc;

@end

@interface Musing3 : Musing2
{
	void *swigCPtr_Musing3;
}
-(void*)getCptr;
-(void*)swigCPtrForMusing3;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(void)usingmethod: (int)i;
-(id)init;

-(void)dealloc;

@end

@interface Dusing2 : Using1
{
	void *swigCPtr_Dusing2;
}
-(void*)getCptr;
-(void*)swigCPtrForDusing2;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;

-(void)dealloc;

@end

@interface Dusing3 : Dusing2
{
	void *swigCPtr_Dusing3;
}
-(void*)getCptr;
-(void*)swigCPtrForDusing3;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(void)usingmethod: (int)i;
-(id)init;

-(void)dealloc;

@end

@interface Mult1 : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForMult1;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;

-(void)dealloc;

@end

@interface Mult2 : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForMult2;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;

-(void)dealloc;

@end

@interface MultMiddleA : Mult1
{
	void *swigCPtr_MultMiddleA;
}
-(void*)getCptr;
-(void*)swigCPtrForMultMiddleA;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(void)multmethod: (int)i j: (int)j;
-(id)init;
-(Mult2*)asMult2;

-(void)dealloc;

@end

@interface MultBottomA : MultMiddleA
{
	void *swigCPtr_MultBottomA;
}
-(void*)getCptr;
-(void*)swigCPtrForMultBottomA;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(void)multmethod: (int)i j: (int)j k: (int)k;
-(id)init;

-(void)dealloc;

@end

void ObjcCplusplus_testA();
@interface MultMiddleB : Mult1
{
	void *swigCPtr_MultMiddleB;
}
-(void*)getCptr;
-(void*)swigCPtrForMultMiddleB;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(id)init;
-(Mult2*)asMult2;

-(void)dealloc;

@end

@interface MultBottomB : MultMiddleB
{
	void *swigCPtr_MultBottomB;
}
-(void*)getCptr;
-(void*)swigCPtrForMultBottomB;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(void)multmethod: (int)i j: (int)j k: (int)k;
-(id)init;

-(void)dealloc;

@end

void ObjcCplusplus_testB();
@interface Vusing : NSObject
{
	void *swigCPtr;
	BOOL swigCMemOwn;
}
-(void*)getCptr;
-(void*)swigCPtrForVusing;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(void)usingmethod: (int)i;
-(id)init;

-(void)dealloc;

@end

@interface Vusing1 : Vusing
{
	void *swigCPtr_Vusing1;
}
-(void*)getCptr;
-(void*)swigCPtrForVusing1;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(void)usingmethod: (int)i;
-(id)init;

-(void)dealloc;

@end

@interface Vusing2 : Vusing1
{
	void *swigCPtr_Vusing2;
}
-(void*)getCptr;
-(void*)swigCPtrForVusing2;
-(void*)swigRelease;
-(id)initWithCptr: (void*)cptr swigOwnCObject: (BOOL)ownCObject;
-(void)usingmethod: (int)i;
-(id)init;

-(void)dealloc;

@end


#ifdef __cplusplus
}
#endif

