/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.5.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#import <objc/NSObject.h>

#ifdef nil
#undef nil
#endif
#ifdef Nil
#undef Nil
#endif

@class NSString;
@class NSArray;
@class NSData;
@class NSAutoreleasePool;
@class NSException;

#ifndef VIRTUAL_DERIVATION_WRAP_H
#define VIRTUAL_DERIVATION_WRAP_H


#ifdef __cplusplus
extern "C" {
#endif

void _wrap_delete_A(void* imarg1);
void _wrap_A_m_a_set(void* imarg1, int imarg2);
int _wrap_A_m_a_get(void* imarg1);
void* _wrap_new_A(int imarg1);
int _wrap_A_get_a(void* imarg1);
void* _wrap_new_B(int imarg1);
int _wrap_B_get_b(void* imarg1);
void _wrap_delete_B(void* imarg1);
void _wrap_IndexReader_norms(void* imarg1);
void _wrap_delete_IndexReader(void* imarg1);
void _wrap_delete_MultiReader(void* imarg1);

#ifdef __cplusplus
}
#endif

#endif

