/* -----------------------------------------------------------------------------*
 *  Standard SWIG API Alias
 * -----------------------------------------------------------------------------*/


#define SWIG_TypeQuery(name)         SWIG_Python_TypeQuery(name)
#define SWIG_TypeRegister(ti)        SWIG_Python_TypeRegister(ti)
#define SWIG_TypeClientData(ti, cd)   SWIG_Python_TypeClientData(ti, cd)
#define SWIG_PropagateClientData(ti)  SWIG_Python_PropagateClientData(ti)
