<?hh

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */
<<__NativeData("_wrap_Circle")>>
class Circle {
<<__Native>>
function __construct(...$argv): void;

<<__Native>>
public function area() : int;

<<__Native>>
static public function info() : void;

<<__Native>>
public function Circle_z_set(int $arg2) : void;

<<__Native>>
public function Circle_z_get() : int;

<<__Native>>
static public function Circle_objectCount_set(int $arg1) : void;

<<__Native>>
static public function Circle_objectCount_get() : int;

<<__Native>>
function __destruct() ;

}
<<__Native>>
function pnt(resource $arg1) : void;

