name: macos-cmake

on:
  push:
    paths-ignore:
      - 'CHANGES*'
      - 'Doc/**'
      - 'Tools/CI-linux-*'
      - 'Tools/GHA-linux-*'
      - 'appveyor.yml'
  pull_request:
    branches: master
    paths-ignore:
      - 'CHANGES*'
      - 'Doc/**'
      - 'Tools/CI-linux-*'
      - 'Tools/GHA-linux-*'
      - 'appveyor.yml'

permissions:
  contents: read

jobs:
  cmake:
    runs-on: ${{ matrix.os }}

    name: cmake ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-14, macos-26]
      # Run all of them, as opposed to aborting when one fails
      fail-fast: false

    env:
      SWIG_INSTALL_PREFIX: '${{ github.workspace }}/swig.install'

    steps:
    - name: Machine Info
      run: |
          echo "number of logical cores logical cpu..."
          sysctl -n hw.logicalcpu
          echo "number of cores..."
          sysctl -n hw.ncpu
          echo "uname..."
          uname -a
          echo "total memory in bytes..."
          sysctl hw.memsize

    - name: Checkout
      uses: actions/checkout@v4
      with:
        show-progress: false

    # See Homebrew site: https://brew.sh/
    - name: Install Dependencies
      run: |
          brew install bison
          # Ensure we use the newer version of bison
          bison_dir="$(brew ls bison | grep '/bin/bison$' | head -1 | sed 's?/bison$??')"
          echo "$bison_dir" >> $GITHUB_PATH

    - name: Configure
      run: |
          cmake --version
          cmake -S . -B build \
            -DCMAKE_INSTALL_PREFIX=$SWIG_INSTALL_PREFIX \
            -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build -j

    - name: Test
      run: ctest --test-dir build -V --output-on-failure

    - name: Install
      run: |
          cmake --install build
          $SWIG_INSTALL_PREFIX/bin/swig -version
          $SWIG_INSTALL_PREFIX/bin/swig -pcreversion
